# Advisor Feedback Round 1 — CDC Brain

This notebook loads the outputs from `week1_cdc_brain.ipynb` and creates a ranking table for your advisor.

## What it gives you
- a summary table for all 5 children
- a detailed packet per child
- a blank CSV scoring sheet with one row per child

## Suggested scoring
Ask your advisor to rate each case on:
- estimated developmental ranges
- activity appropriateness
- safety / overclaiming
- usefulness
- overall quality

In [1]:
# If needed, run this once.
%pip install pandas ipython

Requirement already satisfied: pandas in /opt/homebrew/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: ipython in /Users/sara/Library/Python/3.11/lib/python/site-packages (9.10.1)
Requirement already satisfied: numpy>=1.23.2 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2026.1)
Requirement already satisfied: decorator>=4.3.2 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (5.14.3)
Requirement already satisfied: typing_extensions>=4.6 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from ipython) (4.15.0)
Requirement already satisfied: wcwidth in /Users/sara/Library/Python/3.11/lib/python/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from jedi>=0.18.1->ipython) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from pexpect>4.3->ipython) (0.7.0)
Requirement already satisfied: six>=1.5 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from stack_data>=0.6.0->ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from stack_data>=0.6.0->ipython) (3.0.1)
Requirement already satisfied: pure-eval in /Users/sara/Library/Python/3.11/lib/python/site-packages (from stack_data>=0.6.0->ipython) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import json
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display

In [3]:
def load_outputs():
    candidate_paths = [
        Path("week1_cdc_outputs.json"),
        Path("./notebooks/week1_cdc_outputs.json"),
        Path("../week1_cdc_outputs.json"),
        Path("../../week1_cdc_outputs.json"),
        Path("week1_cdc_outputs_sample.json"),
    ]
    for path in candidate_paths:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8")), path
    raise FileNotFoundError("Could not find week1_cdc_outputs.json. Run the CDC brain notebook first.")

results, results_path = load_outputs()
print("Loaded outputs from:", results_path.resolve())
print("Cases:", len(results))

Loaded outputs from: /Users/sara/Projects/Genex/notebooks/week1_cdc_outputs.json
Cases: 5

In [4]:
summary_rows = []
for result in results:
    summary_rows.append({
        "case_id": result["case_id"],
        "name": result["name"],
        "condition": result["condition"],
        "chronological_age_months": result["chronological_age_months"],
        "speech_range": result["developmental_profile"]["speech_language"]["estimated_range_months"],
        "motor_range": result["developmental_profile"]["motor"]["estimated_range_months"],
        "social_range": result["developmental_profile"]["social_communication"]["estimated_range_months"],
        "adaptive_range": result["developmental_profile"]["adaptive_cognitive"]["estimated_range_months"],
    })
summary_df = pd.DataFrame(summary_rows)
summary_df

,case_id,name,condition,chronological_age_months,speech_range,motor_range,social_range,adaptive_range
0,C01,Emma,Down syndrome,36,24-30,30-36,30-36,24-30
1,C02,Noah,Autism,60,36-48,60-60,30-36,36-48
2,C03,Liam,ADHD,54,36-48,36-48,24-30,36-48
3,C04,Maya,Speech delay,48,30-36,48-60,36-48,48-60
4,C05,Sofia,Cerebral palsy,72,60-60,30-36,48-60,48-60

In [5]:
# Blank scoring table for the advisor.
feedback_rows = []
for result in results:
    feedback_rows.append({
        "case_id": result["case_id"],
        "name": result["name"],
        "condition": result["condition"],
        "score_ranges_1to5": "",
        "score_activities_1to5": "",
        "score_safety_1to5": "",
        "score_usefulness_1to5": "",
        "score_overall_1to5": "",
        "comments": "",
    })

feedback_df = pd.DataFrame(feedback_rows)
feedback_df

,case_id,name,condition,score_ranges_1to5,score_activities_1to5,score_safety_1to5,score_usefulness_1to5,score_overall_1to5,comments
0,C01,Emma,Down syndrome,,,,,,
1,C02,Noah,Autism,,,,,,
2,C03,Liam,ADHD,,,,,,
3,C04,Maya,Speech delay,,,,,,
4,C05,Sofia,Cerebral palsy,,,,,,

In [6]:
def show_case_packet(case_id):
    matched = [r for r in results if r["case_id"] == case_id]
    if not matched:
        raise ValueError(f"No case found for {case_id}")
    result = matched[0]

    display(Markdown(f"# {result['case_id']} — {result['name']}"))
    display(Markdown(
        f"**Condition:** {result['condition']}  \
"
        f"**Chronological age (months):** {result['chronological_age_months']}  \
"
        f"**CDC start month:** {result['cdc_start_month']}  \
"
        f"**Concern:** {result['concern_text']}"
    ))

    for domain_key, profile in result["developmental_profile"].items():
        domain_title = domain_key.replace("_", " ").title()
        display(Markdown(f"## {domain_title}"))
        display(Markdown(
            f"**Estimated range:** {profile['estimated_range_months']} months  \
"
            f"**Confidence:** {profile['confidence']}"
        ))

        asked_lines = []
        for item in profile["asked"]:
            asked_lines.append(f"- [{item['band_month']}m] {item['question']} → **{item['answer']}**")
        display(Markdown("### Asked CDC questions\n" + "\n".join(asked_lines)))

        activity_lines = []
        for act in result["activities_by_domain"][domain_key]:
            activity_lines.append(
                f"**{act.get('activity_number')}. {act.get('title')}** ({act.get('duration_min')} min)  \
"
                f"Why: {act.get('why_this_fits')}  \
"
                f"Materials: {act.get('materials')}  \
"
                f"Instructions: {act.get('instructions')}  \
"
                f"Adaptation: {act.get('adaptation')}"
            )
        display(Markdown("### Suggested activities\n\n" + "\n\n".join(activity_lines)))

show_case_packet("C01")

# C01 — Emma

**Condition:** Down syndrome  **Chronological age (months):** 36  **CDC start month:** 36  **Concern:** Parents want a home plan for communication, motor skills, and daily routines.

## Speech Language

**Estimated range:** 24-30 months  **Confidence:** 0.82

### Asked CDC questions
- [36m] talks with you in conversation using at least two back and forth exchangess → **with_help**
- [36m] ask who or what or where or why questions like where is mommy or where is daddy → **with_help**
- [30m] says about 50 words → **sometimes**
- [30m] say two or more words toghether with one action word like doggie run → **sometimes**

### Suggested activities

**1. Picture-supported requesting** (7 min)  Why: Matches a child with chronological age 36 months and estimated Speech / Language around 24-30 months.  Materials: common home items  Instructions: Use two preferred items and prompt the child to point, sign, or say what they want.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**2. Expand their communication** (9 min)  Why: Matches a child with chronological age 36 months and estimated Speech / Language around 24-30 months.  Materials: common home items  Instructions: Repeat the child's word and add one more word during play or snacks.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**3. WH-question picture practice** (5 min)  Why: Matches a child with chronological age 36 months and estimated Speech / Language around 24-30 months.  Materials: common home items  Instructions: Use picture cards to practice who, what, or where questions.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**4. Routine-based language** (7 min)  Why: Matches a child with chronological age 36 months and estimated Speech / Language around 24-30 months.  Materials: common home items  Instructions: Practice short phrases during snack, bath, or dressing routines.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**5. Choice making with pause time** (9 min)  Why: Matches a child with chronological age 36 months and estimated Speech / Language around 24-30 months.  Materials: common home items  Instructions: Offer a choice and wait 5 seconds before helping.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

## Motor

**Estimated range:** 30-36 months  **Confidence:** 0.82

### Asked CDC questions
- [36m] strings items together like large beads or macaroni → **sometimes**
- [36m] puts on some clothes by himself like loose pants or a jacket → **sometimes**
- [30m] uses hands to twist things like turning doorknobs or unscrewing lids → **yes**
- [30m] takes some clothes off by himself like loose pants or an open jacket → **yes**

### Suggested activities

**1. Supported obstacle path** (7 min)  Why: Matches a child with chronological age 36 months and estimated Motor around 30-36 months.  Materials: common home items  Instructions: Create a short safe path for stepping, reaching, and balance.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**2. Sit-to-stand repetitions** (9 min)  Why: Matches a child with chronological age 36 months and estimated Motor around 30-36 months.  Materials: common home items  Instructions: Practice rising from a chair or cushion during play.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**3. Reach and place game** (5 min)  Why: Matches a child with chronological age 36 months and estimated Motor around 30-36 months.  Materials: common home items  Instructions: Place toys at different heights to practice reaching and controlled movement.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**4. Ball roll and stop** (7 min)  Why: Matches a child with chronological age 36 months and estimated Motor around 30-36 months.  Materials: common home items  Instructions: Roll a ball back and forth and add stop/go cues.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**5. Core and balance play** (9 min)  Why: Matches a child with chronological age 36 months and estimated Motor around 30-36 months.  Materials: common home items  Instructions: Use floor play positions that encourage trunk control and balance.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

## Social Communication

**Estimated range:** 30-36 months  **Confidence:** 0.82

### Asked CDC questions
- [36m] calms down within 10 minutes after you leave her like at childcare drop off → **sometimes**
- [36m] notices other children and joins them to play → **sometimes**
- [30m] plays next to other children and sometimes plays with them → **yes**
- [30m] shows you what she can do by saying look at me → **yes**

### Suggested activities

**1. Turn-taking with favorite toy** (7 min)  Why: Matches a child with chronological age 36 months and estimated Social / Communication around 30-36 months.  Materials: common home items  Instructions: Use a favorite toy and practice clear my-turn/your-turn routines.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**2. Shared attention show-and-share** (9 min)  Why: Matches a child with chronological age 36 months and estimated Social / Communication around 30-36 months.  Materials: common home items  Instructions: Encourage the child to show an object and look back to the caregiver.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**3. Pretend play routine** (5 min)  Why: Matches a child with chronological age 36 months and estimated Social / Communication around 30-36 months.  Materials: common home items  Instructions: Model a simple pretend routine like feeding a doll or stuffed animal.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**4. Name-response game** (7 min)  Why: Matches a child with chronological age 36 months and estimated Social / Communication around 30-36 months.  Materials: common home items  Instructions: Use playful name-calling and immediate reinforcement when the child responds.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**5. Simple peer-style game** (9 min)  Why: Matches a child with chronological age 36 months and estimated Social / Communication around 30-36 months.  Materials: common home items  Instructions: Play a short, rule-based game with waiting and imitation.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

## Adaptive Cognitive

**Estimated range:** 24-30 months  **Confidence:** 0.82

### Asked CDC questions
- [36m] draws a circle when you show her how → **with_help**
- [36m] avoids touching hot objects like the stove when you warn her → **with_help**
- [30m] uses things to pretend like feeding a block to a doll as if it were food → **sometimes**
- [30m] shows simple problem solving skills like standing on a small stool to reach something → **sometimes**

### Suggested activities

**1. Two-step helper task** (7 min)  Why: Matches a child with chronological age 36 months and estimated Adaptive / Cognitive around 24-30 months.  Materials: common home items  Instructions: Practice a short daily routine with two simple steps.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**2. Visual cleanup routine** (9 min)  Why: Matches a child with chronological age 36 months and estimated Adaptive / Cognitive around 24-30 months.  Materials: common home items  Instructions: Use pictures or gestures for cleanup or dressing steps.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**3. Matching and sorting** (5 min)  Why: Matches a child with chronological age 36 months and estimated Adaptive / Cognitive around 24-30 months.  Materials: common home items  Instructions: Sort familiar objects by category, color, or function.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**4. Mini task board** (7 min)  Why: Matches a child with chronological age 36 months and estimated Adaptive / Cognitive around 24-30 months.  Materials: common home items  Instructions: Use a tiny 2-3 step board for snack, dressing, or play setup.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

**5. Cause-and-effect problem solving** (9 min)  Why: Matches a child with chronological age 36 months and estimated Adaptive / Cognitive around 24-30 months.  Materials: common home items  Instructions: Use simple toys or household tasks that reward trial and error.  Adaptation: Reduce language demands, simplify the routine, and add modeling or support as needed.

In [7]:
# Save the blank feedback table so your advisor can fill it out after the meeting.
save_path = Path("advisor_feedback_cdc_round1.csv")
feedback_df.to_csv(save_path, index=False)
print("Saved:", save_path.resolve())

Saved: /Users/sara/Projects/Genex/notebooks/advisor_feedback_cdc_round1.csv