# Genex Interview + Activity Brain — v4

This notebook is the cleaned working notebook for the current Genex 0–5 developmental interview and activity-planning engine.

It supports two interview modes that share the same downstream planning pipeline:

## Mode A — Live parent mode
We answer the milestone questions directly, one by one, as if we were the parent or evaluator.

## Mode B — Synthetic parent mode
Gemini simulates the parent answers one question at a time from the child profile, while the Genex interview engine still selects the questions and computes the developmental profile.

After either mode, the notebook runs the same shared downstream steps:

1. delay estimation by domain
2. milestone question interview by category
3. developmental-age estimate by category
4. support-tier assignment by category
5. category activity-bank generation
6. weekly schedule generation
7. case summary table
8. optional advisor-report export

## Important working rule

If we edit any function cell, we should **restart the kernel and run the notebook from top to bottom again**.  
Most of the crashes in earlier versions were not caused by the file itself; they happened because the kernel had only some of the updated function definitions loaded.

## Recommended run order

1. Install cell  
2. Imports + environment setup  
3. Config + CDC loading  
4. Core engine cells  
5. Choose one mode:
   - run one live case
   - run one synthetic case
   - run a full advisor export packet

We strongly recommend using **Run All** or **Run All Above** before running the example cells at the end.

In [21]:
# Install once per notebook kernel if needed
%pip install -U pandas openpyxl python-dotenv openai google-genai reportlab

Requirement already satisfied: pandas in /opt/homebrew/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: openpyxl in /opt/homebrew/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: python-dotenv in /opt/homebrew/lib/python3.11/site-packages (1.2.2)
Requirement already satisfied: openai in /opt/homebrew/lib/python3.11/site-packages (2.33.0)
Requirement already satisfied: google-genai in /opt/homebrew/lib/python3.11/site-packages (1.73.1)
Requirement already satisfied: reportlab in /opt/homebrew/lib/python3.11/site-packages (4.4.10)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /opt/homebrew/lib/python3.11/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/homebrew/lib/python3.11/site-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/homebrew/lib/python3.11/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/homebrew/lib/python3.11/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/homebrew/lib/python3.11/site-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/homebrew/lib/python3.11/site-packages (from openai) (2.13.0)
Requirement already satisfied: sniffio in /opt/homebrew/lib/python3.11/site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /opt/homebrew/lib/python3.11/site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /opt/homebrew/lib/python3.11/site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /opt/homebrew/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /opt/homebrew/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/homebrew/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/homebrew/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.0 in /opt/homebrew/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai) (2.46.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/homebrew/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: google-auth<3.0.0,>=2.48.1 in /opt/homebrew/lib/python3.11/site-packages (from google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.49.2)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (2.33.1)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (15.0.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/homebrew/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/homebrew/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (46.0.7)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/homebrew/lib/python3.11/site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.6.3)
Requirement already satisfied: pillow>=9.0.0 in /opt/homebrew/lib/python3.11/site-packages (from reportlab) (12.2.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/homebrew/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.0.0)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/homebrew/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.6.3)
Requirement already satisfied: six>=1.5 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [22]:
%pip install -U google-genai

Requirement already satisfied: google-genai in /opt/homebrew/lib/python3.11/site-packages (1.73.1)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.48.1 in /opt/homebrew/lib/python3.11/site-packages (from google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.49.2)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (2.13.0)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (2.33.1)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /Users/sara/Library/Python/3.11/lib/python/site-packages (from google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in /opt/homebrew/lib/python3.11/site-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /opt/homebrew/lib/python3.11/site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/homebrew/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/homebrew/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (46.0.7)
Requirement already satisfied: certifi in /opt/homebrew/lib/python3.11/site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /opt/homebrew/lib/python3.11/site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/homebrew/lib/python3.11/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/homebrew/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.0 in /opt/homebrew/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (2.46.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/homebrew/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/homebrew/lib/python3.11/site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.6.3)
Requirement already satisfied: cffi>=2.0.0 in /opt/homebrew/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.0.0)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/homebrew/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.6.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [23]:
import os
os.environ["GEMINI_API_KEY"] = ""
print("GEMINI_API_KEY visible:", bool(os.environ.get("GEMINI_API_KEY")))

GEMINI_API_KEY visible: True

In [24]:
# ------------------------------------------------------------
# Imports + environment setup
# ------------------------------------------------------------
import os
import re
import json
import time
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List, Optional

import pandas as pd
from dotenv import load_dotenv
from IPython.display import display

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

try:
    from google import genai
except ImportError:
    genai = None

from reportlab.lib.pagesizes import landscape, LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.pdfbase.pdfmetrics import stringWidth

load_dotenv()

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "genex_interview_activity_v4"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RUN_STAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

openai_client = OpenAI(api_key=OPENAI_API_KEY) if (OpenAI is not None and OPENAI_API_KEY) else None
gemini_client = genai.Client(api_key=GEMINI_API_KEY) if (genai is not None and GEMINI_API_KEY) else None

print("OpenAI available:", openai_client is not None)
print("Gemini available:", gemini_client is not None)

# Optional temporary setup if needed for debugging.
# Do NOT save real keys inside the notebook file.
#
# import os
# os.environ["OPENAI_API_KEY"] = "your_real_openai_key_here"
# os.environ["GEMINI_API_KEY"] = "your_real_gemini_key_here"
# OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
# GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
# openai_client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None
# gemini_client = genai.Client(api_key=GEMINI_API_KEY) if GEMINI_API_KEY else None

OpenAI available: True
Gemini available: True

In [25]:
# ------------------------------------------------------------
# Config
# ------------------------------------------------------------
DOMAIN_CONFIG = {
    "movement_and_physical": {
        "display": "Movement / Physical",
        "short": "motor",
    },
    "social_and_emotional": {
        "display": "Social / Emotional",
        "short": "social_emotional",
    },
    "language_and_communication": {
        "display": "Language / Communication",
        "short": "language_communication",
    },
    "cognitive": {
        "display": "Cognitive / Adaptive",
        "short": "cognitive",
    },
}

ALIAS_TO_CATEGORY = {
    "movement and physical": "movement_and_physical",
    "physical": "movement_and_physical",
    "motor": "movement_and_physical",
    "gross motor": "movement_and_physical",

    "social and emotional": "social_and_emotional",
    "social and emotial": "social_and_emotional",
    "social_emotional": "social_and_emotional",
    "social": "social_and_emotional",

    "language and communication": "language_and_communication",
    "language": "language_and_communication",
    "speech": "language_and_communication",
    "speech and language": "language_and_communication",

    "cognitive": "cognitive",
    "adaptive": "cognitive",
}

ANSWER_SCORES = {
    "yes": 1.0,
    "sometimes": 0.4,
    "with_help": 0.2,
    "no": 0.0,
    "not_sure": 0.1,
}

VALID_ANSWERS = set(ANSWER_SCORES.keys())
VALID_PARENT_ANSWERS = {"yes", "sometimes", "with_help", "no", "not_sure"}

In [26]:
# ------------------------------------------------------------
# CDC loading + normalization
# ------------------------------------------------------------
def find_cdc_file(filename: str = "milestone-cdc-table.xlsx") -> Path:
    """Find the CDC milestone table in common project locations."""
    search_roots = [Path.cwd(), Path.cwd().parent, Path.cwd().parent.parent]
    for root in search_roots:
        candidate = root / filename
        if candidate.exists():
            return candidate.resolve()
    for root in search_roots:
        if root.exists():
            matches = list(root.rglob(filename))
            if matches:
                return matches[0].resolve()
    raise FileNotFoundError(
        f"Could not find {filename}. Put it in the repo root or notebooks parent folder."
    )

def load_cdc_table(path: Optional[str] = None):
    """Load and normalize the CDC milestone table."""
    path = Path(path) if path else find_cdc_file()
    df = pd.read_excel(path)

    df.columns = [str(c).strip().lower() for c in df.columns]
    df = df.rename(columns={"category ": "category", "milestone ": "milestone"})
    df["category"] = df["category"].astype(str).str.strip().str.lower()
    df["milestone"] = df["milestone"].astype(str).str.strip()
    df["months"] = pd.to_numeric(df["months"], errors="coerce")
    df = df.dropna(subset=["months", "category", "milestone"]).copy()
    df["months"] = df["months"].astype(int)
    df["category_key"] = df["category"].map(lambda x: ALIAS_TO_CATEGORY.get(x, x.replace(" ", "_")))
    df["question_id"] = [
        f"{row.category_key}_{row.months}_{i}"
        for i, row in enumerate(df.itertuples(), start=1)
    ]
    return df, path

cdc_df, cdc_path = load_cdc_table()
CDC_AGES = sorted(cdc_df["months"].dropna().unique().tolist())

print("Loaded CDC file:", cdc_path)
print("CDC ages:", CDC_AGES)
print("Rows:", len(cdc_df))

def get_category_questions(category_key: str, min_months: int, max_months: int) -> pd.DataFrame:
    subset = cdc_df[
        (cdc_df["category_key"] == category_key)
        & (cdc_df["months"] >= min_months)
        & (cdc_df["months"] <= max_months)
    ].sort_values(["months", "milestone"])
    return subset.copy()

display(cdc_df.head())

Loaded CDC file: /Users/sara/Projects/Genex/milestone-cdc-table.xlsx
CDC ages: [2, 4, 6, 9, 12, 15, 18, 24, 30, 36, 48, 60]
Rows: 159

,months,category,milestone,category_key,question_id
0,2,social and emotial,calms down when spoken to or picked up,social_and_emotional,social_and_emotional_2_1
1,2,social and emotial,looks at your face,social_and_emotional,social_and_emotional_2_2
2,2,social and emotial,seems happy to see you when you walk up to her,social_and_emotional,social_and_emotional_2_3
3,2,social and emotial,smiles when you talk to or smile at her,social_and_emotional,social_and_emotional_2_4
4,2,language and communication,makes sounds other than crying,language_and_communication,language_and_communication_2_5

In [27]:
# ------------------------------------------------------------
# Core helpers + state
# ------------------------------------------------------------
def normalize_answer(answer_text: str) -> str:
    """Normalize a raw parent answer into the allowed answer set."""
    t = str(answer_text).strip().lower().replace(" ", "_")
    if t in VALID_ANSWERS:
        return t
    if t in {"notsure", "unsure", "maybe"}:
        return "not_sure"
    return "not_sure"

def print_banner(title: str):
    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)

def extract_json_block(text: str) -> dict:
    """Parse strict JSON or recover a simple answer from loosely formatted model text."""
    text = str(text).strip()

    try:
        return json.loads(text)
    except Exception:
        pass

    m = re.search(r"```json\s*(\{.*?\})\s*```", text, flags=re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except Exception:
            pass

    m = re.search(r"(\{.*\})", text, flags=re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except Exception:
            pass

    lowered = text.lower()
    for label in ["with_help", "not_sure", "sometimes", "yes", "no"]:
        if label in lowered:
            return {"answer": label, "reason": text[:200]}

    if "with help" in lowered:
        return {"answer": "with_help", "reason": text[:200]}
    if "not sure" in lowered or "unsure" in lowered or "maybe" in lowered:
        return {"answer": "not_sure", "reason": text[:200]}

    raise ValueError(f"Could not parse JSON from model output: {text[:300]}")

def new_state() -> Dict[str, Any]:
    """Initialize the working state dictionary for one case."""
    return {
        "child": {},
        "delay_estimates": {},
        "qna": {},
        "dev_age": {},
        "activity_banks": {},
        "weekly_slot_allocation": {},
        "weekly_schedule": {},
    }

def print_child_reference(state: Dict[str, Any]) -> None:
    child = state["child"]
    print("\n" + "=" * 100)
    print("CHILD REFERENCE CHECK")
    print("=" * 100)
    print(f"Name: {child.get('name', '')}")
    print(f"Chronological age: {child.get('chronological_months', '')} months")
    print(f"Diagnosis / condition: {child.get('diagnosis', '')}")
    print(f"Parent concern: {child.get('concern', '')}")
    print(f"Daily time available: {child.get('daily_time_min', '')} minutes")

def intake_agent_live(state: Dict[str, Any]) -> Dict[str, Any]:
    """Collect a live child profile from user input."""
    print_banner("INTAKE AGENT")

    name = input("What is your child's name? ").strip()
    chronological_months = int(
        input("How old is your child in months? (for example: 18, 24, 36, 48, 60) ").strip()
    )
    diagnosis = input("Any diagnosis / condition? (type 'none' if none) ").strip()
    concern = input("What are your main concerns right now? ").strip()
    daily_time_min = int(
        input("About how many minutes per day can you usually spend helping or playing with your child? ").strip()
    )

    state["child"] = {
        "name": name,
        "chronological_months": chronological_months,
        "diagnosis": diagnosis,
        "concern": concern,
        "daily_time_min": daily_time_min,
    }
    return state["child"]

def init_state_from_case(case: Dict[str, Any], daily_time_min: int = 10) -> Dict[str, Any]:
    """Initialize a state object from a prefilled synthetic case."""
    state = new_state()
    state["child"] = {
        "name": case["child_name"],
        "chronological_months": int(case["age_months"]),
        "diagnosis": case["diagnosis"],
        "concern": case["concerns"],
        "daily_time_min": int(daily_time_min),
    }
    return state

In [28]:
# ------------------------------------------------------------
# Delay estimation
# ------------------------------------------------------------
def estimate_delay_gpt(
    diagnosis: str,
    concern: str,
    chronological_months: int,
    category_key: str,
    model: str = "gpt-4o-mini",
) -> Dict[str, Any]:
    """Estimate a rough starting delay in months for one domain.

    This is only a starting anchor for question selection, not the final developmental age.
    """
    category_display = DOMAIN_CONFIG[category_key]["display"]
    concern_l = (concern or "").lower()

    fallback_by_category = {
        "movement_and_physical": 3,
        "language_and_communication": 3,
        "social_and_emotional": 6,
        "cognitive": 6,
    }

    domain_keywords = {
        "movement_and_physical": [
            "motor", "movement", "walk", "run", "jump", "balance", "coordination",
            "fine motor", "gross motor", "grasp", "hand", "writing", "stairs", "falls",
            "hypotonia", "sitting", "rolling", "crawling"
        ],
        "language_and_communication": [
            "speech", "language", "talk", "communication", "words", "sentence",
            "understand", "expressive", "receptive", "verbal", "babbling", "no words"
        ],
        "social_and_emotional": [
            "social", "peer", "friend", "play", "emotion", "emotional",
            "behavior", "anger", "meltdown", "interaction", "turn taking",
            "regulation", "eye contact", "transitions", "bullied", "bullying"
        ],
        "cognitive": [
            "attention", "focus", "concentration", "school", "learning", "routine",
            "executive", "task", "independent", "adaptive", "toilet", "dressing",
            "self-care", "directions", "paying attention"
        ],
    }

    has_domain_signal = any(kw in concern_l for kw in domain_keywords.get(category_key, []))

    if openai_client is None:
        delay_months = fallback_by_category.get(category_key, 6)
        if not has_domain_signal:
            delay_months = min(delay_months, 6)
        return {
            "delay_months": delay_months,
            "reason": f"Fallback delay estimate used for {category_display} because the OpenAI client is not available.",
            "source": "fallback",
        }

    prompt = f"""
You are a pediatric developmental delay estimator agent for children ages 0 to 5 years.

Your job is to estimate a SINGLE STARTING DELAY in months for one developmental domain only.

This is NOT a diagnosis.
This is NOT a final developmental age.
This is ONLY a rough starting anchor for question selection.

Definition:
delay_months = chronological age in months - estimated functional developmental age in this specific domain

Child information:
- Chronological age in months: {chronological_months}
- Diagnosis / condition: {diagnosis}
- Parent concern: {concern}
- Domain to estimate: {category_display}

Instructions:
1. Think only about THIS domain, not overall development.
2. If the diagnosis or concern does NOT meaningfully affect this domain, return 0 to 6 months.
3. If this domain IS affected, estimate the child's functional developmental level in this domain, then convert it into delay_months.
4. Be conservative but realistic.
5. Never exceed the child's chronological age.
6. Return only one integer number of months.
7. Return strict JSON only.

Required JSON:
{{
  "delay_months": <integer>,
  "reason": "<one short sentence>"
}}
""".strip()

    try:
        resp = openai_client.chat.completions.create(
            model=model,
            temperature=0.2,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": "You return strict JSON only."},
                {"role": "user", "content": prompt},
            ],
        )

        parsed = json.loads(resp.choices[0].message.content)
        delay_months = int(parsed.get("delay_months", fallback_by_category.get(category_key, 6)))
        delay_months = max(0, min(delay_months, chronological_months))

        if not has_domain_signal and delay_months > 6:
            delay_months = 6

        return {
            "delay_months": delay_months,
            "reason": parsed.get("reason", ""),
            "source": "openai",
        }

    except Exception as e:
        return {
            "delay_months": fallback_by_category.get(category_key, 6),
            "reason": f"Fallback delay estimate used because the OpenAI call failed: {e}",
            "source": "fallback",
        }

def delay_agent_all_categories(state: Dict[str, Any], categories: Optional[List[str]] = None) -> Dict[str, Any]:
    """Estimate a starting delay for each category."""
    print_banner("DELAY ESTIMATOR AGENT")
    if not state.get("child"):
        raise ValueError("Child profile missing. Run intake first.")

    categories = categories or list(DOMAIN_CONFIG.keys())
    child = state["child"]

    for category_key in categories:
        est = estimate_delay_gpt(
            diagnosis=child["diagnosis"],
            concern=child["concern"],
            chronological_months=child["chronological_months"],
            category_key=category_key,
        )
        state["delay_estimates"][category_key] = est
        print(f"{DOMAIN_CONFIG[category_key]['display']}: {est['delay_months']} month starting delay | {est['reason']}")

    return state["delay_estimates"]

In [29]:
# ------------------------------------------------------------
# Core milestone engine
# ------------------------------------------------------------
def build_milestone_questions(
    state: Dict[str, Any],
    category_key: str,
    window_months: int = 24,
    target_questions_per_band: int = 3,
    max_bands: int = 3,
    max_questions_total: int = 9,
) -> List[Dict[str, Any]]:
    """Build a focused set of milestone questions around the estimated developmental range."""
    child = state["child"]
    chrono_months = min(child["chronological_months"], 60)
    delay_months = state["delay_estimates"].get(category_key, {}).get("delay_months", 12)

    approx_dev_months = max(2, chrono_months - delay_months)
    min_months = max(2, approx_dev_months - window_months // 2)
    max_months = min(60, approx_dev_months + window_months // 2)

    subset = get_category_questions(category_key, min_months=min_months, max_months=max_months)
    if subset.empty:
        subset = get_category_questions(category_key, min_months=min(CDC_AGES), max_months=max(CDC_AGES))

    available_months = sorted(subset["months"].unique().tolist())

    ordered_months = sorted(
        available_months,
        key=lambda m: (abs(m - approx_dev_months), m)
    )[:max_bands]

    questions = []
    for month in ordered_months:
        month_rows = subset[subset["months"] == month].sort_values("milestone")
        month_rows = month_rows.head(target_questions_per_band)

        for _, row in month_rows.iterrows():
            questions.append({
                "question_id": row["question_id"],
                "months": int(row["months"]),
                "milestone": row["milestone"],
                "question_text": f"Can {child['name']} {row['milestone']} right now? (yes / sometimes / with_help / no / not_sure)",
            })

    return questions[:max_questions_total]

def compute_dev_age_from_answers(
    answers: List[Dict[str, Any]],
    min_yes_confirm: int = 2,
    yes_ratio_confirm: float = 0.60,
) -> int:
    """Estimate developmental age using conservative month-band confirmation.

    A month band is confirmed only if:
    - it has at least `min_yes_confirm` YES answers
    - and YES answers are at least `yes_ratio_confirm` of that band
    """
    if not answers:
        return 6

    band_summary = {}
    for a in answers:
        month = int(a["months"])
        norm = a["norm_answer"]

        if month not in band_summary:
            band_summary[month] = {"total": 0, "yes": 0, "partial": 0, "no": 0}

        band_summary[month]["total"] += 1

        if norm == "yes":
            band_summary[month]["yes"] += 1
        elif norm in {"sometimes", "with_help", "not_sure"}:
            band_summary[month]["partial"] += 1
        else:
            band_summary[month]["no"] += 1

    answered_months = sorted(band_summary.keys())
    confirmed_months = []
    partial_months = []

    for month in answered_months:
        total = band_summary[month]["total"]
        yes_count = band_summary[month]["yes"]
        partial_count = band_summary[month]["partial"]
        yes_ratio = yes_count / total if total > 0 else 0

        if yes_count >= min_yes_confirm and yes_ratio >= yes_ratio_confirm:
            confirmed_months.append(month)
        elif yes_count > 0 or partial_count > 0:
            partial_months.append(month)

    if confirmed_months:
        return int(max(confirmed_months))

    if partial_months:
        anchor = int(min(partial_months))
        lower_candidates = [m for m in answered_months if m < anchor]
        return int(max(lower_candidates)) if lower_candidates else int(anchor)

    return int(min(answered_months))

def summarize_answers_by_band(answers: List[Dict[str, Any]]) -> Dict[int, Dict[str, Any]]:
    """Summarize answers by month band for debugging and advisor review."""
    band_summary = {}

    for a in answers:
        month = int(a["months"])
        norm = a["norm_answer"]

        if month not in band_summary:
            band_summary[month] = {
                "total": 0,
                "yes": 0,
                "partial": 0,
                "no": 0,
                "items": [],
            }

        band_summary[month]["total"] += 1
        band_summary[month]["items"].append({
            "milestone": a["milestone"],
            "answer": norm,
        })

        if norm == "yes":
            band_summary[month]["yes"] += 1
        elif norm in {"sometimes", "with_help", "not_sure"}:
            band_summary[month]["partial"] += 1
        else:
            band_summary[month]["no"] += 1

    for month in band_summary:
        total = band_summary[month]["total"]
        yes = band_summary[month]["yes"]
        band_summary[month]["yes_ratio"] = round(yes / total, 2) if total else 0.0

    return dict(sorted(band_summary.items()))

In [30]:
# ------------------------------------------------------------
# Q&A mode A — live parent
# ------------------------------------------------------------
def qna_agent_live(
    state: Dict[str, Any],
    category_key: str,
    min_yes_confirm: int = 2,
    yes_ratio_confirm: float = 0.60,
) -> Dict[str, Any]:
    """Run one domain interview in live mode using manual answers."""
    print_banner(f"MILESTONE Q&A AGENT — {DOMAIN_CONFIG[category_key]['display']}")

    if "qna" not in state:
        state["qna"] = {}
    if "dev_age" not in state:
        state["dev_age"] = {}

    questions = build_milestone_questions(
        state,
        category_key,
        window_months=24,
        target_questions_per_band=3,
        max_bands=3,
        max_questions_total=9,
    )

    if not questions:
        raise ValueError(
            f"No milestone questions found for category_key={category_key}. "
            f"Check category mapping and CDC normalization."
        )

    asked = []
    questions_by_month = {}
    for q in questions:
        questions_by_month.setdefault(q["months"], []).append(q)

    for month in sorted(questions_by_month.keys()):
        print(f"\n--- Asking {DOMAIN_CONFIG[category_key]['display']} milestones around {month} months ---")
        for q in questions_by_month[month]:
            ans = input(q["question_text"] + "\n").strip()
            norm = normalize_answer(ans)
            asked.append({
                "question_id": q["question_id"],
                "months": q["months"],
                "milestone": q["milestone"],
                "raw_answer": ans,
                "norm_answer": norm,
                "score": ANSWER_SCORES[norm],
                "answer_status": "ok",
            })

    dev_age = compute_dev_age_from_answers(
        asked,
        min_yes_confirm=min_yes_confirm,
        yes_ratio_confirm=yes_ratio_confirm,
    )

    state["qna"][category_key] = asked
    state["dev_age"][category_key] = dev_age

    chrono = state["child"]["chronological_months"]

    print("\nQuestion / answer transcript:")
    for item in asked:
        print(f"- [{item['months']}m] {item['milestone']} -> {item['norm_answer']}")

    band_summary = summarize_answers_by_band(asked)
    print("\nBand summary:")
    for month, info in band_summary.items():
        print(
            f"  {month}m | total={info['total']} | yes={info['yes']} | "
            f"partial={info['partial']} | no={info['no']} | yes_ratio={info['yes_ratio']}"
        )

    print(
        f"\nEstimated developmental age for {DOMAIN_CONFIG[category_key]['display']}: "
        f"{dev_age} months (chronological age {chrono} months)"
    )

    return {
        "category": category_key,
        "dev_age_months": dev_age,
        "answers": asked,
        "band_summary": band_summary,
    }

In [31]:
# ------------------------------------------------------------
# Q&A mode B — Gemini synthetic parent
# ------------------------------------------------------------
def gemini_parent_answer_one_question(
    child: Dict[str, Any],
    category_display: str,
    question_text: str,
    prior_answers: List[Dict[str, Any]],
    model: str = "gemini-2.5-flash",
    max_retries: int = 3,
) -> Dict[str, Any]:
    """Use Gemini to simulate one parent answer with retry/backoff protection."""
    if gemini_client is None:
        raise ValueError(
            "Gemini client is not available. Set GEMINI_API_KEY and rerun the environment setup cell."
        )

    if prior_answers:
        prior_text = "\n".join([f"- {x['question']} -> {x['answer']}" for x in prior_answers[-8:]])
    else:
        prior_text = "None yet."

    prompt = f"""
You are simulating a REAL parent answering developmental milestone questions about their child.

Rules:
- Answer ONLY from the child profile below.
- Be internally consistent across questions.
- Do NOT answer like a clinician or therapist.
- Answer like a parent who knows the child in daily life.
- Choose ONLY one answer:
  yes
  sometimes
  with_help
  no
  not_sure

Child profile:
- Name: {child.get('name')}
- Age: {child.get('chronological_months')} months
- Diagnosis / condition: {child.get('diagnosis')}
- Main concern: {child.get('concern')}

Current developmental category:
- {category_display}

Previous answers in this same interview:
{prior_text}

Question:
{question_text}

Return strict JSON only:
{{
  "answer": "yes|sometimes|with_help|no|not_sure",
  "reason": "one short parent-style reason"
}}
""".strip()

    last_error = None

    for attempt in range(max_retries):
        try:
            response = gemini_client.models.generate_content(
                model=model,
                contents=prompt,
            )

            raw_text = response.text if hasattr(response, "text") else str(response)
            parsed = extract_json_block(raw_text)

            answer = str(parsed.get("answer", "")).strip().lower().replace(" ", "_")
            if answer not in VALID_PARENT_ANSWERS:
                answer = "not_sure"

            return {
                "answer": answer,
                "reason": str(parsed.get("reason", "")).strip() or raw_text[:200],
                "raw_text": raw_text,
                "status": "ok",
            }

        except Exception as e:
            last_error = e
            print(f"Gemini warning on question: {question_text}")
            print(f"Attempt {attempt+1}/{max_retries} failed: {e}")

            if attempt < max_retries - 1:
                time.sleep(10 * (attempt + 1))

    return {
        "answer": "not_sure",
        "reason": f"Fallback after Gemini failure: {last_error}",
        "raw_text": "",
        "status": "api_error",
    }

def qna_agent_gemini_parent(
    state: Dict[str, Any],
    category_key: str,
    ask_limit_per_band: int = 3,
    min_yes_confirm: int = 2,
    yes_ratio_confirm: float = 0.60,
    gemini_model: str = "gemini-2.5-flash",
    delay_between_questions_sec: int = 5,
) -> Dict[str, Any]:
    """Run one domain interview in synthetic-parent mode.

    API failures are marked as `api_error` and excluded from developmental-age scoring.
    """
    print_banner(f"MILESTONE Q&A AGENT — {DOMAIN_CONFIG[category_key]['display']}")

    if "qna" not in state:
        state["qna"] = {}
    if "dev_age" not in state:
        state["dev_age"] = {}

    questions = build_milestone_questions(
        state,
        category_key,
        window_months=24,
        target_questions_per_band=3,
        max_bands=3,
        max_questions_total=9,
    )

    if not questions:
        raise ValueError(
            f"No milestone questions found for category_key={category_key}. "
            f"Check category mapping and CDC normalization."
        )

    asked = []
    prior_answers_for_gemini = []

    questions_by_month = {}
    for q in questions:
        questions_by_month.setdefault(q["months"], []).append(q)

    for month in sorted(questions_by_month.keys()):
        print(f"\n--- Asking {DOMAIN_CONFIG[category_key]['display']} milestones around {month} months ---")

        for q in questions_by_month[month][:ask_limit_per_band]:
            sim = gemini_parent_answer_one_question(
                child=state["child"],
                category_display=DOMAIN_CONFIG[category_key]["display"],
                question_text=q["question_text"],
                prior_answers=prior_answers_for_gemini,
                model=gemini_model,
                max_retries=3,
            )

            norm = normalize_answer(sim["answer"])

            asked_item = {
                "question_id": q["question_id"],
                "months": q["months"],
                "milestone": q["milestone"],
                "raw_answer": sim["answer"],
                "norm_answer": norm,
                "score": ANSWER_SCORES[norm],
                "parent_reason": sim["reason"],
                "answer_status": sim.get("status", "ok"),
            }
            asked.append(asked_item)

            prior_answers_for_gemini.append({
                "question": q["question_text"],
                "answer": sim["answer"],
            })

            print(
                f"Q: {q['question_text']}\n"
                f"A (Gemini-parent): {sim['answer']} | "
                f"status: {sim.get('status', 'ok')} | "
                f"reason: {sim['reason']}"
            )

            time.sleep(delay_between_questions_sec)

    usable_answers = [a for a in asked if a.get("answer_status") != "api_error"]

    dev_age = compute_dev_age_from_answers(
        usable_answers,
        min_yes_confirm=min_yes_confirm,
        yes_ratio_confirm=yes_ratio_confirm,
    )

    state["qna"][category_key] = asked
    state["dev_age"][category_key] = dev_age

    chrono = state["child"]["chronological_months"]

    print("\nQuestion / answer transcript:")
    for item in asked:
        print(
            f"- [{item['months']}m] {item['milestone']} -> {item['norm_answer']} "
            f"| status: {item.get('answer_status', 'ok')} "
            f"| reason: {item.get('parent_reason', '')}"
        )

    band_summary = summarize_answers_by_band(usable_answers)
    print("\nBand summary:")
    for month, info in band_summary.items():
        print(
            f"  {month}m | total={info['total']} | yes={info['yes']} | "
            f"partial={info['partial']} | no={info['no']} | yes_ratio={info['yes_ratio']}"
        )

    print(
        f"\nEstimated developmental age for {DOMAIN_CONFIG[category_key]['display']}: "
        f"{dev_age} months (chronological age {chrono} months)"
    )

    return {
        "category": category_key,
        "dev_age_months": dev_age,
        "answers": asked,
        "band_summary": band_summary,
    }

In [32]:

# ------------------------------------------------------------
# Support tier + shared planning engine
# ------------------------------------------------------------
def get_support_tier(state: Dict[str, Any], category_key: str) -> str:
    """Assign an age-aware support tier using milestone gap and starting delay.

    We intentionally keep this deterministic rather than asking a model again.
    This makes it easier to inspect, tune, and explain to advisors.
    """
    child = state["child"]
    chrono = min(child["chronological_months"], 60)
    dev_age = state["dev_age"].get(category_key, chrono)
    delay_est = state["delay_estimates"].get(category_key, {}).get("delay_months", 0)

    gap = max(0, chrono - dev_age)

    # Age-aware thresholds:
    # smaller month gaps matter more in infancy than they do in older children.
    light_gap_threshold = max(2, round(0.10 * chrono))
    primary_gap_threshold = max(5, round(0.20 * chrono))

    light_delay_threshold = max(4, round(0.10 * chrono))
    primary_delay_threshold = max(6, round(0.20 * chrono))

    # Weighted support score:
    # milestone gap is more important than the rough starting delay estimate,
    # but both contribute to the tier decision.
    support_score = (
        0.65 * (gap / primary_gap_threshold) +
        0.35 * (delay_est / primary_delay_threshold)
    )

    if gap >= primary_gap_threshold or support_score >= 1.0:
        return "needs_special_support"

    if (
        (gap >= light_gap_threshold and delay_est >= light_delay_threshold)
        or support_score >= 0.60
    ):
        return "monitor_and_enrich"

    return "no_special_support"

def no_special_support_needed(state: Dict[str, Any], category_key: str) -> bool:
    """Backward-compatible helper used elsewhere in the notebook."""
    return get_support_tier(state, category_key) == "no_special_support"

def select_next_milestones(state: Dict[str, Any], category_key: str, max_milestones: int = 6) -> Dict[str, Any]:
    """Select near-next-step milestones to drive the activity bank."""
    child = state["child"]
    dev_age = state["dev_age"].get(category_key, None)

    if dev_age is None:
        raise ValueError(f"No developmental age found for {category_key}. Run Q&A first.")

    if no_special_support_needed(state, category_key):
        return {
            "status": "no_special_support",
            "message": f"We do not think {child['name']} has a meaningful delay in {DOMAIN_CONFIG[category_key]['display']} and may not need special support in this category right now.",
            "milestones": [],
        }

    min_m = max(2, dev_age)
    max_m = min(60, dev_age + 12)

    subset = get_category_questions(category_key, min_months=min_m, max_months=max_m)
    if subset.empty:
        return {"status": "success", "milestones": []}

    subset = subset.sort_values(["months", "milestone"]).copy()
    milestones = []
    seen = set()

    for _, row in subset.iterrows():
        key = (int(row["months"]), str(row["milestone"]).strip())
        if key in seen:
            continue
        seen.add(key)
        milestones.append({
            "months": int(row["months"]),
            "milestone": row["milestone"],
        })

    return {"status": "success", "milestones": milestones[:max_milestones]}

def get_category_activity_guardrails(category_key: str) -> str:
    """Return domain-specific activity guardrails to reduce cross-domain drift."""
    if category_key == "movement_and_physical":
        return """
Category-specific rules for Movement / Physical:
- Focus on posture, strength, balance, coordination, reaching, grasping, sitting, crawling, standing, walking, or fine-motor use.
- The main goal should be physical skill practice.
- Do NOT make this mainly about speech, naming, imitation of sounds, or social-emotional labeling.
"""

    if category_key == "language_and_communication":
        return """
Category-specific rules for Language / Communication:
- Focus on sounds, babbling, turn-taking vocalization, following simple verbal directions, gestures for communication, word use, imitation of sounds, naming, requesting, commenting, and comprehension.
- The main goal should be communication.
- Do NOT make this mainly about gross motor practice, reaching, balance, climbing, or general physical exercise.
- If an object is used, it should support communication, not be the main task.
"""

    if category_key == "social_and_emotional":
        return """
Category-specific rules for Social / Emotional:
- Focus on eye contact, shared attention, social reciprocity, imitation of facial expressions, joint play, turn-taking, response to name, emotional connection, and interaction with caregiver or peers.
- The main goal should be social engagement or emotional regulation.
- Do NOT make this mainly about motor strengthening or naming/labeling language tasks unless the social interaction is clearly primary.
"""

    if category_key == "cognitive":
        return """
Category-specific rules for Cognitive / Adaptive:
- Focus on attention, problem-solving, object permanence, simple cause-and-effect, routines, imitation of actions, functional play, early self-help, and adaptive understanding.
- The main goal should be cognitive/adaptive skill building.
- Do NOT make this mainly about speech production or gross motor strengthening unless the cognitive/adaptive task is clearly primary.
"""

    return ""

def generate_category_activity_bank(
    state: Dict[str, Any],
    category_key: str,
    model: str = "gpt-4o-mini",
    activities_per_category: int = 6,
) -> Dict[str, Any]:
    """Generate one activity bank per category.

    We generate activities category-by-category first, then schedule them deterministically.
    """
    child = state["child"]
    category_display = DOMAIN_CONFIG[category_key]["display"]
    support_tier = get_support_tier(state, category_key)
    next_steps = select_next_milestones(state, category_key)

    if next_steps["status"] == "no_special_support":
        state["activity_banks"][category_key] = {
            "status": "no_special_support",
            "support_tier": support_tier,
            "summary": next_steps["message"],
            "activities": [],
        }
        return state["activity_banks"][category_key]

    dev_age = state["dev_age"][category_key]
    chrono_months = min(child["chronological_months"], 60)
    milestone_gap = max(0, chrono_months - dev_age)
    category_guardrails = get_category_activity_guardrails(category_key)

    milestone_lines = "\n".join([f"- ({m['months']} months) {m['milestone']}" for m in next_steps["milestones"]])
    if not milestone_lines:
        milestone_lines = "- No specific milestone items available in this range."

    if openai_client is None:
        fallback_activities = []
        for i, m in enumerate(next_steps["milestones"][:activities_per_category], start=1):
            fallback_activities.append({
                "activity_id": f"{category_key}_{i}",
                "title": f"Practice: {m['milestone']}",
                "instructions": f"Use a short, play-based home activity to practice: {m['milestone']}.",
                "duration_min": 5,
                "materials": "common toys or household items",
                "level": "current_or_next",
                "category": category_display,
                "goal": support_tier,
                "is_extended_activity": False,
                "extended_reason": "",
            })

        while len(fallback_activities) < activities_per_category:
            i = len(fallback_activities) + 1
            fallback_activities.append({
                "activity_id": f"{category_key}_{i}",
                "title": f"{category_display} practice {i}",
                "instructions": f"Do one short parent-guided home activity that supports {category_display.lower()} skills.",
                "duration_min": 5,
                "materials": "common toys or household items",
                "level": "current_or_next",
                "category": category_display,
                "goal": support_tier,
                "is_extended_activity": False,
                "extended_reason": "",
            })

        state["activity_banks"][category_key] = {
            "status": "fallback",
            "support_tier": support_tier,
            "summary": f"Fallback activity bank used for {category_display}.",
            "activities": fallback_activities,
        }
        return state["activity_banks"][category_key]

    prompt = f"""
You are a pediatric home-support planning agent helping a parent at home.

This is NOT a diagnosis and NOT a formal treatment plan.
Create a CATEGORY ACTIVITY BANK, not a day-by-day schedule.

Child:
- Name: {child['name']}
- Chronological age: {child['chronological_months']} months
- Diagnosis / condition: {child['diagnosis']}
- Parent concern: {child['concern']}
- Category: {category_display}
- Support tier: {support_tier}
- Estimated developmental age in this category: {dev_age} months
- Estimated milestone gap in this category: {milestone_gap} months

Relevant milestone targets:
{milestone_lines}

Category-specific guardrails:
{category_guardrails}

Task:
Create {activities_per_category} realistic home activities for this category.

Instructions:
1. Activities must fit the child's chronological age and estimated developmental level.
2. Activities should be practical for home.
3. Keep language parent-friendly.
4. Include a mix of current-level practice and near next-step practice.
5. Most activities should be short and realistic for home: usually 3, 5, 7, or 10 minutes.
6. Avoid making many 15-minute activities unless clearly justified.
7. Rare exception: some activities may benefit from longer continuous time, such as a short playdate or peer practice activity.
8. Only mark an activity as extended if it is clearly justified.
9. Extended activities should usually be 15 or 20 minutes.
10. Do not make more than 1 or 2 extended activities in this category.
11. Each activity must clearly belong to THIS category first and foremost.
12. Avoid cross-domain drift. The main goal of the activity should be obvious from the category.
13. If an activity could fit multiple domains, choose the version that best matches this category's core skill.
14. For each activity, set "goal" to one of: "needs_special_support", "monitor_and_enrich", or "current_or_next", whichever fits best.
15. Return strict JSON only.

Required JSON:
{{
  "summary": "...",
  "activities": [
    {{
      "activity_id": "1",
      "title": "...",
      "instructions": "...",
      "duration_min": 5,
      "materials": "...",
      "level": "current_or_next",
      "category": "<category name>",
      "goal": "{support_tier}",
      "is_extended_activity": false,
      "extended_reason": ""
    }}
  ]
}}
""".strip()

    try:
        resp = openai_client.chat.completions.create(
            model=model,
            temperature=0.3,
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": "You return strict JSON only and stay non-diagnostic, practical, and parent-friendly."
                },
                {"role": "user", "content": prompt},
            ],
        )

        bank = json.loads(resp.choices[0].message.content)

        if "activities" not in bank or not isinstance(bank["activities"], list):
            bank["activities"] = []

        for idx, activity in enumerate(bank["activities"], start=1):
            activity.setdefault("activity_id", f"{category_key}_{idx}")
            activity.setdefault("category", category_display)
            activity.setdefault("duration_min", 5)
            activity.setdefault("materials", "common household items")
            activity.setdefault("level", "current_or_next")
            activity["goal"] = support_tier
            activity.setdefault("is_extended_activity", False)
            activity.setdefault("extended_reason", "")

        state["activity_banks"][category_key] = {
            "status": "success",
            "support_tier": support_tier,
            "summary": bank.get("summary", f"Created activity bank for {category_display}."),
            "activities": bank["activities"][:activities_per_category],
        }
        return state["activity_banks"][category_key]

    except Exception as e:
        fallback_activities = []
        for i, m in enumerate(next_steps["milestones"][:activities_per_category], start=1):
            fallback_activities.append({
                "activity_id": f"{category_key}_{i}",
                "title": f"Practice: {m['milestone']}",
                "instructions": f"Use a short, play-based home activity to practice: {m['milestone']}.",
                "duration_min": 5,
                "materials": "common toys or household items",
                "level": "current_or_next",
                "category": category_display,
                "goal": support_tier,
                "is_extended_activity": False,
                "extended_reason": "",
            })

        while len(fallback_activities) < activities_per_category:
            i = len(fallback_activities) + 1
            fallback_activities.append({
                "activity_id": f"{category_key}_{i}",
                "title": f"{category_display} practice {i}",
                "instructions": f"Do one short parent-guided home activity that supports {category_display.lower()} skills.",
                "duration_min": 5,
                "materials": "common toys or household items",
                "level": "current_or_next",
                "category": category_display,
                "goal": support_tier,
                "is_extended_activity": False,
                "extended_reason": "",
            })

        state["activity_banks"][category_key] = {
            "status": "fallback",
            "support_tier": support_tier,
            "summary": f"Fallback activity bank used for {category_display} because OpenAI failed: {e}",
            "activities": fallback_activities,
        }
        return state["activity_banks"][category_key]

def allocate_weekly_slots(state: Dict[str, Any]) -> Dict[str, Any]:
    """Allocate weekly minutes across categories using support tier + milestone gap."""
    child = state["child"]
    chrono = min(child["chronological_months"], 60)
    daily_time_min = int(child["daily_time_min"])
    weekly_minutes = daily_time_min * 5

    supported_categories = []
    gap_by_category = {}
    weight_by_category = {}
    base_minutes_by_category = {}

    for category_key in DOMAIN_CONFIG:
        tier = get_support_tier(state, category_key)
        if tier == "no_special_support":
            continue

        supported_categories.append(category_key)
        dev_age = state["dev_age"].get(category_key, chrono)
        gap = max(0, chrono - dev_age)
        gap_by_category[category_key] = gap

        if tier == "needs_special_support":
            weight_by_category[category_key] = max(1.0, float(gap))
            base_minutes_by_category[category_key] = 5
        else:  # monitor_and_enrich
            weight_by_category[category_key] = max(1.0, float(gap)) * 0.5
            base_minutes_by_category[category_key] = 3

    if not supported_categories:
        allocation = {
            "daily_time_min": daily_time_min,
            "weekly_minutes": weekly_minutes,
            "supported_categories": [],
            "gap_by_category": {},
            "target_minutes_by_category": {},
        }
        state["weekly_slot_allocation"] = allocation
        return allocation

    total_base = sum(base_minutes_by_category.values())

    if total_base > weekly_minutes:
        scale = weekly_minutes / total_base
        base_minutes_by_category = {
            k: max(1, int(round(v * scale)))
            for k, v in base_minutes_by_category.items()
        }

    target_minutes_by_category = base_minutes_by_category.copy()
    used_minutes = sum(target_minutes_by_category.values())
    remaining_minutes = max(0, weekly_minutes - used_minutes)

    weights = weight_by_category.copy()
    total_weight = sum(weights.values())

    if total_weight > 0 and remaining_minutes > 0:
        for k in supported_categories:
            extra = round(remaining_minutes * (weights[k] / total_weight))
            target_minutes_by_category[k] += extra

    total_target = sum(target_minutes_by_category.values())
    while total_target > weekly_minutes:
        biggest = max(target_minutes_by_category, key=target_minutes_by_category.get)
        if target_minutes_by_category[biggest] > 1:
            target_minutes_by_category[biggest] -= 1
            total_target -= 1
        else:
            break

    allocation = {
        "daily_time_min": daily_time_min,
        "weekly_minutes": weekly_minutes,
        "supported_categories": supported_categories,
        "gap_by_category": gap_by_category,
        "target_minutes_by_category": target_minutes_by_category,
    }
    state["weekly_slot_allocation"] = allocation
    return allocation

def pick_activity_that_fits(
    activities: List[Dict[str, Any]],
    used_indices: set,
    remaining_minutes: int,
) -> Optional[Dict[str, Any]]:
    """Greedy helper: pick the shortest unused activity that fits the remaining minutes."""
    candidates = []
    for idx, activity in enumerate(activities):
        if idx in used_indices:
            continue
        duration = int(activity.get("duration_min", 5))
        if duration <= remaining_minutes:
            candidates.append((duration, idx, activity))

    if not candidates:
        return None

    candidates = sorted(candidates, key=lambda x: x[0])
    duration, idx, activity = candidates[0]
    used_indices.add(idx)
    return activity

def _recompute_assigned_minutes(days: Dict[str, Any], target_minutes_by_category: Dict[str, int]) -> Dict[str, int]:
    """Recompute assigned minutes by category from the current day schedule."""
    assigned_minutes = {k: 0 for k in target_minutes_by_category.keys()}
    for _, day_info in days.items():
        for item in day_info.get("items", []):
            k = item.get("category_key")
            if k in assigned_minutes:
                assigned_minutes[k] += int(item.get("duration_min", 0))
    return assigned_minutes

def ensure_minimum_presence_for_monitor_categories(state: Dict[str, Any], days: Dict[str, Any]) -> Dict[str, Any]:
    """Ensure monitor/enrich categories get at least one short activity when possible.

    First, try to place a short activity into a day with free time.
    If every day is too full, try a gentle swap:
    replace one activity from a category that is currently OVER its target
    so the missing monitor/enrich category is not invisible in the weekly plan.
    """
    allocation = state.get("weekly_slot_allocation", {})
    target_minutes_by_category = allocation.get("target_minutes_by_category", {})
    child = state["child"]
    daily_time_min = int(child["daily_time_min"])

    assigned_minutes = _recompute_assigned_minutes(days, target_minutes_by_category)

    for category_key in target_minutes_by_category.keys():
        tier = get_support_tier(state, category_key)

        if tier != "monitor_and_enrich":
            continue
        if target_minutes_by_category.get(category_key, 0) <= 0:
            continue
        if assigned_minutes.get(category_key, 0) > 0:
            continue

        bank = state.get("activity_banks", {}).get(category_key, {})
        activities = bank.get("activities", [])
        if not activities:
            continue

        short_candidates = [a for a in activities if int(a.get("duration_min", 5)) <= 5]
        if short_candidates:
            chosen = min(short_candidates, key=lambda a: int(a.get("duration_min", 5)))
        else:
            chosen = min(activities, key=lambda a: int(a.get("duration_min", 5)))

        chosen_duration = int(chosen.get("duration_min", 5))
        chosen_item = {
            "category_key": category_key,
            "category": DOMAIN_CONFIG[category_key]["display"],
            "title": chosen.get("title"),
            "instructions": chosen.get("instructions"),
            "duration_min": chosen_duration,
            "materials": chosen.get("materials", "common household items"),
            "level": chosen.get("level", "current_or_next"),
            "goal": chosen.get("goal", "monitor_and_enrich"),
        }

        # Pass 1: direct placement into a day that still has enough room.
        day_names_by_room = sorted(
            days.keys(),
            key=lambda d: daily_time_min - int(days[d].get("total_minutes", 0)),
            reverse=True,
        )

        placed = False
        for day_name in day_names_by_room:
            day_info = days[day_name]
            remaining = daily_time_min - int(day_info.get("total_minutes", 0))
            if remaining >= chosen_duration:
                day_info["items"].append(chosen_item)
                day_info["total_minutes"] += chosen_duration
                assigned_minutes = _recompute_assigned_minutes(days, target_minutes_by_category)
                placed = True
                break

        if placed:
            continue

        # Pass 2: gentle swap with a category that is over target.
        donor_candidates = []
        for day_name, day_info in days.items():
            for item_idx, item in enumerate(day_info.get("items", [])):
                donor_category = item.get("category_key")
                if donor_category not in assigned_minutes or donor_category == category_key:
                    continue

                donor_duration = int(item.get("duration_min", 0))
                donor_surplus = assigned_minutes.get(donor_category, 0) - target_minutes_by_category.get(donor_category, 0)
                new_total = int(day_info.get("total_minutes", 0)) - donor_duration + chosen_duration

                if donor_surplus > 0 and new_total <= daily_time_min:
                    donor_candidates.append((
                        donor_surplus,
                        donor_duration,
                        day_name,
                        item_idx,
                        donor_category,
                    ))

        if donor_candidates:
            donor_candidates.sort(
                key=lambda x: (
                    x[0],                    # largest surplus first
                    x[1] >= chosen_duration, # prefer donor durations that fully cover the new item
                    x[1],                    # then larger donor duration
                ),
                reverse=True,
            )

            _, _, day_name, item_idx, donor_category = donor_candidates[0]
            day_info = days[day_name]
            removed_item = day_info["items"].pop(item_idx)
            day_info["total_minutes"] -= int(removed_item.get("duration_min", 0))
            day_info["items"].append(chosen_item)
            day_info["total_minutes"] += chosen_duration
            assigned_minutes = _recompute_assigned_minutes(days, target_minutes_by_category)

    return days

def pick_weekly_bonus_extended_activity(
    state: Dict[str, Any],
    extended_in_schedule_threshold: int = 15,
    bonus_extended_cap_min: int = 20,
) -> Optional[Dict[str, Any]]:
    """Optional extended activity added only as a weekly bonus, not counted in the daily budget."""
    daily_time_min = int(state["child"]["daily_time_min"])

    if daily_time_min >= extended_in_schedule_threshold:
        return None

    allocation = state.get("weekly_slot_allocation", {})
    gap_by_category = allocation.get("gap_by_category", {})

    candidate_categories = sorted(
        gap_by_category.keys(),
        key=lambda k: gap_by_category[k],
        reverse=True,
    )

    for category_key in candidate_categories:
        bank = state.get("activity_banks", {}).get(category_key, {})
        activities = bank.get("activities", [])

        for activity in activities:
            if not activity.get("is_extended_activity", False):
                continue

            duration = int(activity.get("duration_min", 5))
            if duration > bonus_extended_cap_min:
                continue

            return {
                "category_key": category_key,
                "category": DOMAIN_CONFIG[category_key]["display"],
                "title": activity.get("title"),
                "instructions": activity.get("instructions"),
                "duration_min": duration,
                "materials": activity.get("materials", "common household items"),
                "level": activity.get("level", "current_or_next"),
                "goal": activity.get("goal", ""),
                "extended_reason": activity.get("extended_reason", ""),
            }

    return None

def build_weekly_schedule(state: Dict[str, Any]) -> Dict[str, Any]:
    """Build the final weekly plan from activity banks and allocated minutes."""
    if "weekly_slot_allocation" not in state:
        allocate_weekly_slots(state)

    allocation = state["weekly_slot_allocation"]
    daily_time_min = allocation["daily_time_min"]
    target_minutes_by_category = allocation["target_minutes_by_category"]

    days = {
        "day_1": {"items": [], "total_minutes": 0},
        "day_2": {"items": [], "total_minutes": 0},
        "day_3": {"items": [], "total_minutes": 0},
        "day_4": {"items": [], "total_minutes": 0},
        "day_5": {"items": [], "total_minutes": 0},
    }

    if not target_minutes_by_category:
        state["weekly_schedule"] = {
            "status": "no_special_support",
            "summary": "No categories need a scheduled weekly activity plan right now.",
            "days": days,
        }
        return state["weekly_schedule"]

    assigned_minutes_by_category = {k: 0 for k in target_minutes_by_category.keys()}
    used_activity_indices = {k: set() for k in target_minutes_by_category.keys()}
    day_names = list(days.keys())

    progress_made = True
    while progress_made:
        progress_made = False

        categories_in_priority_order = sorted(
            target_minutes_by_category.keys(),
            key=lambda k: target_minutes_by_category[k] - assigned_minutes_by_category[k],
            reverse=True,
        )

        for day_name in day_names:
            remaining_day_minutes = daily_time_min - days[day_name]["total_minutes"]
            if remaining_day_minutes <= 0:
                continue

            for category_key in categories_in_priority_order:
                remaining_cat_minutes = (
                    target_minutes_by_category[category_key] - assigned_minutes_by_category[category_key]
                )
                if remaining_cat_minutes <= 0:
                    continue

                bank = state["activity_banks"].get(category_key, {})
                activities = bank.get("activities", [])
                if not activities:
                    continue

                activity = pick_activity_that_fits(
                    activities=activities,
                    used_indices=used_activity_indices[category_key],
                    remaining_minutes=remaining_day_minutes,
                )
                if activity is None:
                    continue

                duration = int(activity.get("duration_min", 5))
                days[day_name]["items"].append({
                    "category_key": category_key,
                    "category": DOMAIN_CONFIG[category_key]["display"],
                    "title": activity.get("title"),
                    "instructions": activity.get("instructions"),
                    "duration_min": duration,
                    "materials": activity.get("materials", "common household items"),
                    "level": activity.get("level", "current_or_next"),
                    "goal": activity.get("goal", ""),
                })

                days[day_name]["total_minutes"] += duration
                assigned_minutes_by_category[category_key] += duration
                progress_made = True
                break

    # Small repair pass: if a monitor/enrich category got squeezed out completely,
    # try to place one short activity into any day that still has room.
    days = ensure_minimum_presence_for_monitor_categories(state, days)

    # Recompute assigned minutes after the repair pass.
    assigned_minutes_by_category = {k: 0 for k in target_minutes_by_category.keys()}
    for _, day_info in days.items():
        for item in day_info.get("items", []):
            k = item.get("category_key")
            if k in assigned_minutes_by_category:
                assigned_minutes_by_category[k] += int(item.get("duration_min", 0))

    bonus_activity = pick_weekly_bonus_extended_activity(
        state,
        extended_in_schedule_threshold=15,
        bonus_extended_cap_min=20,
    )

    schedule = {
        "status": "success",
        "summary": "Weekly schedule built from category activity banks and true daily minute limits.",
        "daily_time_min": daily_time_min,
        "target_minutes_by_category": target_minutes_by_category,
        "assigned_minutes_by_category": assigned_minutes_by_category,
        "days": days,
        "weekly_bonus_activity": bonus_activity,
    }

    state["weekly_schedule"] = schedule
    return schedule

def summarizer_agent(state: Dict[str, Any]) -> pd.DataFrame:
    """Summarize final case outputs into a tidy dataframe."""
    child = state["child"]
    rows = []
    allocation = state.get("weekly_slot_allocation", {}).get("target_minutes_by_category", {})

    for category_key in DOMAIN_CONFIG:
        delay_info = state["delay_estimates"].get(category_key, {})
        dev_age = state["dev_age"].get(category_key)
        chrono_for_gap = min(child.get("chronological_months", 0), 60)
        milestone_gap = None if dev_age is None else max(0, chrono_for_gap - dev_age)
        bank = state.get("activity_banks", {}).get(category_key, {})

        rows.append({
            "child_name": child.get("name"),
            "chronological_age_months": child.get("chronological_months"),
            "diagnosis": child.get("diagnosis"),
            "concern": child.get("concern"),
            "daily_time_min": child.get("daily_time_min"),
            "category": DOMAIN_CONFIG[category_key]["display"],
            "estimated_delay_months": delay_info.get("delay_months"),
            "delay_reason": delay_info.get("reason", ""),
            "estimated_dev_age_months": dev_age,
            "milestone_gap_months": milestone_gap,
            "support_tier": get_support_tier(state, category_key),
            "needs_special_support": not no_special_support_needed(state, category_key),
            "weekly_target_minutes_for_category": allocation.get(category_key, 0),
            "activity_bank_status": bank.get("status", "missing"),
            "activity_bank_summary": bank.get("summary", ""),
        })

    return pd.DataFrame(rows)

def display_weekly_schedule(state: Dict[str, Any]) -> None:
    """Print the final weekly schedule in a readable form."""
    schedule = state.get("weekly_schedule", {})

    print_banner("WEEKLY SCHEDULE")

    if schedule.get("status") == "no_special_support":
        print(schedule.get("summary", "No weekly schedule available."))
        return

    print("Summary:", schedule.get("summary", ""))
    print("Daily time budget:", schedule.get("daily_time_min"))
    print("Target minutes by category:", schedule.get("target_minutes_by_category", {}))
    print("Assigned minutes by category:", schedule.get("assigned_minutes_by_category", {}))

    for day_name, day_info in schedule.get("days", {}).items():
        print("\n" + "-" * 100)
        print(f"{day_name.upper()} — total {day_info.get('total_minutes', 0)} min")
        print("-" * 100)

        items = day_info.get("items", [])
        if not items:
            print("No scheduled activities.")
            continue

        for item in items:
            print(f"- [{item['category']}] {item['title']} ({item['duration_min']} min)")
            print(f"  Goal: {item.get('goal', '')}")
            print(f"  Instructions: {item['instructions']}")
            print(f"  Materials: {item['materials']}")

    bonus = schedule.get("weekly_bonus_activity")
    if bonus:
        print("\n" + "=" * 100)
        print("OPTIONAL WEEKLY BONUS ACTIVITY")
        print("=" * 100)
        print(f"- [{bonus['category']}] {bonus['title']} ({bonus['duration_min']} min)")
        print(f"  Goal: {bonus.get('goal', '')}")
        print(f"  Instructions: {bonus['instructions']}")
        print(f"  Materials: {bonus['materials']}")
        print(f"  Why extended: {bonus.get('extended_reason', '')}")

def run_downstream_planning(state: Dict[str, Any], display_schedule: bool = True) -> pd.DataFrame:
    """Run the shared post-interview planning pipeline."""
    for category_key in DOMAIN_CONFIG:
        generate_category_activity_bank(state, category_key)

    allocate_weekly_slots(state)
    build_weekly_schedule(state)

    summary_df = summarizer_agent(state)

    if display_schedule:
        display_weekly_schedule(state)

    return summary_df

In [33]:
# ------------------------------------------------------------
# Main runners
# ------------------------------------------------------------
def run_all_categories_live():
    """Run one full case in live-answer mode."""
    state = new_state()
    intake_agent_live(state)
    print_child_reference(state)

    delay_agent_all_categories(state)

    for category_key in DOMAIN_CONFIG:
        qna_agent_live(
            state,
            category_key,
            min_yes_confirm=2,
            yes_ratio_confirm=0.60,
        )

    summary_df = run_downstream_planning(state, display_schedule=True)
    return state, summary_df

def run_all_categories_gemini_parent(
    case: Dict[str, Any],
    daily_time_min: int = 10,
    gemini_model: str = "gemini-2.5-flash",
):
    """Run one full case in synthetic-parent mode using Gemini."""
    state = init_state_from_case(case, daily_time_min=daily_time_min)
    print_child_reference(state)

    delay_agent_all_categories(state)

    for category_key in DOMAIN_CONFIG:
        qna_agent_gemini_parent(
            state,
            category_key,
            ask_limit_per_band=3,
            min_yes_confirm=2,
            yes_ratio_confirm=0.60,
            gemini_model=gemini_model,
            delay_between_questions_sec=5,
        )

    summary_df = run_downstream_planning(state, display_schedule=True)
    return state, summary_df

def print_case_reference(case: dict, daily_time_min: int):
    print("\n" + "=" * 110)
    print(f"STARTING {case['case_id']} | {case['child_name']} | {case['age_label']} | {case['diagnosis']}")
    print("=" * 110)
    print(f"Concerns: {case['concerns']}")
    print(f"Daily time: {daily_time_min} min/day")

def run_case_live_from_prefilled_case(
    case: dict,
    default_daily_time_min: int = 10,
    min_yes_confirm: int = 2,
    yes_ratio_confirm: float = 0.60,
):
    """Run a prefilled case live while still asking milestone questions manually."""
    raw_daily = input(
        f"[{case['case_id']}] Daily minutes available? Press Enter for default {default_daily_time_min}: "
    ).strip()
    daily_time_min = int(raw_daily) if raw_daily else int(default_daily_time_min)

    state = init_state_from_case(case, daily_time_min=daily_time_min)
    print_case_reference(case, daily_time_min)
    delay_agent_all_categories(state)

    for category_key in DOMAIN_CONFIG:
        qna_agent_live(
            state,
            category_key,
            min_yes_confirm=min_yes_confirm,
            yes_ratio_confirm=yes_ratio_confirm,
        )

    summary_df = run_downstream_planning(state, display_schedule=True)
    return state, summary_df

def run_case_gemini_from_prefilled_case(
    case: dict,
    daily_time_min: int = 10,
    min_yes_confirm: int = 2,
    yes_ratio_confirm: float = 0.60,
    gemini_model: str = "gemini-2.5-flash",
):
    """Run a prefilled case fully in synthetic-parent mode."""
    state = init_state_from_case(case, daily_time_min=daily_time_min)
    print_case_reference(case, daily_time_min)
    delay_agent_all_categories(state)

    for category_key in DOMAIN_CONFIG:
        qna_agent_gemini_parent(
            state,
            category_key,
            ask_limit_per_band=3,
            min_yes_confirm=min_yes_confirm,
            yes_ratio_confirm=yes_ratio_confirm,
            gemini_model=gemini_model,
            delay_between_questions_sec=5,
        )

    summary_df = run_downstream_planning(state, display_schedule=True)
    return state, summary_df

In [34]:
# ------------------------------------------------------------
# Test cases
# ------------------------------------------------------------
cases = [
    {"case_id": "C01", "child_name": "Noah", "age_months": 10, "age_label": "10 months",
     "diagnosis": "Down syndrome",
     "concerns": "Not sitting independently yet, Hypotonia, slow feeding, socially engaged"},

    {"case_id": "C02", "child_name": "Maya", "age_months": 18, "age_label": "18 months",
     "diagnosis": "No formal diagnosis",
     "concerns": "No words yet, uses gestures, understands simple commands, good eye contact"},

    {"case_id": "C03", "child_name": "Leo", "age_months": 26, "age_label": "2y 2m",
     "diagnosis": "Autism spectrum disorder",
     "concerns": "Limited eye contact and few words, Repetitive play, transitions hard, picky eating"},

    {"case_id": "C04", "child_name": "Sofia", "age_months": 37, "age_label": "3y 1m",
     "diagnosis": "Prematurity history",
     "concerns": "Speech hard to understand, Fine motor delay, good comprehension"},

    {"case_id": "C05", "child_name": "Ethan", "age_months": 54, "age_label": "4y 6m",
     "diagnosis": "Cerebral palsy",
     "concerns": "Trouble keeping up in preschool, Self-care delays, frequent falls, difficulty with stairs, uses walker sometimes, good cognition"},

    {"case_id": "C06", "child_name": "Amina", "age_months": 60, "age_label": "5 years",
     "diagnosis": "Global developmental delay",
     "concerns": "Learning and routines are hard, Short attention span, follows only simple directions"},

    {"case_id": "C07", "child_name": "Lucas", "age_months": 14, "age_label": "14 months",
     "diagnosis": "Fragile X syndrome",
     "concerns": "Not walking, limited babbling, Sensory sensitivity, shy socially"},

    {"case_id": "C08", "child_name": "Emma", "age_months": 32, "age_label": "2y 8m",
     "diagnosis": "Suspected childhood apraxia of speech",
     "concerns": "Very limited speech output, Uses gestures, gets frustrated, inconsistent sounds"},

    {"case_id": "C09", "child_name": "Zain", "age_months": 48, "age_label": "4 years",
     "diagnosis": "Attention and self-regulation concerns (possible ADHD)",
     "concerns": "Very active, impulsive, Big emotional reactions, interrupts, difficulty following routines, social interest intact"},

    {"case_id": "C10", "child_name": "Isla", "age_months": 44, "age_label": "3y 8m",
     "diagnosis": "SYNGAP1-related disorder",
     "concerns": "Delayed speech and balance, Attention issues, clumsy gait, limited pretend play"},

    {"case_id": "C11", "child_name": "Aria", "age_months": 20, "age_label": "20 months",
     "diagnosis": "No diagnosis",
     "concerns": "Only ~10 words, very active, good eye contact, understands well"},

    {"case_id": "C12", "child_name": "Mateo", "age_months": 30, "age_label": "2y 6m",
     "diagnosis": "No formal diagnosis",
     "concerns": "Good eye contact but no words, lines up toys, responds to name inconsistently"},

    {"case_id": "C13", "child_name": "Luna", "age_months": 42, "age_label": "3y 6m",
     "diagnosis": "Speech delay",
     "concerns": "Limited speech, understands well, parents have very limited time for activities"},

    {"case_id": "C14", "child_name": "Ryan", "age_months": 50, "age_label": "4y 2m",
     "diagnosis": "No diagnosis",
     "concerns": "Tantrums, difficulty with transitions, strong language skills, social but rigid"},
]

df_cases = pd.DataFrame(cases)
display(df_cases)

,case_id,child_name,age_months,age_label,diagnosis,concerns
0,C01,Noah,10,10 months,Down syndrome,"Not sitting independently yet, Hypotonia, slow..."
1,C02,Maya,18,18 months,No formal diagnosis,"No words yet, uses gestures, understands simpl..."
2,C03,Leo,26,2y 2m,Autism spectrum disorder,"Limited eye contact and few words, Repetitive ..."
3,C04,Sofia,37,3y 1m,Prematurity history,"Speech hard to understand, Fine motor delay, g..."
4,C05,Ethan,54,4y 6m,Cerebral palsy,"Trouble keeping up in preschool, Self-care del..."
5,C06,Amina,60,5 years,Global developmental delay,"Learning and routines are hard, Short attentio..."
6,C07,Lucas,14,14 months,Fragile X syndrome,"Not walking, limited babbling, Sensory sensiti..."
7,C08,Emma,32,2y 8m,Suspected childhood apraxia of speech,"Very limited speech output, Uses gestures, get..."
8,C09,Zain,48,4 years,Attention and self-regulation concerns (possib...,"Very active, impulsive, Big emotional reaction..."
9,C10,Isla,44,3y 8m,SYNGAP1-related disorder,"Delayed speech and balance, Attention issues, ..."
10,C11,Aria,20,20 months,No diagnosis,"Only ~10 words, very active, good eye contact,..."
11,C12,Mateo,30,2y 6m,No formal diagnosis,"Good eye contact but no words, lines up toys, ..."
12,C13,Luna,42,3y 6m,Speech delay,"Limited speech, understands well, parents have..."
13,C14,Ryan,50,4y 2m,No diagnosis,"Tantrums, difficulty with transitions, strong ..."

In [35]:
# ------------------------------------------------------------
# Advisor-report helpers
# ------------------------------------------------------------
def severity_from_gap(gap_months: float) -> str:
    gap_months = 0 if pd.isna(gap_months) else float(gap_months)
    if gap_months <= 6:
        return "minimal / mild"
    elif gap_months <= 18:
        return "moderate"
    else:
        return "significant"

def split_concerns_to_bullets(concern_text: str, max_items: int = 4):
    items = [x.strip(" -•\n\t") for x in re.split(r"[,\n;]+", str(concern_text)) if x.strip()]
    return items[:max_items]

def extract_parent_qa_lines(state: dict, max_lines_for_pdf: int = 12):
    full_lines = []
    for category_key in DOMAIN_CONFIG.keys():
        answers = state.get("qna", {}).get(category_key, [])
        for a in answers:
            milestone = str(a.get("milestone", "")).strip()
            norm_answer = str(a.get("norm_answer", a.get("raw_answer", ""))).strip()
            months = a.get("months", "")
            status = a.get("answer_status", "ok")
            full_lines.append(f"[{months}m] {milestone} -> {norm_answer} ({status})")

    pdf_lines = full_lines[:max_lines_for_pdf]
    return full_lines, pdf_lines

def extract_focus_areas(summary_df: pd.DataFrame, max_items: int = 3):
    if summary_df is None or summary_df.empty:
        return []

    work = summary_df.copy()
    work = work[work["support_tier"].isin(["needs_special_support", "monitor_and_enrich"])].copy()
    if work.empty:
        return []

    work["tier_rank"] = work["support_tier"].map({
        "needs_special_support": 2,
        "monitor_and_enrich": 1,
        "no_special_support": 0,
    })
    sort_col = "milestone_gap_months" if "milestone_gap_months" in work.columns else "estimated_delay_months"
    work = work.sort_values(["tier_rank", sort_col], ascending=[False, False])

    return work["category"].tolist()[:max_items]

def extract_activities_for_case(state: dict, max_activities: int = 5):
    activities = []
    weekly_schedule = state.get("weekly_schedule", {})
    days = weekly_schedule.get("days", {})

    if isinstance(days, dict):
        for day_label, day_info in days.items():
            day_items = day_info.get("items", [])
            for item in day_items:
                activities.append({
                    "day": day_label,
                    "category": item.get("category", item.get("category_display", "")),
                    "title": item.get("title", ""),
                    "description": item.get("instructions", item.get("description", "")),
                    "duration_min": item.get("duration_min", ""),
                    "goal": item.get("goal", item.get("level", item.get("category", ""))),
                })

    if not activities:
        for category_key, bank in state.get("activity_banks", {}).items():
            for item in bank.get("activities", [])[:2]:
                activities.append({
                    "day": "",
                    "category": DOMAIN_CONFIG.get(category_key, {}).get("display", category_key),
                    "title": item.get("title", ""),
                    "description": item.get("instructions", item.get("description", "")),
                    "duration_min": item.get("duration_min", ""),
                    "goal": item.get("goal", item.get("level", "current_or_next")),
                })

    return activities[:max_activities]

def build_case_payload(case: dict, state: dict, summary_df: pd.DataFrame):
    concerns_bullets = split_concerns_to_bullets(case.get("concerns", ""), max_items=4)
    parent_qa_full, parent_qa_pdf = extract_parent_qa_lines(state, max_lines_for_pdf=12)
    focus_areas = extract_focus_areas(summary_df, max_items=3)
    activities = extract_activities_for_case(state, max_activities=5)

    domain_rows = []
    if summary_df is not None and not summary_df.empty:
        for _, row in summary_df.iterrows():
            gap = row.get("milestone_gap_months", row.get("estimated_delay_months", None))
            domain_rows.append({
                "category": row.get("category", ""),
                "estimated_dev_age_months": row.get("estimated_dev_age_months", ""),
                "gap_months": gap,
                "support_tier": row.get("support_tier", ""),
                "severity": severity_from_gap(gap if gap is not None else 0),
                "needs_special_support": row.get("needs_special_support", True),
                "summary": row.get("activity_bank_summary", ""),
            })

    support_categories = [r["category"] for r in domain_rows if r.get("support_tier") in {"needs_special_support", "monitor_and_enrich"}]
    if support_categories:
        summary_text = (
            f"This plan prioritizes {', '.join(support_categories[:3])} for {case['child_name']}. "
            f"The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview."
        )
    else:
        summary_text = (
            f"This output did not identify a strong need for special support across the reviewed categories, "
            f"but the family can continue monitoring development and bring remaining questions to the clinician."
        )

    payload = {
        "case_id": case.get("case_id"),
        "child_name": case.get("child_name"),
        "age_label": case.get("age_label"),
        "age_months": case.get("age_months"),
        "diagnosis": case.get("diagnosis"),
        "concerns_bullets": concerns_bullets,
        "daily_time_min": state.get("child", {}).get("daily_time_min", ""),
        "parent_qa_full": parent_qa_full,
        "parent_qa_pdf": parent_qa_pdf,
        "domain_rows": domain_rows,
        "focus_areas": focus_areas,
        "activities": activities,
        "summary_text": summary_text,
    }
    return payload

def print_case_screen_summary(payload: dict):
    print("\n" + "=" * 110)
    print(f"CASE {payload['case_id']} | {payload['child_name']} | {payload['age_label']} | {payload['diagnosis']}")
    print("=" * 110)

    print("\n1. CHILD PROFILE")
    print(f"- Name: {payload['child_name']}")
    print(f"- Age: {payload['age_label']} ({payload['age_months']} months)")
    print(f"- Diagnosis: {payload['diagnosis']}")
    print(f"- Daily time available: {payload['daily_time_min']} min/day")
    print("- Key concerns:")
    for c in payload["concerns_bullets"]:
        print(f"  • {c}")

    print("\n2. PARENT INPUT (full transcript)")
    for line in payload["parent_qa_full"]:
        print(f"- {line}")

    print("\n3. GENEX OUTPUT")
    domain_df = pd.DataFrame(payload["domain_rows"])
    if not domain_df.empty:
        display(domain_df[["category", "estimated_dev_age_months", "gap_months", "support_tier", "severity"]])

    print("\nFocus areas:")
    for x in payload["focus_areas"]:
        print(f"  • {x}")

    print("\nDaily activities:")
    for i, a in enumerate(payload["activities"], start=1):
        print(f"{i}. {a['title']} | {a['category']} | {a['duration_min']} min")
        print(f"   Goal: {a['goal']}")
        print(f"   Description: {a['description']}")

    print("\n4. SUMMARY")
    print(payload["summary_text"])

    print("\n5. ADVISOR REVIEW SECTION")
    print("Rate 1–5:")
    print("- Clinical appropriateness")
    print("- Safety")
    print("- Practicality for parents")
    print("- Clarity")
    print("- Overall usefulness")
    print("Short feedback:")
    print("- What would you change?")
    print("- What is missing?")
    print("- Any concerns?")

In [36]:
# ------------------------------------------------------------
# PDF rendering + rating sheet
# ------------------------------------------------------------
def wrap_text_to_width(text, font_name, font_size, max_width):
    words = str(text).split()
    if not words:
        return [""]

    lines = []
    current = words[0]
    for word in words[1:]:
        trial = current + " " + word
        if stringWidth(trial, font_name, font_size) <= max_width:
            current = trial
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines

def draw_wrapped_text(c, text, x, y, max_width, font_name="Helvetica", font_size=8.5, line_height=10, max_lines=None):
    lines = wrap_text_to_width(text, font_name, font_size, max_width)
    original_lines = lines[:]
    if max_lines is not None:
        lines = lines[:max_lines]
        if len(original_lines) > max_lines and lines:
            lines[-1] = lines[-1][:max(0, len(lines[-1]) - 3)] + "..."
    c.setFont(font_name, font_size)
    for line in lines:
        c.drawString(x, y, line)
        y -= line_height
    return y

def draw_bullets(c, items, x, y, max_width, font_name="Helvetica", font_size=8.5, line_height=10, max_items=None):
    items = list(items)
    if max_items is not None:
        items = items[:max_items]

    for item in items:
        bullet_lines = wrap_text_to_width(str(item), font_name, font_size, max_width - 12)
        if bullet_lines:
            c.drawString(x, y, u"\u2022")
            c.drawString(x + 10, y, bullet_lines[0])
            y -= line_height
            for extra in bullet_lines[1:]:
                c.drawString(x + 10, y, extra)
                y -= line_height
        else:
            y -= line_height
    return y

def draw_box(c, x, y_top, w, h, title):
    c.roundRect(x, y_top - h, w, h, 8, stroke=1, fill=0)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(x + 8, y_top - 14, title)

def render_case_page(c, payload: dict):
    page_w, page_h = landscape(LETTER)
    margin = 0.35 * inch

    left_x = margin
    mid_x = page_w / 2 + 0.10 * inch
    col_w = (page_w / 2) - (1.5 * margin)

    c.setFont("Helvetica-Bold", 15)
    c.drawString(margin, page_h - 0.45 * inch, f"{payload['case_id']} — {payload['child_name']} ({payload['age_label']})")
    c.setFont("Helvetica", 10)
    c.drawString(margin, page_h - 0.68 * inch, f"Diagnosis: {payload['diagnosis']}")

    top_y = page_h - 0.90 * inch
    profile_h = 1.60 * inch
    input_h = 2.55 * inch
    output_h = 2.20 * inch
    activity_h = 2.10 * inch
    summary_h = 0.85 * inch
    rating_h = 1.20 * inch

    draw_box(c, left_x, top_y, col_w, profile_h, "1. Child Profile")
    draw_box(c, left_x, top_y - profile_h - 0.10 * inch, col_w, input_h, "2. Parent Input (questions + answers)")
    draw_box(c, mid_x, top_y, col_w, output_h, "3. Genex Output")
    draw_box(c, mid_x, top_y - output_h - 0.10 * inch, col_w, activity_h, "4. Daily Activities")

    bottom_top = page_h - 6.65 * inch
    full_w = page_w - 2 * margin
    draw_box(c, margin, bottom_top, full_w, summary_h, "5. Summary")
    draw_box(c, margin, bottom_top - summary_h - 0.10 * inch, full_w, rating_h, "6. Advisor Review")

    y = top_y - 28
    c.setFont("Helvetica", 9)
    c.drawString(left_x + 10, y, f"Name: {payload['child_name']}")
    y -= 12
    c.drawString(left_x + 10, y, f"Age: {payload['age_label']} ({payload['age_months']} months)")
    y -= 12
    c.drawString(left_x + 10, y, f"Diagnosis: {payload['diagnosis']}")
    y -= 12
    c.drawString(left_x + 10, y, f"Daily time: {payload['daily_time_min']} min/day")
    y -= 16
    c.setFont("Helvetica-Bold", 9)
    c.drawString(left_x + 10, y, "Key concerns:")
    y -= 11
    y = draw_bullets(c, payload["concerns_bullets"], left_x + 12, y, col_w - 20, max_items=4)

    y = top_y - profile_h - 0.10 * inch - 28
    y = draw_bullets(c, payload["parent_qa_pdf"], left_x + 12, y, col_w - 20, font_size=7.8, line_height=9, max_items=12)
    c.setFont("Helvetica-Oblique", 7.5)
    c.drawString(left_x + 10, top_y - profile_h - input_h - 0.10 * inch + 10, "Full transcript is preserved in JSON output.")

    y = top_y - 28
    domain_rows = payload["domain_rows"][:4]
    c.setFont("Helvetica-Bold", 8.5)
    c.drawString(mid_x + 10, y, "Domain")
    c.drawString(mid_x + 150, y, "Dev age")
    c.drawString(mid_x + 220, y, "Gap")
    c.drawString(mid_x + 270, y, "Tier")
    y -= 11
    c.setFont("Helvetica", 8.2)
    for row in domain_rows:
        c.drawString(mid_x + 10, y, str(row["category"])[:24])
        c.drawString(mid_x + 150, y, str(row["estimated_dev_age_months"]))
        c.drawString(mid_x + 220, y, str(row["gap_months"]))
        c.drawString(mid_x + 270, y, str(row["support_tier"])[:18])
        y -= 10

    y -= 8
    c.setFont("Helvetica-Bold", 9)
    c.drawString(mid_x + 10, y, "Focus areas:")
    y -= 11
    y = draw_bullets(c, payload["focus_areas"], mid_x + 12, y, col_w - 20, max_items=3)

    y = top_y - output_h - 0.10 * inch - 28
    for i, a in enumerate(payload["activities"][:5], start=1):
        line = f"{i}. {a['title']} ({a['duration_min']} min) — {a['goal']}"
        y = draw_wrapped_text(c, line, mid_x + 10, y, col_w - 20, font_name="Helvetica-Bold", font_size=8.2, line_height=9, max_lines=2)
        y = draw_wrapped_text(c, a["description"], mid_x + 16, y, col_w - 26, font_name="Helvetica", font_size=7.8, line_height=8.5, max_lines=2)
        y -= 4

    y = bottom_top - 28
    y = draw_wrapped_text(c, payload["summary_text"], margin + 10, y, full_w - 20, font_name="Helvetica", font_size=8.5, line_height=10, max_lines=4)

    y = bottom_top - summary_h - 0.10 * inch - 28
    rating_lines = [
        "Rate 1–5: Clinical appropriateness | Safety | Practicality for parents | Clarity | Overall usefulness",
        "Short feedback: What would you change? | What is missing? | Any concerns?"
    ]
    for line in rating_lines:
        y = draw_wrapped_text(c, line, margin + 10, y, full_w - 20, font_name="Helvetica", font_size=9, line_height=11, max_lines=2)

    c.showPage()

def build_advisor_rating_sheet(df_cases: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, row in df_cases.iterrows():
        rows.append({
            "case_id": row["case_id"],
            "child_name": row["child_name"],
            "age_months": row["age_months"],
            "diagnosis": row["diagnosis"],
            "clinical_appropriateness_1to5": "",
            "safety_1to5": "",
            "practicality_for_parents_1to5": "",
            "clarity_1to5": "",
            "overall_usefulness_1to5": "",
            "what_would_you_change": "",
            "what_is_missing": "",
            "any_concerns": "",
        })
    return pd.DataFrame(rows)

In [37]:
# ------------------------------------------------------------
# Generic advisor-report export runner
# ------------------------------------------------------------
def run_cases_and_export(
    df_cases: pd.DataFrame,
    mode: str = "live",   # "live" or "gemini"
    output_dir: str = "outputs/advisor_case_pack_v4",
    default_daily_time_min: int = 10,
    pause_between_cases: bool = True,
    gemini_model: str = "gemini-2.5-flash",
):
    """Run all cases and export the advisor packet files."""
    mode = str(mode).strip().lower()
    if mode not in {"live", "gemini"}:
        raise ValueError("mode must be 'live' or 'gemini'")

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    run_stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    combined_pdf_path = out_dir / f"genex_case_report_{mode}_{run_stamp}.pdf"
    rating_csv_path = out_dir / f"advisor_rating_sheet_{mode}_{run_stamp}.csv"
    rating_xlsx_path = out_dir / f"advisor_rating_sheet_{mode}_{run_stamp}.xlsx"
    json_path = out_dir / f"case_payloads_{mode}_{run_stamp}.json"

    c = canvas.Canvas(str(combined_pdf_path), pagesize=landscape(LETTER))
    all_payloads = []
    rating_df = build_advisor_rating_sheet(df_cases)

    for i, (_, row) in enumerate(df_cases.iterrows(), start=1):
        case = row.to_dict()

        if mode == "live":
            state, summary_df = run_case_live_from_prefilled_case(
                case=case,
                default_daily_time_min=default_daily_time_min,
                min_yes_confirm=2,
                yes_ratio_confirm=0.60,
            )
        else:
            state, summary_df = run_case_gemini_from_prefilled_case(
                case=case,
                daily_time_min=default_daily_time_min,
                min_yes_confirm=2,
                yes_ratio_confirm=0.60,
                gemini_model=gemini_model,
            )

        payload = build_case_payload(case, state, summary_df)
        all_payloads.append(payload)

        print_case_screen_summary(payload)
        render_case_page(c, payload)

        per_case_summary_path = out_dir / f"{case['case_id']}_{case['child_name']}_summary.csv"
        summary_df.to_csv(per_case_summary_path, index=False)

        if pause_between_cases and i < len(df_cases):
            input("\nPress Enter to continue to the next case...")

    c.save()

    rating_df.to_csv(rating_csv_path, index=False)
    rating_df.to_excel(rating_xlsx_path, index=False)

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(all_payloads, f, indent=2)

    print("\n" + "=" * 110)
    print("DONE")
    print("=" * 110)
    print("Mode:", mode)
    print("Combined PDF:", combined_pdf_path)
    print("Rating CSV :", rating_csv_path)
    print("Rating XLSX:", rating_xlsx_path)
    print("Payload JSON:", json_path)

    return all_payloads, rating_df, combined_pdf_path

## Sanity check (optional)

Run this before the example cells if you want a quick check that the core functions are loaded into the current kernel.

In [38]:
print("run_all_categories_live" in globals())
print("run_all_categories_gemini_parent" in globals())
print("run_downstream_planning" in globals())
print("generate_category_activity_bank" in globals())
print("allocate_weekly_slots" in globals())
print("build_weekly_schedule" in globals())
print("summarizer_agent" in globals())

True
True
True
True
True
True
True

## Example run cells

Use **only one** of the cells below at a time.

In [19]:
# Example 1 — one fully live run
# state, summary_df = run_all_categories_live()
# display(summary_df)

In [20]:
# # Example 2 — one synthetic case using Gemini as the parent
# case = df_cases.iloc[0].to_dict()
# state, summary_df = run_all_categories_gemini_parent(
#     case,
#     daily_time_min=10,
#     gemini_model="gemini-2.5-flash",
# )
# display(summary_df)

====================================================================================================
CHILD REFERENCE CHECK
====================================================================================================
Name: Noah
Chronological age: 10 months
Diagnosis / condition: Down syndrome
Parent concern: Not sitting independently yet, Hypotonia, slow feeding, socially engaged
Daily time available: 10 minutes

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 4 month starting delay | Hypotonia may impact the child's ability to sit independently.
Social / Emotional: 4 month starting delay | Social engagement is present but may be impacted by hypotonia and developmental delays associated with Down syndrome.
Language / Communication: 6 month starting delay | Down syndrome often impacts language development, leading to a delay.
Cognitive / Adaptive: 6 month starting delay | Cognitive development may be impacted by Down syndrome and associated hypotonia.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 4 months ---
Q: Can Noah bring hands to mouth right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He tries to get his hands to his mouth, especially when he's exploring or just focusing on something.
Q: Can Noah holds a toy when you put it in his hand right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll grasp it, but with his low muscle tone, he doesn't always hold onto it for very long.
Q: Can Noah holds head steady without support when you are holding him right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's got hypotonia, so it's not always perfectly steady and can be a bit wobbly.

--- Asking Movement / Physical milestones around 6 months ---
Q: Can Noah leans on hands to support herself when sitting right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He tries to put his hands down to catch himself when he's sitting, but he's still pretty wobbly.
Q: Can Noah pushes up with straight arms when on tummy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He tries, and sometimes gets them straight for a bit, but it's not always.
Q: Can Noah rolls from tummy to back right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can get there if he really tries, but it's not every time.

--- Asking Movement / Physical milestones around 9 months ---
Q: Can Noah gets to sitting position by herself right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He's not sitting independently yet, so he definitely can't get there by himself.
Q: Can Noah moves things from one hand to her other hand right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: We've seen him do it with some toys, but it's not consistent yet.
Q: Can Noah sits without support right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He's not quite able to do that on his own yet without support.

Question / answer transcript:
- [4m] bring hands to mouth -> sometimes | status: ok | reason: He tries to get his hands to his mouth, especially when he's exploring or just focusing on something.
- [4m] holds a toy when you put it in his hand -> sometimes | status: ok | reason: He'll grasp it, but with his low muscle tone, he doesn't always hold onto it for very long.
- [4m] holds head steady without support when you are holding him -> sometimes | status: ok | reason: He's got hypotonia, so it's not always perfectly steady and can be a bit wobbly.
- [6m] leans on hands to support herself when sitting -> sometimes | status: ok | reason: He tries to put his hands down to catch himself when he's sitting, but he's still pretty wobbly.
- [6m] pushes up with straight arms when on tummy -> sometimes | status: ok | reason: He tries, and sometimes gets them straight for a bit, but it's not always.
- [6m] rolls from tummy to back -> sometimes | status: ok | reason: He can get there if he really tries, but it's not every time.
- [9m] gets to sitting position by herself -> no | status: ok | reason: He's not sitting independently yet, so he definitely can't get there by himself.
- [9m] moves things from one hand to her other hand -> sometimes | status: ok | reason: We've seen him do it with some toys, but it's not consistent yet.
- [9m] sits without support -> no | status: ok | reason: He's not quite able to do that on his own yet without support.

Band summary:
  4m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  6m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  9m | total=3 | yes=0 | partial=1 | no=2 | yes_ratio=0.0

Estimated developmental age for Movement / Physical: 4 months (chronological age 10 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 4 months ---
Q: Can Noah chuckles when you try to make him laugh but not yet a full laugh right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very socially engaged and definitely responds when we play with him.
Q: Can Noah looks at you moves or makes sounds to get or keep you attention right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very socially engaged and definitely knows how to get our attention.
Q: Can Noah smiles on his own to get your attention right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he's a very social little guy and loves to smile to get us to look at him!

--- Asking Social / Emotional milestones around 6 months ---
Q: Can Noah knows familiar people right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely knows us and his grandma, he gets excited when they come around.
Q: Can Noah laughs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He chuckles when we play with him, but he doesn't have a full laugh yet.
Q: Can Noah likes to look at self in a mirror right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He smiles and bats at the 'other baby' in the mirror.

--- Asking Social / Emotional milestones around 9 months ---
Q: Can Noah is shy or clingy or fearful around strangers right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's generally very social, but sometimes he needs a minute to warm up to new people.
Q: Can Noah looks when you call her name right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very socially engaged and usually turns his head when we call him.
Q: Can Noah reacts when you leave right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely notices and will often fuss or watch for me when I leave the room.

Question / answer transcript:
- [4m] chuckles when you try to make him laugh but not yet a full laugh -> yes | status: ok | reason: He's very socially engaged and definitely responds when we play with him.
- [4m] looks at you moves or makes sounds to get or keep you attention -> yes | status: ok | reason: He's very socially engaged and definitely knows how to get our attention.
- [4m] smiles on his own to get your attention -> yes | status: ok | reason: Oh yes, he's a very social little guy and loves to smile to get us to look at him!
- [6m] knows familiar people -> yes | status: ok | reason: He definitely knows us and his grandma, he gets excited when they come around.
- [6m] laughs -> no | status: ok | reason: He chuckles when we play with him, but he doesn't have a full laugh yet.
- [6m] likes to look at self in a mirror -> yes | status: ok | reason: He smiles and bats at the 'other baby' in the mirror.
- [9m] is shy or clingy or fearful around strangers -> sometimes | status: ok | reason: He's generally very social, but sometimes he needs a minute to warm up to new people.
- [9m] looks when you call her name -> yes | status: ok | reason: He's very socially engaged and usually turns his head when we call him.
- [9m] reacts when you leave -> yes | status: ok | reason: He definitely notices and will often fuss or watch for me when I leave the room.

Band summary:
  4m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67
  9m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Social / Emotional: 9 months (chronological age 10 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 2 months ---
Q: Can Noah makes sounds other than crying right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely makes lots of happy coos and babbles, especially when he's playing with us.
Q: Can Noah reacts to loud sounds right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yeah, he definitely jumps or looks over if there's a loud noise nearby.

--- Asking Language / Communication milestones around 4 months ---
Q: Can Noah makes cooing sounds like ooooo or aahhh right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He makes those happy sounds, especially when we talk to him.
Q: Can Noah makes sounds back when you talk to him right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and already making sounds, so he often babbles back when we talk to him.
Q: Can Noah turns head towards the sound of your voice right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very socially engaged and definitely looks for me when I talk.

--- Asking Language / Communication milestones around 6 months ---
Q: Can Noah blows raspberries or sticks tongue out and blows right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's social and tries to copy us, but it's not always easy for him to do it perfectly.
Q: Can Noah makes squealing noises right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Yes, he's a very vocal little guy, especially when he's happy!
Q: Can Noah takes turns making sounds with you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and loves to babble back and forth with us.

Question / answer transcript:
- [2m] makes sounds other than crying -> yes | status: ok | reason: He definitely makes lots of happy coos and babbles, especially when he's playing with us.
- [2m] reacts to loud sounds -> yes | status: ok | reason: Oh yeah, he definitely jumps or looks over if there's a loud noise nearby.
- [4m] makes cooing sounds like ooooo or aahhh -> yes | status: ok | reason: He makes those happy sounds, especially when we talk to him.
- [4m] makes sounds back when you talk to him -> yes | status: ok | reason: He's very social and already making sounds, so he often babbles back when we talk to him.
- [4m] turns head towards the sound of your voice -> yes | status: ok | reason: He's very socially engaged and definitely looks for me when I talk.
- [6m] blows raspberries or sticks tongue out and blows -> sometimes | status: ok | reason: He's social and tries to copy us, but it's not always easy for him to do it perfectly.
- [6m] makes squealing noises -> yes | status: ok | reason: Yes, he's a very vocal little guy, especially when he's happy!
- [6m] takes turns making sounds with you -> yes | status: ok | reason: He's very social and loves to babble back and forth with us.

Band summary:
  2m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  4m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Language / Communication: 6 months (chronological age 10 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 2 months ---
Q: Can Noah looks at a toy for sevedral seconds right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and loves looking at things.
Q: Can Noah watches you as you move right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and follows us with his eyes.

--- Asking Cognitive / Adaptive milestones around 4 months ---
Q: Can Noah if hungry open mouth when she sees breast or bottle right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely knows when it's feeding time and opens his mouth to let us know he's ready!
Q: Can Noah looks at her hands with interest right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yeah, he loves watching his hands, especially when he moves them around.

--- Asking Cognitive / Adaptive milestones around 6 months ---
Q: Can Noah closes lips to show she doesn't want more food right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's pretty good at letting us know when he's had enough, he'll just keep his mouth shut.
Q: Can Noah puts things in her mouth to explore them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll try to put things in his mouth to explore, especially new toys, but he doesn't always keep them there for long.
Q: Can Noah reaches to grab a toy she wants right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: When she really wants a toy, she'll definitely reach out for it.

Question / answer transcript:
- [2m] looks at a toy for sevedral seconds -> yes | status: ok | reason: He's very social and loves looking at things.
- [2m] watches you as you move -> yes | status: ok | reason: He's very social and follows us with his eyes.
- [4m] if hungry open mouth when she sees breast or bottle -> yes | status: ok | reason: He definitely knows when it's feeding time and opens his mouth to let us know he's ready!
- [4m] looks at her hands with interest -> yes | status: ok | reason: Oh yeah, he loves watching his hands, especially when he moves them around.
- [6m] closes lips to show she doesn't want more food -> yes | status: ok | reason: He's pretty good at letting us know when he's had enough, he'll just keep his mouth shut.
- [6m] puts things in her mouth to explore them -> sometimes | status: ok | reason: He'll try to put things in his mouth to explore, especially new toys, but he doesn't always keep them there for long.
- [6m] reaches to grab a toy she wants -> yes | status: ok | reason: When she really wants a toy, she'll definitely reach out for it.

Band summary:
  2m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  4m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Cognitive / Adaptive: 6 months (chronological age 10 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
Summary: Weekly schedule built from category activity banks and true daily minute limits.
Daily time budget: 10
Target minutes by category: {'movement_and_physical': 28, 'language_and_communication': 11, 'cognitive': 11}
Assigned minutes by category: {'movement_and_physical': 27, 'language_and_communication': 13, 'cognitive': 5}

----------------------------------------------------------------------------------------------------
DAY_1 — total 8 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Tummy Time with Toys (5 min)
  Goal: needs_special_support
  Instructions: Place Noah on his tummy on a soft surface. Position colorful toys just out of reach to encourage him to push up onto his elbows or forearms.
  Materials: Soft mat, colorful toys
- [Language / Communication] Gesture for 'Up' (3 min)
  Goal: monitor_and_enrich
  Instructions: When Noah lifts his arms to be picked up, respond enthusiastically and say 'up!' to reinforce the gesture. Encourage him to use this gesture more.
  Materials: None needed.

----------------------------------------------------------------------------------------------------
DAY_2 — total 10 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Reaching for Toys (5 min)
  Goal: needs_special_support
  Instructions: Place toys at different distances while Noah is lying on his back. Encourage him to reach for the toys using both hands.
  Materials: Various toys
- [Language / Communication] Sound Imitation Game (5 min)
  Goal: monitor_and_enrich
  Instructions: Make different sounds like 'ma-ma' or 'ba-ba' and encourage Noah to imitate you. Use a fun tone and facial expressions to engage him.
  Materials: None needed, just your voice.

----------------------------------------------------------------------------------------------------
DAY_3 — total 10 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Hand-to-Mouth Practice (5 min)
  Goal: needs_special_support
  Instructions: During playtime, help Noah bring his hands to his mouth with safe toys or soft snacks, encouraging him to explore.
  Materials: Safe toys or soft snacks
- [Language / Communication] Squealing Sounds Play (5 min)
  Goal: monitor_and_enrich
  Instructions: Make high-pitched squealing sounds and encourage Noah to join in. Use toys that make sounds to keep him engaged.
  Materials: Sound-making toys (optional).

----------------------------------------------------------------------------------------------------
DAY_4 — total 10 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Toy Grasping (5 min)
  Goal: needs_special_support

,child_name,chronological_age_months,diagnosis,concern,daily_time_min,category,estimated_delay_months,delay_reason,estimated_dev_age_months,milestone_gap_months,support_tier,needs_special_support,weekly_target_minutes_for_category,activity_bank_status,activity_bank_summary
0,Noah,10,Down syndrome,"Not sitting independently yet, Hypotonia, slow...",10,Movement / Physical,4,Hypotonia may impact the child's ability to si...,4,6,needs_special_support,True,28,success,This activity bank provides practical home act...
1,Noah,10,Down syndrome,"Not sitting independently yet, Hypotonia, slow...",10,Social / Emotional,4,Social engagement is present but may be impact...,9,1,no_special_support,False,0,no_special_support,We do not think Noah has a meaningful delay in...
2,Noah,10,Down syndrome,"Not sitting independently yet, Hypotonia, slow...",10,Language / Communication,6,Down syndrome often impacts language developme...,6,4,monitor_and_enrich,True,11,success,This activity bank provides practical language...
3,Noah,10,Down syndrome,"Not sitting independently yet, Hypotonia, slow...",10,Cognitive / Adaptive,6,Cognitive development may be impacted by Down ...,6,4,monitor_and_enrich,True,11,success,"This activity bank provides practical, engagin..."

In [ ]:
# Example 3A — export advisor packet in live mode
# all_payloads, advisor_rating_df, pdf_path = run_cases_and_export(
#     df_cases=df_cases,
#     mode="live",
#     output_dir="outputs/advisor_case_pack_v4",
#     default_daily_time_min=10,
#     pause_between_cases=True,
# )
# display(advisor_rating_df.head())
# pdf_path

In [ ]:
# Example 3B — export advisor packet in Gemini synthetic-parent mode
# all_payloads, advisor_rating_df, pdf_path = run_cases_and_export(
#     df_cases=df_cases,
#     mode="gemini",
#     output_dir="outputs/advisor_case_pack_v4",
#     default_daily_time_min=10,
#     pause_between_cases=False,
#     gemini_model="gemini-2.5-flash",
# )
# display(advisor_rating_df.head())
# pdf_path

In [39]:
import time
from pathlib import Path
from datetime import datetime
import pandas as pd
from reportlab.lib.pagesizes import landscape, LETTER
from reportlab.pdfgen import canvas

def run_cases_and_export_in_batches(
    df_cases: pd.DataFrame,
    batch_size: int = 5,
    gap_between_batches_sec: int = 120,
    mode: str = "gemini",
    output_dir: str = "outputs/advisor_case_pack_v5",
    default_daily_time_min: int = 10,
    pause_between_cases: bool = False,
    gemini_model: str = "gemini-2.5-flash",
):
    mode = str(mode).strip().lower()
    if mode not in {"live", "gemini"}:
        raise ValueError("mode must be 'live' or 'gemini'")

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    run_stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    combined_pdf_path = out_dir / f"genex_case_report_{mode}_{run_stamp}.pdf"
    rating_csv_path = out_dir / f"advisor_rating_sheet_{mode}_{run_stamp}.csv"
    rating_xlsx_path = out_dir / f"advisor_rating_sheet_{mode}_{run_stamp}.xlsx"
    json_path = out_dir / f"case_payloads_{mode}_{run_stamp}.json"

    c = canvas.Canvas(str(combined_pdf_path), pagesize=landscape(LETTER))

    all_payloads = []
    rating_df = build_advisor_rating_sheet(df_cases)

    total_cases = len(df_cases)

    for start_idx in range(0, total_cases, batch_size):
        end_idx = min(start_idx + batch_size, total_cases)
        batch_df = df_cases.iloc[start_idx:end_idx]

        print("\n" + "=" * 110)
        print(f"RUNNING BATCH {start_idx // batch_size + 1} | cases {start_idx + 1} to {end_idx} of {total_cases}")
        print("=" * 110)

        for _, row in batch_df.iterrows():
            case = row.to_dict()

            if mode == "live":
                state, summary_df = run_case_live_from_prefilled_case(
                    case=case,
                    default_daily_time_min=default_daily_time_min,
                    min_yes_confirm=2,
                    yes_ratio_confirm=0.60,
                )
            else:
                state, summary_df = run_case_gemini_from_prefilled_case(
                    case=case,
                    daily_time_min=default_daily_time_min,
                    min_yes_confirm=2,
                    yes_ratio_confirm=0.60,
                    gemini_model=gemini_model,
                )

            payload = build_case_payload(case, state, summary_df)
            all_payloads.append(payload)

            print_case_screen_summary(payload)
            render_case_page(c, payload)

            per_case_summary_path = out_dir / f"{case['case_id']}_{case['child_name']}_summary.csv"
            summary_df.to_csv(per_case_summary_path, index=False)

            if pause_between_cases:
                input("\nPress Enter to continue to the next case...")

        # sleep only between batches, not after the last one
        if end_idx < total_cases:
            print("\n" + "-" * 110)
            print(f"Batch complete. Waiting {gap_between_batches_sec} seconds before next batch...")
            print("-" * 110)
            time.sleep(gap_between_batches_sec)

    c.save()

    rating_df.to_csv(rating_csv_path, index=False)
    rating_df.to_excel(rating_xlsx_path, index=False)

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(all_payloads, f, indent=2)

    print("\n" + "=" * 110)
    print("DONE")
    print("=" * 110)
    print("Mode:", mode)
    print("Combined PDF:", combined_pdf_path)
    print("Rating CSV :", rating_csv_path)
    print("Rating XLSX:", rating_xlsx_path)
    print("Payload JSON:", json_path)

    return all_payloads, rating_df, combined_pdf_path

In [40]:
# Example 3B — export advisor packet in Gemini synthetic-parent mode, in batches of 5 with 2 min gap
all_payloads, advisor_rating_df, pdf_path = run_cases_and_export_in_batches(
    df_cases=df_cases,
    batch_size=5,
    gap_between_batches_sec=120,   # 2 minutes
    mode="gemini",
    output_dir="outputs/advisor_case_pack_v5",
    default_daily_time_min=10,
    pause_between_cases=False,
    gemini_model="gemini-2.5-flash",
)

display(advisor_rating_df.head())
pdf_path

==============================================================================================================
RUNNING BATCH 1 | cases 1 to 5 of 14
==============================================================================================================

==============================================================================================================
STARTING C01 | Noah | 10 months | Down syndrome
==============================================================================================================
Concerns: Not sitting independently yet, Hypotonia, slow feeding, socially engaged
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 4 month starting delay | Hypotonia and Down syndrome may contribute to delays in independent sitting.
Social / Emotional: 4 month starting delay | Social engagement is present, but developmental delays associated with Down syndrome may impact social skills.
Language / Communication: 6 month starting delay | Down syndrome and hypotonia may impact language development, leading to a delay.
Cognitive / Adaptive: 6 month starting delay | Cognitive development may be impacted by Down syndrome and associated hypotonia.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 4 months ---
Q: Can Noah bring hands to mouth right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He manages to get his hands up there, especially when exploring toys, but it's not always consistent.
Q: Can Noah holds a toy when you put it in his hand right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He can grasp it and hold it, though his grip isn't always super strong.
Q: Can Noah holds head steady without support when you are holding him right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can hold it for a little while, but it can still get a bit wobbly, especially if he's tired.

--- Asking Movement / Physical milestones around 6 months ---
Q: Can Noah leans on hands to support herself when sitting right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He tries to lean on his hands to balance, but he's not always steady when he does.
Q: Can Noah pushes up with straight arms when on tummy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He tries, but his arms sometimes bend or he can't hold it for long because of his hypotonia.
Q: Can Noah rolls from tummy to back right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it sometimes, especially if he gets some momentum, but it's not consistent yet.

--- Asking Movement / Physical milestones around 9 months ---
Q: Can Noah gets to sitting position by herself right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He's not sitting independently yet, which is one of our main concerns.
Q: Can Noah moves things from one hand to her other hand right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's starting to do it when he's really focused on playing with something interesting.
Q: Can Noah sits without support right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He's not sitting independently yet, that's one of our main concerns.

Question / answer transcript:
- [4m] bring hands to mouth -> sometimes | status: ok | reason: He manages to get his hands up there, especially when exploring toys, but it's not always consistent.
- [4m] holds a toy when you put it in his hand -> yes | status: ok | reason: He can grasp it and hold it, though his grip isn't always super strong.
- [4m] holds head steady without support when you are holding him -> sometimes | status: ok | reason: He can hold it for a little while, but it can still get a bit wobbly, especially if he's tired.
- [6m] leans on hands to support herself when sitting -> sometimes | status: ok | reason: He tries to lean on his hands to balance, but he's not always steady when he does.
- [6m] pushes up with straight arms when on tummy -> sometimes | status: ok | reason: He tries, but his arms sometimes bend or he can't hold it for long because of his hypotonia.
- [6m] rolls from tummy to back -> sometimes | status: ok | reason: He can do it sometimes, especially if he gets some momentum, but it's not consistent yet.
- [9m] gets to sitting position by herself -> no | status: ok | reason: He's not sitting independently yet, which is one of our main concerns.
- [9m] moves things from one hand to her other hand -> sometimes | status: ok | reason: He's starting to do it when he's really focused on playing with something interesting.
- [9m] sits without support -> no | status: ok | reason: He's not sitting independently yet, that's one of our main concerns.

Band summary:
  4m | total=3 | yes=1 | partial=2 | no=0 | yes_ratio=0.33
  6m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  9m | total=3 | yes=0 | partial=1 | no=2 | yes_ratio=0.0

Estimated developmental age for Movement / Physical: 4 months (chronological age 10 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 4 months ---
Q: Can Noah chuckles when you try to make him laugh but not yet a full laugh right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very socially engaged and definitely chuckles when we try to make him laugh.
Q: Can Noah looks at you moves or makes sounds to get or keep you attention right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and loves to interact with us.
Q: Can Noah smiles on his own to get your attention right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's a very social little guy, always trying to get our attention with a smile.

--- Asking Social / Emotional milestones around 6 months ---
Q: Can Noah knows familiar people right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely recognizes us and his grandparents, he gets so excited when they come over.
Q: Can Noah laughs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He chuckles when we play, but it's not a full laugh yet.
Q: Can Noah likes to look at self in a mirror right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves to look at himself in the mirror and smiles at his reflection.

--- Asking Social / Emotional milestones around 9 months ---
Q: Can Noah is shy or clingy or fearful around strangers right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's usually very social, but sometimes if someone new comes up too fast or is really loud, he might get a little shy.
Q: Can Noah looks when you call her name right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He usually turns his head when we call his name, especially if he's not super focused on something else.
Q: Can Noah reacts when you leave right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh, definitely. If I try to leave the room, he'll usually start to fuss or reach for me.

Question / answer transcript:
- [4m] chuckles when you try to make him laugh but not yet a full laugh -> yes | status: ok | reason: He's very socially engaged and definitely chuckles when we try to make him laugh.
- [4m] looks at you moves or makes sounds to get or keep you attention -> yes | status: ok | reason: He's very social and loves to interact with us.
- [4m] smiles on his own to get your attention -> yes | status: ok | reason: He's a very social little guy, always trying to get our attention with a smile.
- [6m] knows familiar people -> yes | status: ok | reason: He definitely recognizes us and his grandparents, he gets so excited when they come over.
- [6m] laughs -> no | status: ok | reason: He chuckles when we play, but it's not a full laugh yet.
- [6m] likes to look at self in a mirror -> yes | status: ok | reason: He loves to look at himself in the mirror and smiles at his reflection.
- [9m] is shy or clingy or fearful around strangers -> sometimes | status: ok | reason: He's usually very social, but sometimes if someone new comes up too fast or is really loud, he might get a little shy.
- [9m] looks when you call her name -> yes | status: ok | reason: He usually turns his head when we call his name, especially if he's not super focused on something else.
- [9m] reacts when you leave -> yes | status: ok | reason: Oh, definitely. If I try to leave the room, he'll usually start to fuss or reach for me.

Band summary:
  4m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67
  9m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Social / Emotional: 9 months (chronological age 10 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 2 months ---
Q: Can Noah makes sounds other than crying right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He babbles and coos a lot, especially when we talk to him or he's excited.
Q: Can Noah reacts to loud sounds right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely startles or turns his head when there's a sudden loud sound.

--- Asking Language / Communication milestones around 4 months ---
Q: Can Noah makes cooing sounds like ooooo or aahhh right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He often makes those sweet sounds when he's happy or looking at us.
Q: Can Noah makes sounds back when you talk to him right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and loves to 'talk' back when we chat with him, often cooing or babbling.
Q: Can Noah turns head towards the sound of your voice right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very socially engaged and usually looks our way when we speak.

--- Asking Language / Communication milestones around 6 months ---
Q: Can Noah blows raspberries or sticks tongue out and blows right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's very social and makes different sounds, but it's not something he does consistently yet.
Q: Can Noah makes squealing noises right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely lets us know when he's happy or excited with a good squeal!
Q: Can Noah takes turns making sounds with you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves to make sounds back and forth, we have little 'conversations'.

Question / answer transcript:
- [2m] makes sounds other than crying -> yes | status: ok | reason: He babbles and coos a lot, especially when we talk to him or he's excited.
- [2m] reacts to loud sounds -> yes | status: ok | reason: He definitely startles or turns his head when there's a sudden loud sound.
- [4m] makes cooing sounds like ooooo or aahhh -> yes | status: ok | reason: He often makes those sweet sounds when he's happy or looking at us.
- [4m] makes sounds back when you talk to him -> yes | status: ok | reason: He's very social and loves to 'talk' back when we chat with him, often cooing or babbling.
- [4m] turns head towards the sound of your voice -> yes | status: ok | reason: He's very socially engaged and usually looks our way when we speak.
- [6m] blows raspberries or sticks tongue out and blows -> sometimes | status: ok | reason: He's very social and makes different sounds, but it's not something he does consistently yet.
- [6m] makes squealing noises -> yes | status: ok | reason: He definitely lets us know when he's happy or excited with a good squeal!
- [6m] takes turns making sounds with you -> yes | status: ok | reason: He loves to make sounds back and forth, we have little 'conversations'.

Band summary:
  2m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  4m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Language / Communication: 6 months (chronological age 10 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 2 months ---
Q: Can Noah looks at a toy for sevedral seconds right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely tracks and looks at toys he's interested in, especially his rattles or colorful ones.
Q: Can Noah watches you as you move right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and tracks us with his eyes when we move around the room.

--- Asking Cognitive / Adaptive milestones around 4 months ---
Q: Can Noah if hungry open mouth when she sees breast or bottle right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He sees it coming and is ready to eat, even though it takes him a while to finish.
Q: Can Noah looks at her hands with interest right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he loves looking at his hands, bats at them sometimes too.

--- Asking Cognitive / Adaptive milestones around 6 months ---
Q: Can Noah closes lips to show she doesn't want more food right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll sometimes close his lips tightly to show he's done, but it's not always super clear.
Q: Can Noah puts things in her mouth to explore them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he puts everything in his mouth to see what it is!
Q: Can Noah reaches to grab a toy she wants right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he definitely reaches out for toys he wants to explore.

Question / answer transcript:
- [2m] looks at a toy for sevedral seconds -> yes | status: ok | reason: He definitely tracks and looks at toys he's interested in, especially his rattles or colorful ones.
- [2m] watches you as you move -> yes | status: ok | reason: He's very social and tracks us with his eyes when we move around the room.
- [4m] if hungry open mouth when she sees breast or bottle -> yes | status: ok | reason: He sees it coming and is ready to eat, even though it takes him a while to finish.
- [4m] looks at her hands with interest -> yes | status: ok | reason: Oh yes, he loves looking at his hands, bats at them sometimes too.
- [6m] closes lips to show she doesn't want more food -> sometimes | status: ok | reason: He'll sometimes close his lips tightly to show he's done, but it's not always super clear.
- [6m] puts things in her mouth to explore them -> yes | status: ok | reason: Oh yes, he puts everything in his mouth to see what it is!
- [6m] reaches to grab a toy she wants -> yes | status: ok | reason: Oh yes, he definitely reaches out for toys he wants to explore.

Band summary:
  2m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  4m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Cognitive / Adaptive: 6 months (chronological age 10 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
Summary: Weekly schedule built from category activity banks and true daily minute limits.
Daily time budget: 10
Target minutes by category: {'movement_and_physical': 28, 'language_and_communication': 11, 'cognitive': 11}
Assigned minutes by category: {'movement_and_physical': 27, 'language_and_communication': 15, 'cognitive': 5}

----------------------------------------------------------------------------------------------------
DAY_1 — total 10 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Tummy Time with Toys (5 min)
  Goal: needs_special_support
  Instructions: Place Noah on his tummy on a soft surface. Place colorful toys just out of reach to encourage him to push up onto his elbows or forearms to reach for them.
  Materials: Colorful toys, soft blanket
- [Language / Communication] Sound Imitation Game (5 min)
  Goal: monitor_and_enrich
  Instructions: Make different sounds like 'ma', 'ba', and 'ah' and encourage Noah to imitate you. Use exaggerated facial expressions to engage him.
  Materials: None needed.

----------------------------------------------------------------------------------------------------
DAY_2 — total 10 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Supported Sitting Practice (5 min)
  Goal: needs_special_support
  Instructions: Sit Noah on the floor with pillows around him for support. Encourage him to lean on his hands for balance while you place toys in front of him.
  Materials: Pillows, toys
- [Language / Communication] Gesture Play (5 min)
  Goal: monitor_and_enrich
  Instructions: Use simple gestures like waving or clapping and say the words associated with them. Encourage Noah to mimic the gestures while saying the words.
  Materials: None needed.

----------------------------------------------------------------------------------------------------
DAY_3 — total 10 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Hand-to-Mouth Play (5 min)
  Goal: needs_special_support
  Instructions: Give Noah soft toys or safe objects to hold and encourage him to bring them to his mouth. This helps strengthen his grasp and coordination.
  Materials: Soft toys or safe objects
- [Language / Communication] Squeaky Toy Sounds (5 min)
  Goal: monitor_and_enrich

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,4,6,needs_special_support,minimal / mild
1,Social / Emotional,9,1,no_special_support,minimal / mild
2,Language / Communication,6,4,monitor_and_enrich,minimal / mild
3,Cognitive / Adaptive,6,4,monitor_and_enrich,minimal / mild

Focus areas:
  • Movement / Physical
  • Language / Communication
  • Cognitive / Adaptive

Daily activities:
1. Tummy Time with Toys | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Place Noah on his tummy on a soft surface. Place colorful toys just out of reach to encourage him to push up onto his elbows or forearms to reach for them.
2. Sound Imitation Game | Language / Communication | 5 min
   Goal: monitor_and_enrich
   Description: Make different sounds like 'ma', 'ba', and 'ah' and encourage Noah to imitate you. Use exaggerated facial expressions to engage him.
3. Supported Sitting Practice | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Sit Noah on the floor with pillows around him for support. Encourage him to lean on his hands for balance while you place toys in front of him.
4. Gesture Play | Language / Communication | 5 min
   Goal: monitor_and_enrich
   Description: Use simple gestures like waving or clapping and say the words associated with them. Encourage Noah to mimic the gestures while saying the words.
5. Hand-to-Mouth Play | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Give Noah soft toys or safe objects to hold and encourage him to bring them to his mouth. This helps strengthen his grasp and coordination.

4. SUMMARY
This plan prioritizes Movement / Physical, Language / Communication, Cognitive / Adaptive for Noah. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C02 | Maya | 18 months | No formal diagnosis
==============================================================================================================
Concerns: No words yet, uses gestures, understands simple commands, good eye contact
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 3 month starting delay | Child shows good eye contact and understands commands, indicating some physical development but no words yet suggests a slight delay in movement skills.
Social / Emotional: 3 month starting delay | The child shows good eye contact and understands simple commands, indicating some social-emotional development, but the lack of words suggests a slight delay.
Language / Communication: 6 month starting delay | The child uses gestures and understands commands but has not yet developed spoken words.
Cognitive / Adaptive: 3 month starting delay | Child shows understanding of simple commands but lacks verbal communication.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 12 months ---
Q: Can Maya drinks from a cup without a lid as you hold it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can do it when we hold it for her, but it can get pretty messy.
Q: Can Maya picks things up between thumb and pointer finger like small bits of food right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She uses her fingers to pick up all her snacks off her tray.
Q: Can Maya pulls up to stand right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She pulls herself up on the couch and tables all the time.

--- Asking Movement / Physical milestones around 15 months ---
Q: Can Maya takes a few steps on her own right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's walking all over now.
Q: Can Maya uses fingers to feed herself some food right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can pick up small pieces of food herself to eat.

--- Asking Movement / Physical milestones around 18 months ---
Q: Can Maya climbs on and off a couch or chair without help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's always climbing on the sofa to get things.
Q: Can Maya drinks from a cup without a lid and may spill sometimes right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She's still figuring it out, sometimes she gets a sip, other times she just makes a mess.
Q: Can Maya feeds himself with his fingers right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very good at picking up her own food.

Question / answer transcript:
- [12m] drinks from a cup without a lid as you hold it -> sometimes | status: ok | reason: She can do it when we hold it for her, but it can get pretty messy.
- [12m] picks things up between thumb and pointer finger like small bits of food -> yes | status: ok | reason: She uses her fingers to pick up all her snacks off her tray.
- [12m] pulls up to stand -> yes | status: ok | reason: She pulls herself up on the couch and tables all the time.
- [15m] takes a few steps on her own -> yes | status: ok | reason: She's walking all over now.
- [15m] uses fingers to feed herself some food -> yes | status: ok | reason: She can pick up small pieces of food herself to eat.
- [18m] climbs on and off a couch or chair without help -> yes | status: ok | reason: She's always climbing on the sofa to get things.
- [18m] drinks from a cup without a lid and may spill sometimes -> sometimes | status: ok | reason: She's still figuring it out, sometimes she gets a sip, other times she just makes a mess.
- [18m] feeds himself with his fingers -> yes | status: ok | reason: She's very good at picking up her own food.

Band summary:
  12m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  15m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Movement / Physical: 18 months (chronological age 18 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 12 months ---
Q: Can Maya play games with you like pat a cake right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's good at copying the actions and loves to interact.

--- Asking Social / Emotional milestones around 15 months ---
Q: Can Maya claps when excited right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, she definitely claps her hands when she's really happy about something.
Q: Can Maya copies other children while playing like taking toys out of a container when another child does right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often watches other children and tries to do the same things they're doing with toys.
Q: Can Maya hugs stuffed doll or other toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often cuddles her teddy bear and other soft toys.

--- Asking Social / Emotional milestones around 18 months ---
Q: Can Maya helps you dress him by pushing the arm through the sleeve or lifting up the foot right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands when I ask her to lift her arm or foot to help get dressed.
Q: Can Maya looks at a few pages in a book with you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves looking at the pictures and pointing things out.
Q: Can Maya moves away from you but looks to make sure you are close by right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She'll go explore but always looks back to make sure I'm still there.

Question / answer transcript:
- [12m] play games with you like pat a cake -> yes | status: ok | reason: She's good at copying the actions and loves to interact.
- [15m] claps when excited -> yes | status: ok | reason: Oh yes, she definitely claps her hands when she's really happy about something.
- [15m] copies other children while playing like taking toys out of a container when another child does -> yes | status: ok | reason: She often watches other children and tries to do the same things they're doing with toys.
- [15m] hugs stuffed doll or other toy -> yes | status: ok | reason: She often cuddles her teddy bear and other soft toys.
- [18m] helps you dress him by pushing the arm through the sleeve or lifting up the foot -> yes | status: ok | reason: She understands when I ask her to lift her arm or foot to help get dressed.
- [18m] looks at a few pages in a book with you -> yes | status: ok | reason: She loves looking at the pictures and pointing things out.
- [18m] moves away from you but looks to make sure you are close by -> yes | status: ok | reason: She'll go explore but always looks back to make sure I'm still there.

Band summary:
  12m | total=1 | yes=1 | partial=0 | no=0 | yes_ratio=1.0
  15m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Social / Emotional: 18 months (chronological age 18 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 9 months ---
Q: Can Maya lifts arms up to be picked up right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She always puts her arms up when she wants to be picked up, she's very clear about it.
Q: Can Maya makes a lot of different sounds like mamamamama and bababababa right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She makes lots of different sounds like that, but they aren't actual words yet.

--- Asking Language / Communication milestones around 12 months ---
Q: Can Maya calls parents mama or dada or another special name right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She isn't saying any words yet, that's our main concern.
Q: Can Maya understands no so pauses briefly or stops when you say it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She definitely gets it when we say no, especially if she's doing something she shouldn't.
Q: Can Maya waves byebye right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She uses gestures to communicate, and waving is one of them.

--- Asking Language / Communication milestones around 15 months ---
Q: Can Maya follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we're asking for, especially when we show her with a gesture.
Q: Can Maya looks at a ffamiliar object when you name it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we say when we ask for things she knows.
Q: Can Maya points to ask for something or to get help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She uses gestures to tell us what she wants since she doesn't have words yet.

Question / answer transcript:
- [9m] lifts arms up to be picked up -> yes | status: ok | reason: She always puts her arms up when she wants to be picked up, she's very clear about it.
- [9m] makes a lot of different sounds like mamamamama and bababababa -> yes | status: ok | reason: She makes lots of different sounds like that, but they aren't actual words yet.
- [12m] calls parents mama or dada or another special name -> no | status: ok | reason: She isn't saying any words yet, that's our main concern.
- [12m] understands no so pauses briefly or stops when you say it -> yes | status: ok | reason: She definitely gets it when we say no, especially if she's doing something she shouldn't.
- [12m] waves byebye -> yes | status: ok | reason: She uses gestures to communicate, and waving is one of them.
- [15m] follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy -> yes | status: ok | reason: She understands what we're asking for, especially when we show her with a gesture.
- [15m] looks at a ffamiliar object when you name it -> yes | status: ok | reason: She understands what we say when we ask for things she knows.
- [15m] points to ask for something or to get help -> yes | status: ok | reason: She uses gestures to tell us what she wants since she doesn't have words yet.

Band summary:
  9m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  12m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67
  15m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Language / Communication: 15 months (chronological age 18 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 12 months ---
Q: Can Maya looks for things he sees you hide like a toy under a blanket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, she definitely knows where her toys go when we hide them!
Q: Can Maya puts something in a container like a block in a cap right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often puts her small toys into baskets and containers during playtime.

--- Asking Cognitive / Adaptive milestones around 15 months ---
Q: Can Maya stacks at least two small objects like blocks right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can stack her blocks, she likes to build with them.
Q: Can Maya tries to use things the right way like a phone or a cup or a book right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often pretends to talk on her toy phone or brings a cup to her mouth.

--- Asking Cognitive / Adaptive milestones around 18 months ---
Q: Can Maya copies you doing chores like sweeping with a broom right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves watching us and often tries to 'help' with her toy broom or cloth.
Q: Can Maya plays with toys in a simple way like pushing a toy car right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, she loves pushing her toy cars and trucks around the floor.

Question / answer transcript:
- [12m] looks for things he sees you hide like a toy under a blanket -> yes | status: ok | reason: Oh yes, she definitely knows where her toys go when we hide them!
- [12m] puts something in a container like a block in a cap -> yes | status: ok | reason: She often puts her small toys into baskets and containers during playtime.
- [15m] stacks at least two small objects like blocks -> yes | status: ok | reason: She can stack her blocks, she likes to build with them.
- [15m] tries to use things the right way like a phone or a cup or a book -> yes | status: ok | reason: She often pretends to talk on her toy phone or brings a cup to her mouth.
- [18m] copies you doing chores like sweeping with a broom -> yes | status: ok | reason: She loves watching us and often tries to 'help' with her toy broom or cloth.
- [18m] plays with toys in a simple way like pushing a toy car -> yes | status: ok | reason: Oh yes, she loves pushing her toy cars and trucks around the floor.

Band summary:
  12m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  15m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Cognitive / Adaptive: 18 months (chronological age 18 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
Summary: Weekly schedule built from category activity banks and true daily minute limits.
Daily time budget: 10
Target minutes by category: {'language_and_communication': 50}
Assigned minutes by category: {'language_and_communication': 32}

----------------------------------------------------------------------------------------------------
DAY_1 — total 5 min
----------------------------------------------------------------------------------------------------
- [Language / Communication] Name That Toy (5 min)
  Goal: monitor_and_enrich
  Instructions: Hold up a familiar toy and say its name clearly. Encourage Maya to look at the toy when you name it. You can also ask her to point to the toy when you say its name.
  Materials: A few familiar toys (e.g., ball, dog, doll)

----------------------------------------------------------------------------------------------------
DAY_2 — total 5 min
----------------------------------------------------------------------------------------------------
- [Language / Communication] Follow the Direction (5 min)
  Goal: monitor_and_enrich
  Instructions: Give Maya a simple one-step direction like 'give me the ball' without using gestures. Encourage her to respond by handing you the toy.
  Materials: A ball or another toy

----------------------------------------------------------------------------------------------------
DAY_3 — total 5 min
----------------------------------------------------------------------------------------------------
- [Language / Communication] Sound Imitation Game (5 min)
  Goal: monitor_and_enrich
  Instructions: Make simple sounds (like animal noises) and encourage Maya to imitate them. Use animals she knows, like a dog (bark) or cat (meow).
  Materials: None required, just your voice

----------------------------------------------------------------------------------------------------
DAY_4 — total 7 min
----------------------------------------------------------------------------------------------------
- [Language / Communication] Point and Ask (7 min)
  Goal: monitor_and_enrich
  Instructions: Place a few toys out of reach. Encourage Maya to point at the toy she wants and say a sound or word. Respond to her request by giving her the toy.
  Materials: A few toys placed out of reach


,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,18,0,no_special_support,minimal / mild
1,Social / Emotional,18,0,no_special_support,minimal / mild
2,Language / Communication,15,3,monitor_and_enrich,minimal / mild
3,Cognitive / Adaptive,18,0,no_special_support,minimal / mild

Focus areas:
  • Language / Communication

Daily activities:
1. Name That Toy | Language / Communication | 5 min
   Goal: monitor_and_enrich
   Description: Hold up a familiar toy and say its name clearly. Encourage Maya to look at the toy when you name it. You can also ask her to point to the toy when you say its name.
2. Follow the Direction | Language / Communication | 5 min
   Goal: monitor_and_enrich
   Description: Give Maya a simple one-step direction like 'give me the ball' without using gestures. Encourage her to respond by handing you the toy.
3. Sound Imitation Game | Language / Communication | 5 min
   Goal: monitor_and_enrich
   Description: Make simple sounds (like animal noises) and encourage Maya to imitate them. Use animals she knows, like a dog (bark) or cat (meow).
4. Point and Ask | Language / Communication | 7 min
   Goal: monitor_and_enrich
   Description: Place a few toys out of reach. Encourage Maya to point at the toy she wants and say a sound or word. Respond to her request by giving her the toy.
5. Story Time with Sounds | Language / Communication | 10 min
   Goal: monitor_and_enrich
   Description: Read a short picture book with animals or objects. Encourage Maya to make sounds or point to pictures as you read. Pause to let her respond.

4. SUMMARY
This plan prioritizes Language / Communication for Maya. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C03 | Leo | 2y 2m | Autism spectrum disorder
==============================================================================================================
Concerns: Limited eye contact and few words, Repetitive play, transitions hard, picky eating
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 6 month starting delay | Limited eye contact and repetitive play may indicate challenges in gross motor skills and coordination.
Social / Emotional: 12 month starting delay | Social interactions are often significantly impacted in children with autism spectrum disorder.
Language / Communication: 12 month starting delay | Limited eye contact and few words suggest significant delays in language development.
Cognitive / Adaptive: 6 month starting delay | Cognitive development is likely impacted by limited communication and repetitive play patterns.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 15 months ---
Q: Can Leo takes a few steps on her own right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he's been walking for a while now.
Q: Can Leo uses fingers to feed herself some food right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He uses his fingers for the few things he likes to eat.

--- Asking Movement / Physical milestones around 18 months ---
Q: Can Leo climbs on and off a couch or chair without help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's pretty good at climbing on furniture, he's always doing it.
Q: Can Leo drinks from a cup without a lid and may spill sometimes right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He can feed himself with his fingers, so he has the coordination for drinking from an open cup, even if he still spills now and then.
Q: Can Leo feeds himself with his fingers right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's able to pick up food with his fingers and eat it.

--- Asking Movement / Physical milestones around 24 months ---
Q: Can Leo eats with a spoon right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can for some foods, but often prefers his fingers.
Q: Can Leo kicks a ball right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's pretty good with his movements and can climb, so kicking a ball isn't usually an issue.
Q: Can Leo runs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very active and runs around the house when he's playing.

Question / answer transcript:
- [15m] takes a few steps on her own -> yes | status: ok | reason: Oh yes, he's been walking for a while now.
- [15m] uses fingers to feed herself some food -> yes | status: ok | reason: He uses his fingers for the few things he likes to eat.
- [18m] climbs on and off a couch or chair without help -> yes | status: ok | reason: He's pretty good at climbing on furniture, he's always doing it.
- [18m] drinks from a cup without a lid and may spill sometimes -> yes | status: ok | reason: He can feed himself with his fingers, so he has the coordination for drinking from an open cup, even if he still spills now and then.
- [18m] feeds himself with his fingers -> yes | status: ok | reason: He's able to pick up food with his fingers and eat it.
- [24m] eats with a spoon -> sometimes | status: ok | reason: He can for some foods, but often prefers his fingers.
- [24m] kicks a ball -> yes | status: ok | reason: He's pretty good with his movements and can climb, so kicking a ball isn't usually an issue.
- [24m] runs -> yes | status: ok | reason: He's very active and runs around the house when he's playing.

Band summary:
  15m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  24m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Movement / Physical: 24 months (chronological age 26 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 12 months ---
Q: Can Leo play games with you like pat a cake right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He struggles with the back-and-forth, and usually prefers to do his own thing.

--- Asking Social / Emotional milestones around 15 months ---
Q: Can Leo claps when excited right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He often claps his hands when he gets really excited, especially about his favorite toys.
Q: Can Leo copies other children while playing like taking toys out of a container when another child does right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He usually focuses on his own play and doesn't seem to notice what other kids are doing.
Q: Can Leo hugs stuffed doll or other toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He has a special teddy bear he likes to cuddle, especially when he's sleepy.

--- Asking Social / Emotional milestones around 18 months ---
Q: Can Leo helps you dress him by pushing the arm through the sleeve or lifting up the foot right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: I usually have to guide his hand or foot to get him started.
Q: Can Leo looks at a few pages in a book with you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: I have to really guide him to look at the pictures and keep him engaged for a few pages.
Q: Can Leo moves away from you but looks to make sure you are close by right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He gets really focused on his own play, but sometimes he'll do a quick check to see where I am.

Question / answer transcript:
- [12m] play games with you like pat a cake -> no | status: ok | reason: He struggles with the back-and-forth, and usually prefers to do his own thing.
- [15m] claps when excited -> yes | status: ok | reason: He often claps his hands when he gets really excited, especially about his favorite toys.
- [15m] copies other children while playing like taking toys out of a container when another child does -> no | status: ok | reason: He usually focuses on his own play and doesn't seem to notice what other kids are doing.
- [15m] hugs stuffed doll or other toy -> yes | status: ok | reason: He has a special teddy bear he likes to cuddle, especially when he's sleepy.
- [18m] helps you dress him by pushing the arm through the sleeve or lifting up the foot -> with_help | status: ok | reason: I usually have to guide his hand or foot to get him started.
- [18m] looks at a few pages in a book with you -> with_help | status: ok | reason: I have to really guide him to look at the pictures and keep him engaged for a few pages.
- [18m] moves away from you but looks to make sure you are close by -> sometimes | status: ok | reason: He gets really focused on his own play, but sometimes he'll do a quick check to see where I am.

Band summary:
  12m | total=1 | yes=0 | partial=0 | no=1 | yes_ratio=0.0
  15m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67
  18m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0

Estimated developmental age for Social / Emotional: 15 months (chronological age 26 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 12 months ---
Q: Can Leo calls parents mama or dada or another special name right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can say 'mama' or 'dada' occasionally, but it's not something he does consistently or often.
Q: Can Leo understands no so pauses briefly or stops when you say it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: It really depends on the situation; sometimes he'll pause, but other times he just keeps going.
Q: Can Leo waves byebye right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: We usually have to tell him to do it or show him, he doesn't often do it on his own.

--- Asking Language / Communication milestones around 15 months ---
Q: Can Leo follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He understands some words, especially with a gesture, but it's not every time.
Q: Can Leo looks at a ffamiliar object when you name it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll look at some things we name, especially if it's one of his preferred toys, but it's not consistent.
Q: Can Leo points to ask for something or to get help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He can point if we prompt him or guide his hand, but he doesn't typically do it on his own to ask for things.

--- Asking Language / Communication milestones around 18 months ---
Q: Can Leo follows one step directions without any gestures like giving you the toy when you say give it to me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He usually needs me to show him, but sometimes he'll understand a simple request without a gesture.
Q: Can Leo tries to say three or more words besides mama or dada right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He mostly just says mama and dada, we're working on getting more words.

Question / answer transcript:
- [12m] calls parents mama or dada or another special name -> sometimes | status: ok | reason: He can say 'mama' or 'dada' occasionally, but it's not something he does consistently or often.
- [12m] understands no so pauses briefly or stops when you say it -> sometimes | status: ok | reason: It really depends on the situation; sometimes he'll pause, but other times he just keeps going.
- [12m] waves byebye -> with_help | status: ok | reason: We usually have to tell him to do it or show him, he doesn't often do it on his own.
- [15m] follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy -> sometimes | status: ok | reason: He understands some words, especially with a gesture, but it's not every time.
- [15m] looks at a ffamiliar object when you name it -> sometimes | status: ok | reason: He'll look at some things we name, especially if it's one of his preferred toys, but it's not consistent.
- [15m] points to ask for something or to get help -> with_help | status: ok | reason: He can point if we prompt him or guide his hand, but he doesn't typically do it on his own to ask for things.
- [18m] follows one step directions without any gestures like giving you the toy when you say give it to me -> sometimes | status: ok | reason: He usually needs me to show him, but sometimes he'll understand a simple request without a gesture.
- [18m] tries to say three or more words besides mama or dada -> no | status: ok | reason: He mostly just says mama and dada, we're working on getting more words.

Band summary:
  12m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  15m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  18m | total=2 | yes=0 | partial=1 | no=1 | yes_ratio=0.0

Estimated developmental age for Language / Communication: 12 months (chronological age 26 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 15 months ---
Q: Can Leo stacks at least two small objects like blocks right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves to stack his blocks, it's one of his favorite repetitive activities.
Q: Can Leo tries to use things the right way like a phone or a cup or a book right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He knows how to bring a cup to his mouth and will flip through books. Sometimes he'll even hold a toy phone to his ear.

--- Asking Cognitive / Adaptive milestones around 18 months ---
Q: Can Leo copies you doing chores like sweeping with a broom right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can use objects the right way, so he understands the idea, but with his repetitive play, he doesn't consistently copy chores.
Q: Can Leo plays with toys in a simple way like pushing a toy car right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves pushing his cars and trains back and forth, he can do that for a while.

--- Asking Cognitive / Adaptive milestones around 24 months ---
Q: Can Leo holds something in one hand while using the other hand for example holding a container and taking the lid off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He opens his snack containers and toy boxes all the time.
Q: Can Leo plays with more than one toy at the same time like putting toy food on a toy plate right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: His play tends to be repetitive, so he doesn't always combine toys like that spontaneously.
Q: Can Leo tries to use switches or knobs or buttons on a toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's good with his hands and often presses buttons or turns knobs on his activity toys.

Question / answer transcript:
- [15m] stacks at least two small objects like blocks -> yes | status: ok | reason: He loves to stack his blocks, it's one of his favorite repetitive activities.
- [15m] tries to use things the right way like a phone or a cup or a book -> yes | status: ok | reason: He knows how to bring a cup to his mouth and will flip through books. Sometimes he'll even hold a toy phone to his ear.
- [18m] copies you doing chores like sweeping with a broom -> sometimes | status: ok | reason: He can use objects the right way, so he understands the idea, but with his repetitive play, he doesn't consistently copy chores.
- [18m] plays with toys in a simple way like pushing a toy car -> yes | status: ok | reason: He loves pushing his cars and trains back and forth, he can do that for a while.
- [24m] holds something in one hand while using the other hand for example holding a container and taking the lid off -> yes | status: ok | reason: He opens his snack containers and toy boxes all the time.
- [24m] plays with more than one toy at the same time like putting toy food on a toy plate -> sometimes | status: ok | reason: His play tends to be repetitive, so he doesn't always combine toys like that spontaneously.
- [24m] tries to use switches or knobs or buttons on a toy -> yes | status: ok | reason: He's good with his hands and often presses buttons or turns knobs on his activity toys.

Band summary:
  15m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=2 | yes=1 | partial=1 | no=0 | yes_ratio=0.5
  24m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Cognitive / Adaptive: 24 months (chronological age 26 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
Summary: Weekly schedule built from category activity banks and true daily minute limits.
Daily time budget: 10
Target minutes by category: {'movement_and_physical': 4, 'social_and_emotional': 19, 'language_and_communication': 23, 'cognitive': 4}
Assigned minutes by category: {'movement_and_physical': 5, 'social_and_emotional': 15, 'language_and_communication': 20, 'cognitive': 5}

----------------------------------------------------------------------------------------------------
DAY_1 — total 8 min
----------------------------------------------------------------------------------------------------
- [Language / Communication] Wave Goodbye (3 min)
  Goal: needs_special_support
  Instructions: Practice waving goodbye at different times, like when leaving a room or ending a play session. Encourage Leo to wave back.
  Materials: None required.
- [Social / Emotional] Excited Clapping (5 min)

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,24,2,monitor_and_enrich,minimal / mild
1,Social / Emotional,15,11,needs_special_support,moderate
2,Language / Communication,12,14,needs_special_support,moderate
3,Cognitive / Adaptive,24,2,monitor_and_enrich,minimal / mild

Focus areas:
  • Language / Communication
  • Social / Emotional
  • Movement / Physical

Daily activities:
1. Wave Goodbye | Language / Communication | 3 min
   Goal: needs_special_support
   Description: Practice waving goodbye at different times, like when leaving a room or ending a play session. Encourage Leo to wave back.
2. Excited Clapping | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: Play a fun song and encourage Leo to clap along with you when he feels excited. You can model the clapping and show facial expressions of joy.
3. Sound Imitation Game | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Make different animal sounds and encourage Leo to imitate them. Start with simple sounds like 'moo' or 'meow'.
4. Hugging Time | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: Select a stuffed toy and encourage Leo to hug it. Then, model hugging him and encourage him to hug you back, promoting affection and connection.
5. Point and Ask | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Place a few toys in front of Leo. Encourage him to point to a toy he wants and say its name or make a sound.

4. SUMMARY
This plan prioritizes Movement / Physical, Social / Emotional, Language / Communication for Leo. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C04 | Sofia | 3y 1m | Prematurity history
==============================================================================================================
Concerns: Speech hard to understand, Fine motor delay, good comprehension
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 6 month starting delay | Prematurity may impact physical development, leading to a slight delay.
Social / Emotional: 3 month starting delay | Prematurity may impact social/emotional development, leading to a slight delay.
Language / Communication: 12 month starting delay | Prematurity and speech concerns suggest a significant delay in language development.
Cognitive / Adaptive: 6 month starting delay | Prematurity may impact cognitive development, leading to a slight delay.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 24 months ---
Q: Can Sofia eats with a spoon right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can get some food in, but it's not always neat or easy because of her fine motor delay.
Q: Can Sofia kicks a ball right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves running around and kicking her ball.
Q: Can Sofia runs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's always running around the house and outside.

--- Asking Movement / Physical milestones around 30 months ---
Q: Can Sofia jumps off the ground with both feet right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves jumping, especially when we go to the park or find puddles.
Q: Can Sofia takes some clothes off by himself like loose pants or an open jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can get her loose pants or an open jacket off sometimes, but other times she struggles a bit with the sleeves or getting pants over her feet.
Q: Can Sofia turns book pages one at a time when you read to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries, but often grabs a few pages at once because of her fine motor delay.

--- Asking Movement / Physical milestones around 36 months ---
Q: Can Sofia puts on some clothes by himself like loose pants or a jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: She tries to put them on, but usually needs help to get them on right or pull them all the way up.
Q: Can Sofia strings items together like large beads or macaroni right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: She tries to string them but needs help getting the string through.
Q: Can Sofia uses a fork right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries with it, and can manage for some foods, but it's not always consistent or easy for her.

Question / answer transcript:
- [24m] eats with a spoon -> sometimes | status: ok | reason: She can get some food in, but it's not always neat or easy because of her fine motor delay.
- [24m] kicks a ball -> yes | status: ok | reason: She loves running around and kicking her ball.
- [24m] runs -> yes | status: ok | reason: She's always running around the house and outside.
- [30m] jumps off the ground with both feet -> yes | status: ok | reason: She loves jumping, especially when we go to the park or find puddles.
- [30m] takes some clothes off by himself like loose pants or an open jacket -> sometimes | status: ok | reason: She can get her loose pants or an open jacket off sometimes, but other times she struggles a bit with the sleeves or getting pants over her feet.
- [30m] turns book pages one at a time when you read to her -> sometimes | status: ok | reason: She tries, but often grabs a few pages at once because of her fine motor delay.
- [36m] puts on some clothes by himself like loose pants or a jacket -> with_help | status: ok | reason: She tries to put them on, but usually needs help to get them on right or pull them all the way up.
- [36m] strings items together like large beads or macaroni -> with_help | status: ok | reason: She tries to string them but needs help getting the string through.
- [36m] uses a fork -> sometimes | status: ok | reason: She tries with it, and can manage for some foods, but it's not always consistent or easy for her.

Band summary:
  24m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  30m | total=3 | yes=1 | partial=2 | no=0 | yes_ratio=0.33
  36m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0

Estimated developmental age for Movement / Physical: 24 months (chronological age 37 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 24 months ---
Q: Can Sofia looks at your face to see how to react in a new situation right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often looks at us to see how we're reacting, especially when she's unsure about something new.
Q: Can Sofia notices when others are hurt or upset like pausing or looking sad when someone is crying right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very observant and has good comprehension, so she picks up on those things easily.

--- Asking Social / Emotional milestones around 30 months ---
Q: Can Sofia follos simple routines when told like helping to pick up toys when you say it is clean up time right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we're asking her to do because her comprehension is good.
Q: Can Sofia plays next to other children and sometimes plays with them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She enjoys being around other kids and will sometimes join their games.
Q: Can Sofia shows you what she can do by saying look at me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves to show off her new skills and tries to get our attention when she does.

--- Asking Social / Emotional milestones around 36 months ---
Q: Can Sofia calms down within 10 minutes after you leave her like at childcare drop off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She usually settles down pretty quickly after drop-off.
Q: Can Sofia notices other children and joins them to play right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She already plays with other children sometimes, so she clearly notices them and can join in.

Question / answer transcript:
- [24m] looks at your face to see how to react in a new situation -> yes | status: ok | reason: She often looks at us to see how we're reacting, especially when she's unsure about something new.
- [24m] notices when others are hurt or upset like pausing or looking sad when someone is crying -> yes | status: ok | reason: She's very observant and has good comprehension, so she picks up on those things easily.
- [30m] follos simple routines when told like helping to pick up toys when you say it is clean up time -> yes | status: ok | reason: She understands what we're asking her to do because her comprehension is good.
- [30m] plays next to other children and sometimes plays with them -> yes | status: ok | reason: She enjoys being around other kids and will sometimes join their games.
- [30m] shows you what she can do by saying look at me -> yes | status: ok | reason: She loves to show off her new skills and tries to get our attention when she does.
- [36m] calms down within 10 minutes after you leave her like at childcare drop off -> yes | status: ok | reason: She usually settles down pretty quickly after drop-off.
- [36m] notices other children and joins them to play -> yes | status: ok | reason: She already plays with other children sometimes, so she clearly notices them and can join in.

Band summary:
  24m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  30m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  36m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Social / Emotional: 36 months (chronological age 37 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 18 months ---
Q: Can Sofia follows one step directions without any gestures like giving you the toy when you say give it to me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we say very well, even if her speech is hard to understand sometimes.
Q: Can Sofia tries to say three or more words besides mama or dada right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She tries to say lots of words, even if they're hard to understand.

--- Asking Language / Communication milestones around 24 months ---
Q: Can Sofia points at least two body parts when you ask her to show you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask and can point to many body parts.
Q: Can Sofia points to things in a book when you ask like where is the bear right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask and can point to things easily in books.
Q: Can Sofia says at least two words together like more milk right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She puts little words together, even if they're not always clear.

--- Asking Language / Communication milestones around 30 months ---
Q: Can Sofia name things in a book when you point and ask what is this right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She knows a lot of words and points them out, even if they aren't always super clear.
Q: Can Sofia say two or more words toghether with one action word like doggie run right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She already puts two words together like 'more milk', so she definitely tries to combine action words too.
Q: Can Sofia says about 50 words right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She talks a lot and can name many things and even put words together.

Question / answer transcript:
- [18m] follows one step directions without any gestures like giving you the toy when you say give it to me -> yes | status: ok | reason: She understands what we say very well, even if her speech is hard to understand sometimes.
- [18m] tries to say three or more words besides mama or dada -> yes | status: ok | reason: She tries to say lots of words, even if they're hard to understand.
- [24m] points at least two body parts when you ask her to show you -> yes | status: ok | reason: She understands what we ask and can point to many body parts.
- [24m] points to things in a book when you ask like where is the bear -> yes | status: ok | reason: She understands what we ask and can point to things easily in books.
- [24m] says at least two words together like more milk -> yes | status: ok | reason: She puts little words together, even if they're not always clear.
- [30m] name things in a book when you point and ask what is this -> yes | status: ok | reason: She knows a lot of words and points them out, even if they aren't always super clear.
- [30m] say two or more words toghether with one action word like doggie run -> yes | status: ok | reason: She already puts two words together like 'more milk', so she definitely tries to combine action words too.
- [30m] says about 50 words -> yes | status: ok | reason: She talks a lot and can name many things and even put words together.

Band summary:
  18m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  24m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  30m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Language / Communication: 30 months (chronological age 37 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 24 months ---
Q: Can Sofia holds something in one hand while using the other hand for example holding a container and taking the lid off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can do it with some things, but it's still tricky for her because of her fine motor delay.
Q: Can Sofia plays with more than one toy at the same time like putting toy food on a toy plate right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves pretend play and understands putting things together like that, even if her fine motor makes it a little tricky sometimes.
Q: Can Sofia tries to use switches or knobs or buttons on a toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She knows what they do and likes to push them.

--- Asking Cognitive / Adaptive milestones around 30 months ---
Q: Can Sofia follows two step instructions like put the toy down and close the door right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask her to do, her comprehension is quite good.
Q: Can Sofia shows she knows at least one color like pointing to a red crayon when you ask which one is red right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands when we ask her to point to a color.
Q: Can Sofia shows simple problem solving skills like standing on a small stool to reach something right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty clever and will figure out ways to get what she wants, like standing on something.

--- Asking Cognitive / Adaptive milestones around 36 months ---
Q: Can Sofia avoids touching hot objects like the stove when you warn her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She knows it's hot and listens when we tell her not to touch it.
Q: Can Sofia draws a circle when you show her how right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries to copy when I show her, but because of her fine motor delay, it's not always a clear circle.

Question / answer transcript:
- [24m] holds something in one hand while using the other hand for example holding a container and taking the lid off -> sometimes | status: ok | reason: She can do it with some things, but it's still tricky for her because of her fine motor delay.
- [24m] plays with more than one toy at the same time like putting toy food on a toy plate -> yes | status: ok | reason: She loves pretend play and understands putting things together like that, even if her fine motor makes it a little tricky sometimes.
- [24m] tries to use switches or knobs or buttons on a toy -> yes | status: ok | reason: She knows what they do and likes to push them.
- [30m] follows two step instructions like put the toy down and close the door -> yes | status: ok | reason: She understands what we ask her to do, her comprehension is quite good.
- [30m] shows she knows at least one color like pointing to a red crayon when you ask which one is red -> yes | status: ok | reason: She understands when we ask her to point to a color.
- [30m] shows simple problem solving skills like standing on a small stool to reach something -> yes | status: ok | reason: She's pretty clever and will figure out ways to get what she wants, like standing on something.
- [36m] avoids touching hot objects like the stove when you warn her -> yes | status: ok | reason: She knows it's hot and listens when we tell her not to touch it.
- [36m] draws a circle when you show her how -> sometimes | status: ok | reason: She tries to copy when I show her, but because of her fine motor delay, it's not always a clear circle.

Band summary:
  24m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  30m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  36m | total=2 | yes=1 | partial=1 | no=0 | yes_ratio=0.5

Estimated developmental age for Cognitive / Adaptive: 30 months (chronological age 37 months)

====================================================================================================
WEEKLY SCHEDULE

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,24,13,needs_special_support,moderate
1,Social / Emotional,36,1,no_special_support,minimal / mild
2,Language / Communication,30,7,needs_special_support,moderate
3,Cognitive / Adaptive,30,7,needs_special_support,moderate

Focus areas:
  • Movement / Physical
  • Language / Communication
  • Cognitive / Adaptive

Daily activities:
1. Spoon Practice | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Give Sofia a bowl with some soft food (like yogurt or mashed bananas) and a spoon. Encourage her to scoop and eat independently, offering help as needed.
2. Color Sorting | Cognitive / Adaptive | 5 min
   Goal: needs_special_support
   Description: Gather a few colored items (like blocks or crayons). Ask Sofia to sort them by color, saying 'Can you put all the red ones here?' and 'Now, can you find the blue ones?'
3. Stair Climbing | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Supervise Sofia as she walks up and down a few stairs. Encourage her to hold onto the railing or your hand for support, focusing on her balance and strength.
4. Two-Step Instructions | Cognitive / Adaptive | 5 min
   Goal: needs_special_support
   Description: Give Sofia two-step instructions like 'Pick up the toy and put it in the box.' Praise her when she follows through.
5. Ball Kicking | Movement / Physical | 7 min
   Goal: needs_special_support
   Description: Set up a soft ball in a safe space. Encourage Sofia to kick the ball towards a target, like a box or a wall. Celebrate her attempts and encourage her to try again.

4. SUMMARY
This plan prioritizes Movement / Physical, Language / Communication, Cognitive / Adaptive for Sofia. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C05 | Ethan | 4y 6m | Cerebral palsy
==============================================================================================================
Concerns: Trouble keeping up in preschool, Self-care delays, frequent falls, difficulty with stairs, uses walker sometimes, good cognition
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 18 month starting delay | Cerebral palsy and related concerns indicate significant challenges in movement and physical skills.
Social / Emotional: 6 month starting delay | Social interactions may be impacted by physical challenges and mobility issues.
Language / Communication: 6 month starting delay | Cerebral palsy can impact speech clarity and communication skills.
Cognitive / Adaptive: 12 month starting delay | Cerebral palsy may impact cognitive/adaptive skills, leading to a functional developmental level around 42 months.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 24 months ---
Q: Can Ethan eats with a spoon right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He has self-care delays, so he needs some help to eat with a spoon.
Q: Can Ethan kicks a ball right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He has frequent falls and can't balance well enough to kick a ball without falling.
Q: Can Ethan runs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He falls too much.

--- Asking Movement / Physical milestones around 30 months ---
Q: Can Ethan jumps off the ground with both feet right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He has a lot of trouble with balance and falls often, so jumping isn't really something he can do.
Q: Can Ethan takes some clothes off by himself like loose pants or an open jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He tries to pull them off, but he always needs a hand to finish getting them past his feet or arms because of his motor challenges.
Q: Can Ethan turns book pages one at a time when you read to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He has good cognition and wants to turn pages, but his fine motor control makes it hard for him to turn just one at a time without some help.

--- Asking Movement / Physical milestones around 36 months ---
Q: Can Ethan puts on some clothes by himself like loose pants or a jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He tries to help but still needs a lot of assistance to get his clothes on.
Q: Can Ethan strings items together like large beads or macaroni right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He has trouble with small, precise movements and needs some assistance to get the string through the holes.
Q: Can Ethan uses a fork right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He tries, but usually needs a little help getting the food on it and to his mouth.

Question / answer transcript:
- [24m] eats with a spoon -> with_help | status: ok | reason: He has self-care delays, so he needs some help to eat with a spoon.
- [24m] kicks a ball -> no | status: ok | reason: He has frequent falls and can't balance well enough to kick a ball without falling.
- [24m] runs -> no | status: ok | reason: He falls too much.
- [30m] jumps off the ground with both feet -> no | status: ok | reason: He has a lot of trouble with balance and falls often, so jumping isn't really something he can do.
- [30m] takes some clothes off by himself like loose pants or an open jacket -> with_help | status: ok | reason: He tries to pull them off, but he always needs a hand to finish getting them past his feet or arms because of his motor challenges.
- [30m] turns book pages one at a time when you read to her -> with_help | status: ok | reason: He has good cognition and wants to turn pages, but his fine motor control makes it hard for him to turn just one at a time without some help.
- [36m] puts on some clothes by himself like loose pants or a jacket -> with_help | status: ok | reason: He tries to help but still needs a lot of assistance to get his clothes on.
- [36m] strings items together like large beads or macaroni -> with_help | status: ok | reason: He has trouble with small, precise movements and needs some assistance to get the string through the holes.
- [36m] uses a fork -> with_help | status: ok | reason: He tries, but usually needs a little help getting the food on it and to his mouth.

Band summary:
  24m | total=3 | yes=0 | partial=1 | no=2 | yes_ratio=0.0
  30m | total=3 | yes=0 | partial=2 | no=1 | yes_ratio=0.0
  36m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0

Estimated developmental age for Movement / Physical: 24 months (chronological age 54 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 36 months ---
Q: Can Ethan calms down within 10 minutes after you leave her like at childcare drop off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's used to preschool and understands we'll be back.
Q: Can Ethan notices other children and joins them to play right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very aware of other children and loves to be part of what they're doing.

--- Asking Social / Emotional milestones around 48 months ---
Q: Can Ethan asks to go play with children if none are around like can I play with Alex right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and knows how to ask for what he wants, especially when it comes to playing with his friends.
Q: Can Ethan avoids danger like not jumping from tall heights at the playgroung right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very aware of his body and what he can and can't do, especially with his CP. He knows his limits.
Q: Can Ethan changes behavior based on where she is like place of worship or library or playground right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's good at understanding what's expected in different places, like being quiet in church or running around at the park.

--- Asking Social / Emotional milestones around 60 months ---
Q: Can Ethan does simple chores at home like matching socks or cleaning the table after eating right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He understands what we ask him to do, but his coordination and physical challenges make it hard for him to do the actual tasks independently.
Q: Can Ethan follows rules or takesake turns when playing games with other  children right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's bright and understands what's expected in games, even if he sometimes has trouble with the physical parts of playing.
Q: Can Ethan sings dances or acts for you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves to sing and get into character, even if his dancing looks a bit different sometimes.

Question / answer transcript:
- [36m] calms down within 10 minutes after you leave her like at childcare drop off -> yes | status: ok | reason: He's used to preschool and understands we'll be back.
- [36m] notices other children and joins them to play -> yes | status: ok | reason: He's very aware of other children and loves to be part of what they're doing.
- [48m] asks to go play with children if none are around like can I play with Alex -> yes | status: ok | reason: He's very social and knows how to ask for what he wants, especially when it comes to playing with his friends.
- [48m] avoids danger like not jumping from tall heights at the playgroung -> yes | status: ok | reason: He's very aware of his body and what he can and can't do, especially with his CP. He knows his limits.
- [48m] changes behavior based on where she is like place of worship or library or playground -> yes | status: ok | reason: He's good at understanding what's expected in different places, like being quiet in church or running around at the park.
- [60m] does simple chores at home like matching socks or cleaning the table after eating -> with_help | status: ok | reason: He understands what we ask him to do, but his coordination and physical challenges make it hard for him to do the actual tasks independently.
- [60m] follows rules or takesake turns when playing games with other  children -> yes | status: ok | reason: He's bright and understands what's expected in games, even if he sometimes has trouble with the physical parts of playing.
- [60m] sings dances or acts for you -> yes | status: ok | reason: He loves to sing and get into character, even if his dancing looks a bit different sometimes.

Band summary:
  36m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  48m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  60m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Social / Emotional: 60 months (chronological age 54 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 36 months ---
Q: Can Ethan ask who or what or where or why questions like where is mommy or where is daddy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very good with his words and is always curious about things.
Q: Can Ethan says first name when asked right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He knows his name and can say it clearly.
Q: Can Ethan says what action is happening in a picture or book when asked like running or eating or playing right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he's very good at understanding what's happening and telling us. His mind is very sharp.

--- Asking Language / Communication milestones around 48 months ---
Q: Can Ethan answers simple questions like what is a coat for or what is crayon for right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's pretty good at understanding things and knows what objects are used for.
Q: Can Ethan says sentences with four or more words right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He talks a lot and can ask all sorts of questions, so his sentences are definitely long enough.
Q: Can Ethan says some words from a song or story or nursery rhyme right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves singing along to his favorite songs and knows many of his preschool rhymes.

--- Asking Language / Communication milestones around 60 months ---
Q: Can Ethan answers simple questions about a book or a story after you read or tell it to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He understands stories really well and can tell us about them.
Q: Can Ethan keep a conversation going with more than three back and forth exchanges right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very chatty and loves to tell us about his day at preschool, asking us questions too.
Q: Can Ethan tells a storys she heard or made up with at least two events for example cat was stuck in a tree and firefighter saved it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's really good with words and can remember things from books or even make up little adventures.

Question / answer transcript:
- [36m] ask who or what or where or why questions like where is mommy or where is daddy -> yes | status: ok | reason: He's very good with his words and is always curious about things.
- [36m] says first name when asked -> yes | status: ok | reason: He knows his name and can say it clearly.
- [36m] says what action is happening in a picture or book when asked like running or eating or playing -> yes | status: ok | reason: Oh yes, he's very good at understanding what's happening and telling us. His mind is very sharp.
- [48m] answers simple questions like what is a coat for or what is crayon for -> yes | status: ok | reason: He's pretty good at understanding things and knows what objects are used for.
- [48m] says sentences with four or more words -> yes | status: ok | reason: He talks a lot and can ask all sorts of questions, so his sentences are definitely long enough.
- [48m] says some words from a song or story or nursery rhyme -> yes | status: ok | reason: He loves singing along to his favorite songs and knows many of his preschool rhymes.
- [60m] answers simple questions about a book or a story after you read or tell it to her -> yes | status: ok | reason: He understands stories really well and can tell us about them.
- [60m] keep a conversation going with more than three back and forth exchanges -> yes | status: ok | reason: He's very chatty and loves to tell us about his day at preschool, asking us questions too.
- [60m] tells a storys she heard or made up with at least two events for example cat was stuck in a tree and firefighter saved it -> yes | status: ok | reason: He's really good with words and can remember things from books or even make up little adventures.

Band summary:
  36m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  48m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  60m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Language / Communication: 60 months (chronological age 54 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 30 months ---
Q: Can Ethan follows two step instructions like put the toy down and close the door right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very bright and understands what we tell him, his cognition is good.
Q: Can Ethan shows she knows at least one color like pointing to a red crayon when you ask which one is red right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he's really good with his colors, even with all his other challenges.
Q: Can Ethan shows simple problem solving skills like standing on a small stool to reach something right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He knows he needs a stool to reach things, but due to his balance issues, we always need to help him get on and off safely.

--- Asking Cognitive / Adaptive milestones around 36 months ---
Q: Can Ethan avoids touching hot objects like the stove when you warn her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very smart and knows not to touch things when we tell him they're hot.
Q: Can Ethan draws a circle when you show her how right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He understands what a circle is and tries, but his hand often needs some guidance due to his CP.

--- Asking Cognitive / Adaptive milestones around 48 months ---
Q: Can Ethan draws a person with three or more body parts right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: He needs help to draw a simple circle, so a more complex drawing like a person would definitely require help due to his CP.
Q: Can Ethan names a few colors or items right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He has good cognition, and he can already point out colors, so naming them isn't a problem.
Q: Can Ethan tell what comes next in a well known story right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves story time and knows his favorite books inside out, he'll finish sentences for us.

Question / answer transcript:
- [30m] follows two step instructions like put the toy down and close the door -> yes | status: ok | reason: He's very bright and understands what we tell him, his cognition is good.

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,24,30,needs_special_support,significant
1,Social / Emotional,60,0,no_special_support,minimal / mild
2,Language / Communication,60,0,no_special_support,minimal / mild
3,Cognitive / Adaptive,48,6,monitor_and_enrich,minimal / mild

Focus areas:
  • Movement / Physical
  • Cognitive / Adaptive

Daily activities:
1. Spoon Practice | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Provide Ethan with a bowl of soft food and a spoon. Encourage him to scoop and eat independently, offering guidance as needed.
2. Color Hunt | Cognitive / Adaptive | 5 min
   Goal: monitor_and_enrich
   Description: Go on a color hunt around the house. Ask Ethan to find objects of a specific color and name them as he finds them.
3. Ball Kicking | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Set up a soft ball in a safe space. Encourage Ethan to kick the ball forward, using his walker for support if needed.
4. Counting Fun | Cognitive / Adaptive | 5 min
   Goal: monitor_and_enrich
   Description: Count objects around the house together, such as toys or snacks. Help Ethan count up to 10.
5. Jumping Fun | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Create a safe space with a soft surface. Encourage Ethan to jump with both feet, using a small trampoline or jumping in place.

4. SUMMARY
This plan prioritizes Movement / Physical, Cognitive / Adaptive for Ethan. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

--------------------------------------------------------------------------------------------------------------
Batch complete. Waiting 120 seconds before next batch...
--------------------------------------------------------------------------------------------------------------

==============================================================================================================
RUNNING BATCH 2 | cases 6 to 10 of 14
==============================================================================================================

==============================================================================================================
STARTING C06 | Amina | 5 years | Global developmental delay
==============================================================================================================
Concerns: Learning and routines are hard, Short attention span, follows only simple directions
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 6 month starting delay | The child's global developmental delay and concerns suggest significant challenges in movement and physical skills.
Social / Emotional: 6 month starting delay | The child's difficulties with attention and following directions suggest a significant impact on social/emotional development.
Language / Communication: 6 month starting delay | The child shows signs of significant language delays with a short attention span and difficulty following directions.
Cognitive / Adaptive: 18 month starting delay | The child's difficulties with learning and following directions suggest a significant cognitive delay.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 48 months ---
Q: Can Amina catches a large ball most of the times right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries, and she gets some, but it's not consistent yet.
Q: Can Amina holds crayon or pencil between fingers and thumb not fist right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She's learning to hold it properly, but sometimes she still grips it with her whole hand.
Q: Can Amina serves herself food or pours water with adult supervision right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries, but her short attention span and difficulty with routines mean she often needs reminders or gets distracted, even with us watching closely.

--- Asking Movement / Physical milestones around 60 months ---
Q: Can Amina buttons some buttons right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: She needs help with the steps and getting the button through, as she loses focus easily.
Q: Can Amina hops on one foot right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can hop a few times, but usually loses her balance quickly.

Question / answer transcript:
- [48m] catches a large ball most of the times -> sometimes | status: ok | reason: She tries, and she gets some, but it's not consistent yet.
- [48m] holds crayon or pencil between fingers and thumb not fist -> sometimes | status: ok | reason: She's learning to hold it properly, but sometimes she still grips it with her whole hand.
- [48m] serves herself food or pours water with adult supervision -> sometimes | status: ok | reason: She tries, but her short attention span and difficulty with routines mean she often needs reminders or gets distracted, even with us watching closely.
- [60m] buttons some buttons -> with_help | status: ok | reason: She needs help with the steps and getting the button through, as she loses focus easily.
- [60m] hops on one foot -> sometimes | status: ok | reason: She can hop a few times, but usually loses her balance quickly.

Band summary:
  48m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  60m | total=2 | yes=0 | partial=2 | no=0 | yes_ratio=0.0

Estimated developmental age for Movement / Physical: 48 months (chronological age 60 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 48 months ---
Q: Can Amina asks to go play with children if none are around like can I play with Alex right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She mostly plays by herself or needs prompting, and usually only initiates play if the other child is present.
Q: Can Amina avoids danger like not jumping from tall heights at the playgroung right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She doesn't really understand how dangerous some things are, so we have to watch her very closely.
Q: Can Amina changes behavior based on where she is like place of worship or library or playground right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: She needs constant reminders and guidance to change her behavior based on where we are, it doesn't come naturally for her yet.

--- Asking Social / Emotional milestones around 60 months ---
Q: Can Amina does simple chores at home like matching socks or cleaning the table after eating right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: She needs a lot of guidance and prompting to get through even simple tasks, and her attention span is short.
Q: Can Amina follows rules or takesake turns when playing games with other  children right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: Learning rules and waiting for her turn are hard for Amina because of her short attention span and difficulties with routines.
Q: Can Amina sings dances or acts for you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She sometimes hums along or does a little dance when she hears music she likes, but it's not a consistent performance for us.

Question / answer transcript:
- [48m] asks to go play with children if none are around like can I play with Alex -> no | status: ok | reason: She mostly plays by herself or needs prompting, and usually only initiates play if the other child is present.
- [48m] avoids danger like not jumping from tall heights at the playgroung -> no | status: ok | reason: She doesn't really understand how dangerous some things are, so we have to watch her very closely.
- [48m] changes behavior based on where she is like place of worship or library or playground -> with_help | status: ok | reason: She needs constant reminders and guidance to change her behavior based on where we are, it doesn't come naturally for her yet.
- [60m] does simple chores at home like matching socks or cleaning the table after eating -> with_help | status: ok | reason: She needs a lot of guidance and prompting to get through even simple tasks, and her attention span is short.
- [60m] follows rules or takesake turns when playing games with other  children -> with_help | status: ok | reason: Learning rules and waiting for her turn are hard for Amina because of her short attention span and difficulties with routines.
- [60m] sings dances or acts for you -> sometimes | status: ok | reason: She sometimes hums along or does a little dance when she hears music she likes, but it's not a consistent performance for us.

Band summary:
  48m | total=3 | yes=0 | partial=1 | no=2 | yes_ratio=0.0
  60m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0

Estimated developmental age for Social / Emotional: 48 months (chronological age 60 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 48 months ---
Q: Can Amina answers simple questions like what is a coat for or what is crayon for right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She only follows very simple directions, so explaining the purpose of things like a coat or crayon is too hard for her right now.
Q: Can Amina says sentences with four or more words right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She mostly uses single words or very short phrases right now.
Q: Can Amina says some words from a song or story or nursery rhyme right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She struggles with learning and has a short attention span, so picking up words from songs or stories is very hard for her right now.

--- Asking Language / Communication milestones around 60 months ---
Q: Can Amina answers simple questions about a book or a story after you read or tell it to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She really struggles to understand and answer questions like that, especially after hearing a whole story.
Q: Can Amina keep a conversation going with more than three back and forth exchanges right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She can't really talk back and forth much, and her attention span is very short.
Q: Can Amina tells a storys she heard or made up with at least two events for example cat was stuck in a tree and firefighter saved it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She can't make up complex sentences yet, let alone tell a whole story with events.

Question / answer transcript:
- [48m] answers simple questions like what is a coat for or what is crayon for -> no | status: ok | reason: She only follows very simple directions, so explaining the purpose of things like a coat or crayon is too hard for her right now.
- [48m] says sentences with four or more words -> no | status: ok | reason: She mostly uses single words or very short phrases right now.
- [48m] says some words from a song or story or nursery rhyme -> no | status: ok | reason: She struggles with learning and has a short attention span, so picking up words from songs or stories is very hard for her right now.
- [60m] answers simple questions about a book or a story after you read or tell it to her -> no | status: ok | reason: She really struggles to understand and answer questions like that, especially after hearing a whole story.
- [60m] keep a conversation going with more than three back and forth exchanges -> no | status: ok | reason: She can't really talk back and forth much, and her attention span is very short.
- [60m] tells a storys she heard or made up with at least two events for example cat was stuck in a tree and firefighter saved it -> no | status: ok | reason: She can't make up complex sentences yet, let alone tell a whole story with events.

Band summary:
  48m | total=3 | yes=0 | partial=0 | no=3 | yes_ratio=0.0
  60m | total=3 | yes=0 | partial=0 | no=3 | yes_ratio=0.0

Estimated developmental age for Language / Communication: 48 months (chronological age 60 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 30 months ---
Q: Can Amina follows two step instructions like put the toy down and close the door right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She only follows simple directions, two steps are too much for her right now.
Q: Can Amina shows she knows at least one color like pointing to a red crayon when you ask which one is red right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She sometimes knows one, but learning colors is hard for her.
Q: Can Amina shows simple problem solving skills like standing on a small stool to reach something right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She might try if she really wants something, but she doesn't always think of it.

--- Asking Cognitive / Adaptive milestones around 36 months ---
Q: Can Amina avoids touching hot objects like the stove when you warn her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She knows 'hot' but her attention can be short, so sometimes she still tries to touch things.
Q: Can Amina draws a circle when you show her how right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries, but it's not always a perfect circle, and it depends on the day.

--- Asking Cognitive / Adaptive milestones around 48 months ---
Q: Can Amina draws a person with three or more body parts right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries to draw people, and sometimes she'll make a head with a few lines for arms or legs, but it's not consistent.
Q: Can Amina names a few colors or items right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can name a few very familiar things, but it's not consistent and she struggles with colors.
Q: Can Amina tell what comes next in a well known story right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: Learning new things is really hard for her, and she has trouble following along with the story.

Question / answer transcript:
- [30m] follows two step instructions like put the toy down and close the door -> no | status: ok | reason: She only follows simple directions, two steps are too much for her right now.
- [30m] shows she knows at least one color like pointing to a red crayon when you ask which one is red -> sometimes | status: ok | reason: She sometimes knows one, but learning colors is hard for her.
- [30m] shows simple problem solving skills like standing on a small stool to reach something -> sometimes | status: ok | reason: She might try if she really wants something, but she doesn't always think of it.
- [36m] avoids touching hot objects like the stove when you warn her -> sometimes | status: ok | reason: She knows 'hot' but her attention can be short, so sometimes she still tries to touch things.
- [36m] draws a circle when you show her how -> sometimes | status: ok | reason: She tries, but it's not always a perfect circle, and it depends on the day.
- [48m] draws a person with three or more body parts -> sometimes | status: ok | reason: She tries to draw people, and sometimes she'll make a head with a few lines for arms or legs, but it's not consistent.
- [48m] names a few colors or items -> sometimes | status: ok | reason: She can name a few very familiar things, but it's not consistent and she struggles with colors.
- [48m] tell what comes next in a well known story -> no | status: ok | reason: Learning new things is really hard for her, and she has trouble following along with the story.

Band summary:
  30m | total=3 | yes=0 | partial=2 | no=1 | yes_ratio=0.0
  36m | total=2 | yes=0 | partial=2 | no=0 | yes_ratio=0.0
  48m | total=3 | yes=0 | partial=2 | no=1 | yes_ratio=0.0

Estimated developmental age for Cognitive / Adaptive: 30 months (chronological age 60 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
Summary: Weekly schedule built from category activity banks and true daily minute limits.
Daily time budget: 10
Target minutes by category: {'movement_and_physical': 10, 'social_and_emotional': 10, 'language_and_communication': 10, 'cognitive': 19}
Assigned minutes by category: {'movement_and_physical': 10, 'social_and_emotional': 10, 'language_and_communication': 10, 'cognitive': 20}

----------------------------------------------------------------------------------------------------
DAY_1 — total 10 min
----------------------------------------------------------------------------------------------------
- [Cognitive / Adaptive] Color Sorting (5 min)
  Goal: needs_special_support
  Instructions: Gather a few colored items (like blocks or crayons). Ask Amina to sort them into groups by color. You can say, 'Can you put all the red ones here?'
  Materials: Colored blocks or crayons
- [Social / Emotional] Playful Pretend (5 min)
  Goal: needs_special_support
  Instructions: Choose a character together (like a superhero or teacher) and take turns pretending to be that character. Use simple phrases and actions to act out scenarios.
  Materials: Costumes or props (optional)

----------------------------------------------------------------------------------------------------
DAY_2 — total 10 min
----------------------------------------------------------------------------------------------------
- [Cognitive / Adaptive] Two-Step Instructions (5 min)
  Goal: needs_special_support
  Instructions: Give Amina simple two-step instructions like 'Pick up the toy and put it in the box.' Praise her when she follows the directions.
  Materials: Toys or household items
- [Social / Emotional] Emotion Charades (5 min)
  Goal: needs_special_support

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,48,12,needs_special_support,moderate
1,Social / Emotional,48,12,needs_special_support,moderate
2,Language / Communication,48,12,needs_special_support,moderate
3,Cognitive / Adaptive,30,30,needs_special_support,significant

Focus areas:
  • Cognitive / Adaptive
  • Movement / Physical
  • Social / Emotional

Daily activities:
1. Color Sorting | Cognitive / Adaptive | 5 min
   Goal: needs_special_support
   Description: Gather a few colored items (like blocks or crayons). Ask Amina to sort them into groups by color. You can say, 'Can you put all the red ones here?'
2. Playful Pretend | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: Choose a character together (like a superhero or teacher) and take turns pretending to be that character. Use simple phrases and actions to act out scenarios.
3. Two-Step Instructions | Cognitive / Adaptive | 5 min
   Goal: needs_special_support
   Description: Give Amina simple two-step instructions like 'Pick up the toy and put it in the box.' Praise her when she follows the directions.
4. Emotion Charades | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: Take turns making faces to show different emotions (happy, sad, surprised). The other person guesses the emotion and then switches roles.
5. Problem-Solving with a Stool | Cognitive / Adaptive | 5 min
   Goal: needs_special_support
   Description: Place a toy on a high shelf and encourage Amina to use a small stool to reach it. Guide her by saying, 'Can you stand on the stool to get the toy?'

4. SUMMARY
This plan prioritizes Movement / Physical, Social / Emotional, Language / Communication for Amina. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C07 | Lucas | 14 months | Fragile X syndrome
==============================================================================================================
Concerns: Not walking, limited babbling, Sensory sensitivity, shy socially
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 6 month starting delay | Fragile X syndrome and parent concerns suggest significant impact on movement development.
Social / Emotional: 6 month starting delay | Social shyness and limited babbling suggest a moderate delay in social/emotional development.
Language / Communication: 6 month starting delay | Language development is often impacted in children with Fragile X syndrome, leading to a noticeable delay.
Cognitive / Adaptive: 6 month starting delay | Cognitive development may be impacted by Fragile X syndrome and associated concerns.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 4 months ---
Q: Can Lucas bring hands to mouth right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's been doing that for a while.
Q: Can Lucas holds a toy when you put it in his hand right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he definitely holds onto things once you put them in his hand.
Q: Can Lucas holds head steady without support when you are holding him right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's had good head control for quite a while now.

--- Asking Movement / Physical milestones around 6 months ---
Q: Can Lucas leans on hands to support herself when sitting right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He often puts his hands down to keep steady when he's sitting.
Q: Can Lucas pushes up with straight arms when on tummy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's got good arm strength and can push himself up well, especially since he can lean on his hands when sitting.
Q: Can Lucas rolls from tummy to back right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He can push up with his arms when he's on his tummy, so he definitely has the strength to roll over.

--- Asking Movement / Physical milestones around 9 months ---
Q: Can Lucas gets to sitting position by herself right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He uses his arms to push himself up from his tummy to get into a sitting position.
Q: Can Lucas moves things from one hand to her other hand right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He often switches toys from one hand to the other while he's playing.
Q: Can Lucas sits without support right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He still needs to lean on his hands to stay steady when he sits.

Question / answer transcript:
- [4m] bring hands to mouth -> yes | status: ok | reason: He's been doing that for a while.
- [4m] holds a toy when you put it in his hand -> yes | status: ok | reason: Oh yes, he definitely holds onto things once you put them in his hand.
- [4m] holds head steady without support when you are holding him -> yes | status: ok | reason: He's had good head control for quite a while now.
- [6m] leans on hands to support herself when sitting -> yes | status: ok | reason: He often puts his hands down to keep steady when he's sitting.
- [6m] pushes up with straight arms when on tummy -> yes | status: ok | reason: He's got good arm strength and can push himself up well, especially since he can lean on his hands when sitting.
- [6m] rolls from tummy to back -> yes | status: ok | reason: He can push up with his arms when he's on his tummy, so he definitely has the strength to roll over.
- [9m] gets to sitting position by herself -> yes | status: ok | reason: He uses his arms to push himself up from his tummy to get into a sitting position.
- [9m] moves things from one hand to her other hand -> yes | status: ok | reason: He often switches toys from one hand to the other while he's playing.
- [9m] sits without support -> no | status: ok | reason: He still needs to lean on his hands to stay steady when he sits.

Band summary:
  4m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  9m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67

Estimated developmental age for Movement / Physical: 9 months (chronological age 14 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 4 months ---
Q: Can Lucas chuckles when you try to make him laugh but not yet a full laugh right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He'll smile and make little sounds when we try, but it's not a big belly laugh.
Q: Can Lucas looks at you moves or makes sounds to get or keep you attention right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Lucas definitely looks at me and makes little sounds or moves to get my attention, especially when he wants something or wants to play.
Q: Can Lucas smiles on his own to get your attention right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely gives us a smile when he wants us to notice him or play with him.

--- Asking Social / Emotional milestones around 6 months ---
Q: Can Lucas knows familiar people right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely knows who his family is.
Q: Can Lucas laughs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He chuckles when we try to make him laugh, so I count that as laughing.
Q: Can Lucas likes to look at self in a mirror right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He often looks at his reflection, he seems curious about it.

--- Asking Social / Emotional milestones around 9 months ---
Q: Can Lucas is shy or clingy or fearful around strangers right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Yes, he's definitely shy socially, especially with people he doesn't know.
Q: Can Lucas looks when you call her name right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He usually turns his head when we call him, especially if it's one of us.
Q: Can Lucas reacts when you leave right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely reacts, sometimes he gets really upset, especially since he's shy and clingy.

Question / answer transcript:
- [4m] chuckles when you try to make him laugh but not yet a full laugh -> yes | status: ok | reason: He'll smile and make little sounds when we try, but it's not a big belly laugh.
- [4m] looks at you moves or makes sounds to get or keep you attention -> yes | status: ok | reason: Lucas definitely looks at me and makes little sounds or moves to get my attention, especially when he wants something or wants to play.
- [4m] smiles on his own to get your attention -> yes | status: ok | reason: He definitely gives us a smile when he wants us to notice him or play with him.
- [6m] knows familiar people -> yes | status: ok | reason: He definitely knows who his family is.
- [6m] laughs -> yes | status: ok | reason: He chuckles when we try to make him laugh, so I count that as laughing.
- [6m] likes to look at self in a mirror -> yes | status: ok | reason: He often looks at his reflection, he seems curious about it.
- [9m] is shy or clingy or fearful around strangers -> yes | status: ok | reason: Yes, he's definitely shy socially, especially with people he doesn't know.
- [9m] looks when you call her name -> yes | status: ok | reason: He usually turns his head when we call him, especially if it's one of us.
- [9m] reacts when you leave -> yes | status: ok | reason: He definitely reacts, sometimes he gets really upset, especially since he's shy and clingy.

Band summary:
  4m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  9m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Social / Emotional: 9 months (chronological age 14 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 4 months ---
Q: Can Lucas makes cooing sounds like ooooo or aahhh right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's pretty quiet, and his babbling is limited, but we do hear those soft cooing sounds every now and then.
Q: Can Lucas makes sounds back when you talk to him right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll sometimes make sounds back, but his babbling is still pretty limited overall.
Q: Can Lucas turns head towards the sound of your voice right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can hear me, but sometimes he's just focused on other things or gets a bit overwhelmed.

--- Asking Language / Communication milestones around 6 months ---
Q: Can Lucas blows raspberries or sticks tongue out and blows right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: No, he's not really doing that yet; he has very limited babbling right now.
Q: Can Lucas makes squealing noises right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He doesn't do it a lot, but sometimes when he's really happy or excited, a little squeal will come out.
Q: Can Lucas takes turns making sounds with you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll sometimes make a sound back when we talk to him, but it's not consistent.

--- Asking Language / Communication milestones around 9 months ---
Q: Can Lucas lifts arms up to be picked up right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can, but he's a bit shy so he doesn't always do it without some encouragement.
Q: Can Lucas makes a lot of different sounds like mamamamama and bababababa right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: His babbling is still pretty limited right now.

Question / answer transcript:
- [4m] makes cooing sounds like ooooo or aahhh -> sometimes | status: ok | reason: He's pretty quiet, and his babbling is limited, but we do hear those soft cooing sounds every now and then.
- [4m] makes sounds back when you talk to him -> sometimes | status: ok | reason: He'll sometimes make sounds back, but his babbling is still pretty limited overall.
- [4m] turns head towards the sound of your voice -> sometimes | status: ok | reason: He can hear me, but sometimes he's just focused on other things or gets a bit overwhelmed.
- [6m] blows raspberries or sticks tongue out and blows -> no | status: ok | reason: No, he's not really doing that yet; he has very limited babbling right now.
- [6m] makes squealing noises -> sometimes | status: ok | reason: He doesn't do it a lot, but sometimes when he's really happy or excited, a little squeal will come out.
- [6m] takes turns making sounds with you -> sometimes | status: ok | reason: He'll sometimes make a sound back when we talk to him, but it's not consistent.
- [9m] lifts arms up to be picked up -> sometimes | status: ok | reason: He can, but he's a bit shy so he doesn't always do it without some encouragement.
- [9m] makes a lot of different sounds like mamamamama and bababababa -> no | status: ok | reason: His babbling is still pretty limited right now.

Band summary:
  4m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  6m | total=3 | yes=0 | partial=2 | no=1 | yes_ratio=0.0
  9m | total=2 | yes=0 | partial=1 | no=1 | yes_ratio=0.0

Estimated developmental age for Language / Communication: 4 months (chronological age 14 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 4 months ---
Q: Can Lucas if hungry open mouth when she sees breast or bottle right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely knows what's coming when he's hungry and ready to eat.
Q: Can Lucas looks at her hands with interest right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He often watches his hands, especially when he's wiggling his fingers around.

--- Asking Cognitive / Adaptive milestones around 6 months ---
Q: Can Lucas closes lips to show she doesn't want more food right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's really good at showing us he's all done by keeping his mouth closed tight.
Q: Can Lucas puts things in her mouth to explore them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's still at that age where he puts everything in his mouth to see what it is.
Q: Can Lucas reaches to grab a toy she wants right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He definitely reaches for things to put them in his mouth, so if he wants a toy, he'll grab it.

--- Asking Cognitive / Adaptive milestones around 9 months ---
Q: Can Lucas bangs to things together right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves to bang his blocks together, especially to make noise.
Q: Can Lucas looks for objects when dropped out of sight right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll look for it sometimes, but not always when something drops.

Question / answer transcript:
- [4m] if hungry open mouth when she sees breast or bottle -> yes | status: ok | reason: He definitely knows what's coming when he's hungry and ready to eat.
- [4m] looks at her hands with interest -> yes | status: ok | reason: He often watches his hands, especially when he's wiggling his fingers around.
- [6m] closes lips to show she doesn't want more food -> yes | status: ok | reason: He's really good at showing us he's all done by keeping his mouth closed tight.
- [6m] puts things in her mouth to explore them -> yes | status: ok | reason: He's still at that age where he puts everything in his mouth to see what it is.
- [6m] reaches to grab a toy she wants -> yes | status: ok | reason: He definitely reaches for things to put them in his mouth, so if he wants a toy, he'll grab it.
- [9m] bangs to things together -> yes | status: ok | reason: He loves to bang his blocks together, especially to make noise.
- [9m] looks for objects when dropped out of sight -> sometimes | status: ok | reason: He'll look for it sometimes, but not always when something drops.

Band summary:
  4m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  6m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  9m | total=2 | yes=1 | partial=1 | no=0 | yes_ratio=0.5

Estimated developmental age for Cognitive / Adaptive: 6 months (chronological age 14 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
Summary: Weekly schedule built from category activity banks and true daily minute limits.
Daily time budget: 10
Target minutes by category: {'movement_and_physical': 10, 'social_and_emotional': 10, 'language_and_communication': 16, 'cognitive': 14}
Assigned minutes by category: {'movement_and_physical': 10, 'social_and_emotional': 8, 'language_and_communication': 22, 'cognitive': 5}

----------------------------------------------------------------------------------------------------
DAY_1 — total 10 min
----------------------------------------------------------------------------------------------------
- [Language / Communication] Sound Imitation Game (5 min)
  Goal: needs_special_support
  Instructions: Make simple sounds like 'ahh' or 'ooo' and encourage Lucas to imitate you. Use a happy tone and smile to engage him.
  Materials: None needed.
- [Movement / Physical] Sitting Up with Support (5 min)
  Goal: needs_special_support

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,9,5,needs_special_support,minimal / mild
1,Social / Emotional,9,5,needs_special_support,minimal / mild
2,Language / Communication,4,10,needs_special_support,moderate
3,Cognitive / Adaptive,6,8,needs_special_support,moderate

Focus areas:
  • Language / Communication
  • Cognitive / Adaptive
  • Movement / Physical

Daily activities:
1. Sound Imitation Game | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Make simple sounds like 'ahh' or 'ooo' and encourage Lucas to imitate you. Use a happy tone and smile to engage him.
2. Sitting Up with Support | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Place Lucas in a sitting position with pillows around him for support. Encourage him to reach for toys placed slightly out of reach to practice balance and sitting without support.
3. Sound Exploration with Toys | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Use toys that make sounds (like rattles or musical toys). Shake or press them to make sounds and encourage Lucas to mimic or respond.
4. Hand Transfer Game | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Give Lucas a small toy in one hand and encourage him to move it to the other hand. You can model this by doing it yourself first.
5. Follow the Sound | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Make a sound (like clapping or a simple word) and encourage Lucas to turn his head towards you. Reward him with smiles when he responds.

4. SUMMARY
This plan prioritizes Movement / Physical, Social / Emotional, Language / Communication for Lucas. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C08 | Emma | 2y 8m | Suspected childhood apraxia of speech
==============================================================================================================
Concerns: Very limited speech output, Uses gestures, gets frustrated, inconsistent sounds
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 4 month starting delay | Suspected childhood apraxia of speech may impact physical coordination related to speech production.
Social / Emotional: 6 month starting delay | Limited speech output and frustration may impact social interactions and emotional expression.
Language / Communication: 12 month starting delay | Suspected childhood apraxia of speech likely impacts expressive language skills.
Cognitive / Adaptive: 6 month starting delay | Limited speech output and frustration may impact cognitive/adaptive skills.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 24 months ---
Q: Can Emma eats with a spoon right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She handles a spoon fine for eating, her main challenges are with talking.
Q: Can Emma kicks a ball right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves playing outside and chasing balls around.
Q: Can Emma runs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, she's always zipping around the house and yard.

--- Asking Movement / Physical milestones around 30 months ---
Q: Can Emma jumps off the ground with both feet right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yeah, she's a busy bee and can run and kick, so jumping with both feet is no problem for her.
Q: Can Emma takes some clothes off by himself like loose pants or an open jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty good at pulling down her pants for potty time and slipping off her jacket.
Q: Can Emma turns book pages one at a time when you read to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can do that, she's usually pretty good with her hands.

--- Asking Movement / Physical milestones around 36 months ---
Q: Can Emma puts on some clothes by himself like loose pants or a jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty good at getting her pants on and can put on a jacket if it's open.
Q: Can Emma strings items together like large beads or macaroni right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's good with her hands, like turning pages and getting dressed.
Q: Can Emma uses a fork right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty good with it, especially since she can use a spoon already.

Question / answer transcript:
- [24m] eats with a spoon -> yes | status: ok | reason: She handles a spoon fine for eating, her main challenges are with talking.
- [24m] kicks a ball -> yes | status: ok | reason: She loves playing outside and chasing balls around.
- [24m] runs -> yes | status: ok | reason: Oh yes, she's always zipping around the house and yard.
- [30m] jumps off the ground with both feet -> yes | status: ok | reason: Oh yeah, she's a busy bee and can run and kick, so jumping with both feet is no problem for her.
- [30m] takes some clothes off by himself like loose pants or an open jacket -> yes | status: ok | reason: She's pretty good at pulling down her pants for potty time and slipping off her jacket.
- [30m] turns book pages one at a time when you read to her -> yes | status: ok | reason: She can do that, she's usually pretty good with her hands.
- [36m] puts on some clothes by himself like loose pants or a jacket -> yes | status: ok | reason: She's pretty good at getting her pants on and can put on a jacket if it's open.
- [36m] strings items together like large beads or macaroni -> yes | status: ok | reason: She's good with her hands, like turning pages and getting dressed.
- [36m] uses a fork -> yes | status: ok | reason: She's pretty good with it, especially since she can use a spoon already.

Band summary:
  24m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  30m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  36m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Movement / Physical: 36 months (chronological age 32 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 18 months ---
Q: Can Emma helps you dress him by pushing the arm through the sleeve or lifting up the foot right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Her physical development is on track; it's mostly her speech that we're working on.
Q: Can Emma looks at a few pages in a book with you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She enjoys looking at the pictures and pointing things out.
Q: Can Emma moves away from you but looks to make sure you are close by right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's good at exploring, but always checks to make sure I'm still close by.

--- Asking Social / Emotional milestones around 24 months ---
Q: Can Emma looks at your face to see how to react in a new situation right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often looks at my face, especially if she's unsure or it's new, to see how I'm reacting.
Q: Can Emma notices when others are hurt or upset like pausing or looking sad when someone is crying right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very observant and definitely notices if someone is upset, sometimes she'll even try to pat them.

--- Asking Social / Emotional milestones around 30 months ---
Q: Can Emma follos simple routines when told like helping to pick up toys when you say it is clean up time right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask her to do, like when it's time to put toys away.
Q: Can Emma plays next to other children and sometimes plays with them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves being around other kids and will join in their play, even if she's mostly using gestures to communicate.
Q: Can Emma shows you what she can do by saying look at me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: Her speech is very limited; she mostly uses gestures to show things.

Question / answer transcript:
- [18m] helps you dress him by pushing the arm through the sleeve or lifting up the foot -> yes | status: ok | reason: Her physical development is on track; it's mostly her speech that we're working on.
- [18m] looks at a few pages in a book with you -> yes | status: ok | reason: She enjoys looking at the pictures and pointing things out.
- [18m] moves away from you but looks to make sure you are close by -> yes | status: ok | reason: She's good at exploring, but always checks to make sure I'm still close by.
- [24m] looks at your face to see how to react in a new situation -> yes | status: ok | reason: She often looks at my face, especially if she's unsure or it's new, to see how I'm reacting.
- [24m] notices when others are hurt or upset like pausing or looking sad when someone is crying -> yes | status: ok | reason: She's very observant and definitely notices if someone is upset, sometimes she'll even try to pat them.
- [30m] follos simple routines when told like helping to pick up toys when you say it is clean up time -> yes | status: ok | reason: She understands what we ask her to do, like when it's time to put toys away.
- [30m] plays next to other children and sometimes plays with them -> yes | status: ok | reason: She loves being around other kids and will join in their play, even if she's mostly using gestures to communicate.
- [30m] shows you what she can do by saying look at me -> no | status: ok | reason: Her speech is very limited; she mostly uses gestures to show things.

Band summary:
  18m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  24m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  30m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67

Estimated developmental age for Social / Emotional: 30 months (chronological age 32 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 15 months ---
Q: Can Emma follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Her understanding is generally good, it's the talking part she struggles with. Gestures really help her.
Q: Can Emma looks at a ffamiliar object when you name it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, she definitely knows what things are when we say them. Her understanding is pretty good.
Q: Can Emma points to ask for something or to get help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Because her speech is limited, she often points to show us what she wants or needs help with.

--- Asking Language / Communication milestones around 18 months ---
Q: Can Emma follows one step directions without any gestures like giving you the toy when you say give it to me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands simple directions, even if we don't use gestures.
Q: Can Emma tries to say three or more words besides mama or dada right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: Her speech output is very limited beyond 'mama' and 'dada', and she struggles with inconsistent sounds.

--- Asking Language / Communication milestones around 24 months ---
Q: Can Emma points at least two body parts when you ask her to show you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask her to do and points really well, even though she doesn't use many words.
Q: Can Emma points to things in a book when you ask like where is the bear right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we're asking for and can point to other things when we name them.
Q: Can Emma says at least two words together like more milk right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: Her speech is very limited right now, she's not putting words together yet.

Question / answer transcript:
- [15m] follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy -> yes | status: ok | reason: Her understanding is generally good, it's the talking part she struggles with. Gestures really help her.
- [15m] looks at a ffamiliar object when you name it -> yes | status: ok | reason: Oh yes, she definitely knows what things are when we say them. Her understanding is pretty good.
- [15m] points to ask for something or to get help -> yes | status: ok | reason: Because her speech is limited, she often points to show us what she wants or needs help with.
- [18m] follows one step directions without any gestures like giving you the toy when you say give it to me -> yes | status: ok | reason: She understands simple directions, even if we don't use gestures.
- [18m] tries to say three or more words besides mama or dada -> no | status: ok | reason: Her speech output is very limited beyond 'mama' and 'dada', and she struggles with inconsistent sounds.
- [24m] points at least two body parts when you ask her to show you -> yes | status: ok | reason: She understands what we ask her to do and points really well, even though she doesn't use many words.
- [24m] points to things in a book when you ask like where is the bear -> yes | status: ok | reason: She understands what we're asking for and can point to other things when we name them.
- [24m] says at least two words together like more milk -> no | status: ok | reason: Her speech is very limited right now, she's not putting words together yet.

Band summary:
  15m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=2 | yes=1 | partial=0 | no=1 | yes_ratio=0.5
  24m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67

Estimated developmental age for Language / Communication: 24 months (chronological age 32 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 18 months ---
Q: Can Emma copies you doing chores like sweeping with a broom right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's always watching what I do and loves to try to help out.
Q: Can Emma plays with toys in a simple way like pushing a toy car right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, she loves pushing her cars and trains around.

--- Asking Cognitive / Adaptive milestones around 24 months ---
Q: Can Emma holds something in one hand while using the other hand for example holding a container and taking the lid off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can open her snack containers and play-doh tubs just fine.
Q: Can Emma plays with more than one toy at the same time like putting toy food on a toy plate right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves playing 'restaurant' or 'cooking' and putting food on plates.
Q: Can Emma tries to use switches or knobs or buttons on a toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves pushing buttons on her activity toys and can turn them on and off.

--- Asking Cognitive / Adaptive milestones around 30 months ---
Q: Can Emma follows two step instructions like put the toy down and close the door right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we say, even if she can't always say much back.
Q: Can Emma shows she knows at least one color like pointing to a red crayon when you ask which one is red right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can point to a couple of colors when we ask, even though she can't say the names yet.
Q: Can Emma shows simple problem solving skills like standing on a small stool to reach something right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty good at figuring out how to get to things she wants, like treats on the counter.

Question / answer transcript:
- [18m] copies you doing chores like sweeping with a broom -> yes | status: ok | reason: She's always watching what I do and loves to try to help out.
- [18m] plays with toys in a simple way like pushing a toy car -> yes | status: ok | reason: Oh yes, she loves pushing her cars and trains around.
- [24m] holds something in one hand while using the other hand for example holding a container and taking the lid off -> yes | status: ok | reason: She can open her snack containers and play-doh tubs just fine.
- [24m] plays with more than one toy at the same time like putting toy food on a toy plate -> yes | status: ok | reason: She loves playing 'restaurant' or 'cooking' and putting food on plates.
- [24m] tries to use switches or knobs or buttons on a toy -> yes | status: ok | reason: She loves pushing buttons on her activity toys and can turn them on and off.
- [30m] follows two step instructions like put the toy down and close the door -> yes | status: ok | reason: She understands what we say, even if she can't always say much back.
- [30m] shows she knows at least one color like pointing to a red crayon when you ask which one is red -> yes | status: ok | reason: She can point to a couple of colors when we ask, even though she can't say the names yet.

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,36,0,no_special_support,minimal / mild
1,Social / Emotional,30,2,no_special_support,minimal / mild
2,Language / Communication,24,8,needs_special_support,moderate
3,Cognitive / Adaptive,30,2,no_special_support,minimal / mild

Focus areas:
  • Language / Communication

Daily activities:
1. Body Part Pointing | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Ask Emma to point to different body parts on herself and on a doll or stuffed animal. Start with familiar parts like 'nose' and 'eyes'.
2. Two-Word Phrases | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Use toys or snacks to encourage Emma to say two-word phrases like 'more juice' or 'big truck'. Model the phrases and wait for her to imitate.
3. Gesture Game | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Play a game where you and Emma take turns using gestures to communicate. For example, blowing a kiss or nodding yes. Encourage her to imitate your gestures.
4. Book Exploration | Language / Communication | 7 min
   Goal: needs_special_support
   Description: Choose a picture book and ask Emma to point to specific items, like 'Where is the bear?' Encourage her to make sounds or say words related to the pictures.
5. Naming Objects in Books | Language / Communication | 10 min
   Goal: needs_special_support
   Description: Look at a book together and point to different objects, asking Emma 'What is this?' Encourage her to name the objects or make sounds related to them.

4. SUMMARY
This plan prioritizes Language / Communication for Emma. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C09 | Zain | 4 years | Attention and self-regulation concerns (possible ADHD)
==============================================================================================================
Concerns: Very active, impulsive, Big emotional reactions, interrupts, difficulty following routines, social interest intact
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 6 month starting delay | The child's impulsivity and emotional reactions may hinder their physical coordination and control.
Social / Emotional: 6 month starting delay | Attention and self-regulation concerns may impact social-emotional skills.
Language / Communication: 6 month starting delay | Attention and self-regulation concerns may impact language processing and communication skills.
Cognitive / Adaptive: 6 month starting delay | Attention and self-regulation concerns may impact cognitive/adaptive functioning.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 30 months ---
Q: Can Zain jumps off the ground with both feet right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he's always running and jumping, he's very active.
Q: Can Zain takes some clothes off by himself like loose pants or an open jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's definitely able to pull off loose pants or an open jacket when he wants to.
Q: Can Zain turns book pages one at a time when you read to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can, but often he's too impulsive and just flips through several pages at once instead of one by one.

--- Asking Movement / Physical milestones around 36 months ---
Q: Can Zain puts on some clothes by himself like loose pants or a jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He knows how to put them on, but it can take a while because he gets distracted easily.
Q: Can Zain strings items together like large beads or macaroni right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it, but he often gets distracted and doesn't always stick with it.
Q: Can Zain uses a fork right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He knows how to use it, but sometimes he gets too distracted or impulsive and just uses his hands instead.

--- Asking Movement / Physical milestones around 48 months ---
Q: Can Zain catches a large ball most of the times right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's very active and tries hard, but sometimes his impulsiveness makes him miss the ball, or he gets distracted.
Q: Can Zain holds crayon or pencil between fingers and thumb not fist right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can hold it with his fingers, but sometimes he still uses his whole hand, especially if he's rushing.
Q: Can Zain serves herself food or pours water with adult supervision right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it, but he's impulsive and sometimes makes a mess even when I'm right there watching.

Question / answer transcript:
- [30m] jumps off the ground with both feet -> yes | status: ok | reason: Oh yes, he's always running and jumping, he's very active.
- [30m] takes some clothes off by himself like loose pants or an open jacket -> yes | status: ok | reason: He's definitely able to pull off loose pants or an open jacket when he wants to.
- [30m] turns book pages one at a time when you read to her -> sometimes | status: ok | reason: He can, but often he's too impulsive and just flips through several pages at once instead of one by one.
- [36m] puts on some clothes by himself like loose pants or a jacket -> yes | status: ok | reason: He knows how to put them on, but it can take a while because he gets distracted easily.
- [36m] strings items together like large beads or macaroni -> sometimes | status: ok | reason: He can do it, but he often gets distracted and doesn't always stick with it.
- [36m] uses a fork -> sometimes | status: ok | reason: He knows how to use it, but sometimes he gets too distracted or impulsive and just uses his hands instead.
- [48m] catches a large ball most of the times -> sometimes | status: ok | reason: He's very active and tries hard, but sometimes his impulsiveness makes him miss the ball, or he gets distracted.
- [48m] holds crayon or pencil between fingers and thumb not fist -> sometimes | status: ok | reason: He can hold it with his fingers, but sometimes he still uses his whole hand, especially if he's rushing.
- [48m] serves herself food or pours water with adult supervision -> sometimes | status: ok | reason: He can do it, but he's impulsive and sometimes makes a mess even when I'm right there watching.

Band summary:
  30m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  36m | total=3 | yes=1 | partial=2 | no=0 | yes_ratio=0.33
  48m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0

Estimated developmental age for Movement / Physical: 30 months (chronological age 48 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 30 months ---
Q: Can Zain follos simple routines when told like helping to pick up toys when you say it is clean up time right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He really struggles with attention and self-regulation, so it's not a given.
Q: Can Zain plays next to other children and sometimes plays with them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Zain is interested in other kids and wants to be near them, even if he's a bit impulsive during play.
Q: Can Zain shows you what she can do by saying look at me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Zain loves showing us things and will definitely say 'look at me!' to get our attention, especially since he interrupts a lot.

--- Asking Social / Emotional milestones around 36 months ---
Q: Can Zain calms down within 10 minutes after you leave her like at childcare drop off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: When she gets really worked up, especially at drop-off, it usually takes her a lot longer than that to settle down because of her big emotional reactions.
Q: Can Zain notices other children and joins them to play right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He has social interest and definitely notices other kids; he'll jump right in.

--- Asking Social / Emotional milestones around 48 months ---
Q: Can Zain asks to go play with children if none are around like can I play with Alex right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Zain loves playing with other kids and will often ask for specific friends even when they're not around.
Q: Can Zain avoids danger like not jumping from tall heights at the playgroung right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's so impulsive, he often doesn't think about safety before acting, even though he knows better sometimes.
Q: Can Zain changes behavior based on where she is like place of worship or library or playground right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She knows she should, but her energy and impulsivity make it hard to actually do it consistently.

Question / answer transcript:
- [30m] follos simple routines when told like helping to pick up toys when you say it is clean up time -> sometimes | status: ok | reason: He really struggles with attention and self-regulation, so it's not a given.
- [30m] plays next to other children and sometimes plays with them -> yes | status: ok | reason: Zain is interested in other kids and wants to be near them, even if he's a bit impulsive during play.
- [30m] shows you what she can do by saying look at me -> yes | status: ok | reason: Zain loves showing us things and will definitely say 'look at me!' to get our attention, especially since he interrupts a lot.
- [36m] calms down within 10 minutes after you leave her like at childcare drop off -> no | status: ok | reason: When she gets really worked up, especially at drop-off, it usually takes her a lot longer than that to settle down because of her big emotional reactions.
- [36m] notices other children and joins them to play -> yes | status: ok | reason: He has social interest and definitely notices other kids; he'll jump right in.
- [48m] asks to go play with children if none are around like can I play with Alex -> yes | status: ok | reason: Zain loves playing with other kids and will often ask for specific friends even when they're not around.
- [48m] avoids danger like not jumping from tall heights at the playgroung -> sometimes | status: ok | reason: He's so impulsive, he often doesn't think about safety before acting, even though he knows better sometimes.
- [48m] changes behavior based on where she is like place of worship or library or playground -> sometimes | status: ok | reason: She knows she should, but her energy and impulsivity make it hard to actually do it consistently.

Band summary:
  30m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  36m | total=2 | yes=1 | partial=0 | no=1 | yes_ratio=0.5
  48m | total=3 | yes=1 | partial=2 | no=0 | yes_ratio=0.33

Estimated developmental age for Social / Emotional: 30 months (chronological age 48 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 30 months ---
Q: Can Zain name things in a book when you point and ask what is this right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He knows many things, but his attention often wanders when we try to read a book.
Q: Can Zain say two or more words toghether with one action word like doggie run right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's four years old and talks, even if he interrupts a lot.
Q: Can Zain says about 50 words right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's 4 years old and talks in sentences, so he definitely knows more than 50 words.

--- Asking Language / Communication milestones around 36 months ---
Q: Can Zain ask who or what or where or why questions like where is mommy or where is daddy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He asks us where things and people are often.
Q: Can Zain says first name when asked right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He knows his own name well, and he can usually answer when you talk directly to him.
Q: Can Zain says what action is happening in a picture or book when asked like running or eating or playing right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He knows action words, but his attention can make him inconsistent when looking at books.

--- Asking Language / Communication milestones around 48 months ---
Q: Can Zain answers simple questions like what is a coat for or what is crayon for right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He usually knows the answers, but his attention can wander, so he doesn't always respond consistently.
Q: Can Zain says sentences with four or more words right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He talks a lot and asks all sorts of questions, many of them are longer than just a few words.
Q: Can Zain says some words from a song or story or nursery rhyme right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves to sing along to his favorite songs and can tell us parts of his favorite stories.

Question / answer transcript:
- [30m] name things in a book when you point and ask what is this -> sometimes | status: ok | reason: He knows many things, but his attention often wanders when we try to read a book.
- [30m] say two or more words toghether with one action word like doggie run -> yes | status: ok | reason: He's four years old and talks, even if he interrupts a lot.
- [30m] says about 50 words -> yes | status: ok | reason: He's 4 years old and talks in sentences, so he definitely knows more than 50 words.
- [36m] ask who or what or where or why questions like where is mommy or where is daddy -> yes | status: ok | reason: He asks us where things and people are often.
- [36m] says first name when asked -> yes | status: ok | reason: He knows his own name well, and he can usually answer when you talk directly to him.
- [36m] says what action is happening in a picture or book when asked like running or eating or playing -> sometimes | status: ok | reason: He knows action words, but his attention can make him inconsistent when looking at books.
- [48m] answers simple questions like what is a coat for or what is crayon for -> sometimes | status: ok | reason: He usually knows the answers, but his attention can wander, so he doesn't always respond consistently.
- [48m] says sentences with four or more words -> yes | status: ok | reason: He talks a lot and asks all sorts of questions, many of them are longer than just a few words.
- [48m] says some words from a song or story or nursery rhyme -> yes | status: ok | reason: He loves to sing along to his favorite songs and can tell us parts of his favorite stories.

Band summary:
  30m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  36m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  48m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Language / Communication: 48 months (chronological age 48 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 30 months ---
Q: Can Zain follows two step instructions like put the toy down and close the door right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: It really depends on his focus; he often gets sidetracked or only does the first part.
Q: Can Zain shows she knows at least one color like pointing to a red crayon when you ask which one is red right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He knows some colors, but his attention and impulsivity mean he doesn't always show it when asked.
Q: Can Zain shows simple problem solving skills like standing on a small stool to reach something right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very active and impulsive, so if he wants something, he'll find a way to get it.

--- Asking Cognitive / Adaptive milestones around 36 months ---
Q: Can Zain avoids touching hot objects like the stove when you warn her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's very impulsive, so even when we warn him, he sometimes still goes to touch things.
Q: Can Zain draws a circle when you show her how right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it when he focuses, but sometimes he rushes or gets distracted.

--- Asking Cognitive / Adaptive milestones around 48 months ---
Q: Can Zain draws a person with three or more body parts right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can definitely do it, but his attention issues mean he often gets distracted before finishing or only does a very quick version.
Q: Can Zain names a few colors or items right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He knows some, but it's hard to get him to focus on it for long enough to name a few.
Q: Can Zain tell what comes next in a well known story right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He knows some stories really well, but sometimes he just gets distracted or loses focus when we're reading.

Question / answer transcript:

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,30,18,needs_special_support,moderate
1,Social / Emotional,30,18,needs_special_support,moderate
2,Language / Communication,48,0,no_special_support,minimal / mild
3,Cognitive / Adaptive,30,18,needs_special_support,moderate

Focus areas:
  • Movement / Physical
  • Social / Emotional
  • Cognitive / Adaptive

Daily activities:
1. Clean-Up Time Together | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: At a designated clean-up time, encourage Zain to help pick up toys. Use a timer for 5 minutes and make it a fun challenge to see how many toys can be picked up together.
2. Jumping Fun | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Create a safe space and encourage Zain to jump off a low surface (like a step or a cushion) using both feet. Start with a small height and gradually increase as he gains confidence.
3. Look at Me Game | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: Take turns with Zain to show fun actions or silly faces. Encourage him to say 'look at me' when he does something fun. This promotes shared attention and social engagement.
4. Page Turner | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Read a picture book together and encourage Zain to turn the pages one at a time. Use a book with thicker pages for easier handling.
5. Emotion Charades | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: Take turns acting out different emotions (happy, sad, surprised) and have Zain guess which emotion it is. This encourages emotional recognition and expression.

4. SUMMARY
This plan prioritizes Movement / Physical, Social / Emotional, Cognitive / Adaptive for Zain. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C10 | Isla | 3y 8m | SYNGAP1-related disorder
==============================================================================================================
Concerns: Delayed speech and balance, Attention issues, clumsy gait, limited pretend play
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 12 month starting delay | The child's diagnosis and concerns suggest significant impact on movement and physical skills.
Social / Emotional: 12 month starting delay | The child's SYNGAP1-related disorder and concerns about attention and play suggest a significant impact on social/emotional development.
Language / Communication: 18 month starting delay | The child's SYNGAP1-related disorder and concerns about delayed speech suggest a significant delay in language development.
Cognitive / Adaptive: 12 month starting delay | Cognitive concerns related to SYNGAP1 and attention issues suggest a significant delay in adaptive functioning.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 24 months ---
Q: Can Isla eats with a spoon right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can use it, but it's often messy and she sometimes gets distracted easily.
Q: Can Isla kicks a ball right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries to kick, but with her balance issues and clumsy gait, it's not consistent and she often struggles.
Q: Can Isla runs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can get going fast, but it's more of a clumsy shuffle than a smooth run, and she often loses her balance.

--- Asking Movement / Physical milestones around 30 months ---
Q: Can Isla jumps off the ground with both feet right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She attempts it, and sometimes gets both feet off the ground, but her balance issues make it challenging for her.
Q: Can Isla takes some clothes off by himself like loose pants or an open jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can get them off herself when they're really loose, but often needs a prompt or gets a bit stuck.
Q: Can Isla turns book pages one at a time when you read to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She struggles with focus, so it's not always one page at a time.

--- Asking Movement / Physical milestones around 36 months ---
Q: Can Isla puts on some clothes by himself like loose pants or a jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can sometimes get them on, but it's hard for her with her balance.
Q: Can Isla strings items together like large beads or macaroni right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can string a few, but her attention often wanders before she finishes.
Q: Can Isla uses a fork right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can use a spoon sometimes, and it's similar with a fork; she tries but it's not always successful.

Question / answer transcript:
- [24m] eats with a spoon -> sometimes | status: ok | reason: She can use it, but it's often messy and she sometimes gets distracted easily.
- [24m] kicks a ball -> sometimes | status: ok | reason: She tries to kick, but with her balance issues and clumsy gait, it's not consistent and she often struggles.
- [24m] runs -> sometimes | status: ok | reason: She can get going fast, but it's more of a clumsy shuffle than a smooth run, and she often loses her balance.
- [30m] jumps off the ground with both feet -> sometimes | status: ok | reason: She attempts it, and sometimes gets both feet off the ground, but her balance issues make it challenging for her.
- [30m] takes some clothes off by himself like loose pants or an open jacket -> sometimes | status: ok | reason: She can get them off herself when they're really loose, but often needs a prompt or gets a bit stuck.
- [30m] turns book pages one at a time when you read to her -> sometimes | status: ok | reason: She struggles with focus, so it's not always one page at a time.
- [36m] puts on some clothes by himself like loose pants or a jacket -> sometimes | status: ok | reason: She can sometimes get them on, but it's hard for her with her balance.
- [36m] strings items together like large beads or macaroni -> sometimes | status: ok | reason: She can string a few, but her attention often wanders before she finishes.
- [36m] uses a fork -> sometimes | status: ok | reason: She can use a spoon sometimes, and it's similar with a fork; she tries but it's not always successful.

Band summary:
  24m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  30m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  36m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0

Estimated developmental age for Movement / Physical: 24 months (chronological age 44 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 24 months ---
Q: Can Isla looks at your face to see how to react in a new situation right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She often gets distracted, especially in new situations, so she doesn't always look to me.
Q: Can Isla notices when others are hurt or upset like pausing or looking sad when someone is crying right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She does notice sometimes if someone is clearly upset, but it's not always consistent.

--- Asking Social / Emotional milestones around 30 months ---
Q: Can Isla follos simple routines when told like helping to pick up toys when you say it is clean up time right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: She knows the routine, but with her attention issues, I usually have to guide her to get started.
Q: Can Isla plays next to other children and sometimes plays with them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She often plays near other kids, and sometimes she'll briefly interact with them, but it's not consistent or for very long.
Q: Can Isla shows you what she can do by saying look at me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She has delayed speech and isn't using phrases like 'look at me' to get our attention for showing things.

--- Asking Social / Emotional milestones around 36 months ---
Q: Can Isla calms down within 10 minutes after you leave her like at childcare drop off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: She has attention issues and often needs the teacher to help guide her to calm down after I leave.
Q: Can Isla notices other children and joins them to play right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She will sometimes go over and engage with other kids, but it's not always consistent.

Question / answer transcript:
- [24m] looks at your face to see how to react in a new situation -> sometimes | status: ok | reason: She often gets distracted, especially in new situations, so she doesn't always look to me.
- [24m] notices when others are hurt or upset like pausing or looking sad when someone is crying -> sometimes | status: ok | reason: She does notice sometimes if someone is clearly upset, but it's not always consistent.
- [30m] follos simple routines when told like helping to pick up toys when you say it is clean up time -> with_help | status: ok | reason: She knows the routine, but with her attention issues, I usually have to guide her to get started.
- [30m] plays next to other children and sometimes plays with them -> sometimes | status: ok | reason: She often plays near other kids, and sometimes she'll briefly interact with them, but it's not consistent or for very long.
- [30m] shows you what she can do by saying look at me -> no | status: ok | reason: She has delayed speech and isn't using phrases like 'look at me' to get our attention for showing things.
- [36m] calms down within 10 minutes after you leave her like at childcare drop off -> with_help | status: ok | reason: She has attention issues and often needs the teacher to help guide her to calm down after I leave.
- [36m] notices other children and joins them to play -> sometimes | status: ok | reason: She will sometimes go over and engage with other kids, but it's not always consistent.

Band summary:
  24m | total=2 | yes=0 | partial=2 | no=0 | yes_ratio=0.0
  30m | total=3 | yes=0 | partial=2 | no=1 | yes_ratio=0.0
  36m | total=2 | yes=0 | partial=2 | no=0 | yes_ratio=0.0

Estimated developmental age for Social / Emotional: 24 months (chronological age 44 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 18 months ---
Q: Can Isla follows one step directions without any gestures like giving you the toy when you say give it to me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: It really depends on if she's focused at the moment.
Q: Can Isla tries to say three or more words besides mama or dada right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She has a few words she tries to use besides mama and dada.

--- Asking Language / Communication milestones around 24 months ---
Q: Can Isla points at least two body parts when you ask her to show you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She knows her nose and mouth really well when I ask.
Q: Can Isla points to things in a book when you ask like where is the bear right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can point to body parts when asked, so she can usually find things in a book too.
Q: Can Isla says at least two words together like more milk right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She has some words and occasionally puts two together, but it's not consistent yet due to her delayed speech.

--- Asking Language / Communication milestones around 30 months ---
Q: Can Isla name things in a book when you point and ask what is this right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can say some words and knows what things are in books, but her speech is delayed so she doesn't always name them.
Q: Can Isla say two or more words toghether with one action word like doggie run right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She's starting to put a few words together, and sometimes she'll add an action when she's really focused.
Q: Can Isla says about 50 words right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's picked up quite a few individual words, even if her overall speech is still behind for her age.

Question / answer transcript:
- [18m] follows one step directions without any gestures like giving you the toy when you say give it to me -> sometimes | status: ok | reason: It really depends on if she's focused at the moment.
- [18m] tries to say three or more words besides mama or dada -> yes | status: ok | reason: She has a few words she tries to use besides mama and dada.
- [24m] points at least two body parts when you ask her to show you -> yes | status: ok | reason: She knows her nose and mouth really well when I ask.
- [24m] points to things in a book when you ask like where is the bear -> yes | status: ok | reason: She can point to body parts when asked, so she can usually find things in a book too.
- [24m] says at least two words together like more milk -> sometimes | status: ok | reason: She has some words and occasionally puts two together, but it's not consistent yet due to her delayed speech.
- [30m] name things in a book when you point and ask what is this -> sometimes | status: ok | reason: She can say some words and knows what things are in books, but her speech is delayed so she doesn't always name them.
- [30m] say two or more words toghether with one action word like doggie run -> sometimes | status: ok | reason: She's starting to put a few words together, and sometimes she'll add an action when she's really focused.
- [30m] says about 50 words -> yes | status: ok | reason: She's picked up quite a few individual words, even if her overall speech is still behind for her age.

Band summary:
  18m | total=2 | yes=1 | partial=1 | no=0 | yes_ratio=0.5
  24m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  30m | total=3 | yes=1 | partial=2 | no=0 | yes_ratio=0.33

Estimated developmental age for Language / Communication: 24 months (chronological age 44 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 24 months ---
Q: Can Isla holds something in one hand while using the other hand for example holding a container and taking the lid off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She struggles with coordinating both hands, but sometimes she can manage.
Q: Can Isla plays with more than one toy at the same time like putting toy food on a toy plate right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She has limited pretend play and attention issues, so she might do it briefly, but not consistently.
Q: Can Isla tries to use switches or knobs or buttons on a toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She tries to press buttons or flip switches on toys, especially if they make a sound or light up, but sometimes she loses interest quickly.

--- Asking Cognitive / Adaptive milestones around 30 months ---
Q: Can Isla follows two step instructions like put the toy down and close the door right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: Her attention makes it hard for her to follow both steps consistently.
Q: Can Isla shows she knows at least one color like pointing to a red crayon when you ask which one is red right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can sometimes point to one, but her attention makes it tricky.
Q: Can Isla shows simple problem solving skills like standing on a small stool to reach something right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She might try to get something high up, but her balance issues mean she doesn't always manage it or needs to be quick.

--- Asking Cognitive / Adaptive milestones around 36 months ---
Q: Can Isla avoids touching hot objects like the stove when you warn her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She knows what 'hot' is, but her attention issues mean she doesn't always react to a warning.
Q: Can Isla draws a circle when you show her how right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She can try to copy it when we show her, but it's not always a clear circle.

Question / answer transcript:
- [24m] holds something in one hand while using the other hand for example holding a container and taking the lid off -> sometimes | status: ok | reason: She struggles with coordinating both hands, but sometimes she can manage.
- [24m] plays with more than one toy at the same time like putting toy food on a toy plate -> sometimes | status: ok | reason: She has limited pretend play and attention issues, so she might do it briefly, but not consistently.
- [24m] tries to use switches or knobs or buttons on a toy -> sometimes | status: ok | reason: She tries to press buttons or flip switches on toys, especially if they make a sound or light up, but sometimes she loses interest quickly.
- [30m] follows two step instructions like put the toy down and close the door -> sometimes | status: ok | reason: Her attention makes it hard for her to follow both steps consistently.

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,24,20,needs_special_support,significant
1,Social / Emotional,24,20,needs_special_support,significant
2,Language / Communication,24,20,needs_special_support,significant
3,Cognitive / Adaptive,24,20,needs_special_support,significant

Focus areas:
  • Movement / Physical
  • Social / Emotional
  • Language / Communication

Daily activities:
1. Body Part Pointing | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Ask Isla to point to specific body parts on herself or on a doll, like 'Where's your nose?' or 'Show me the doll's eyes.'
2. Spoon Practice | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Provide Isla with a bowl of soft food and a spoon. Encourage her to scoop and eat the food using the spoon. Offer assistance as needed to help her practice holding the spoon correctly.
3. Two-Word Phrases | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Encourage Isla to use two-word phrases by modeling them. For example, say 'More juice' or 'Big truck' and encourage her to repeat after you.
4. Ball Kicking | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Set up a soft ball in an open space. Encourage Isla to kick the ball with her foot. You can demonstrate and then take turns kicking the ball back and forth.
5. Gesture Game | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Play a game where you model different gestures like blowing a kiss, nodding, or waving. Encourage Isla to imitate these gestures.

4. SUMMARY
This plan prioritizes Movement / Physical, Social / Emotional, Language / Communication for Isla. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

--------------------------------------------------------------------------------------------------------------
Batch complete. Waiting 120 seconds before next batch...
--------------------------------------------------------------------------------------------------------------

==============================================================================================================
RUNNING BATCH 3 | cases 11 to 14 of 14
==============================================================================================================

==============================================================================================================
STARTING C11 | Aria | 20 months | No diagnosis
==============================================================================================================
Concerns: Only ~10 words, very active, good eye contact, understands well
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 2 month starting delay | The child is active and has good eye contact, suggesting typical movement skills with slight delay.
Social / Emotional: 0 month starting delay | The child shows good social engagement and understanding.
Language / Communication: 2 month starting delay | Child is active and understands well, indicating slight delay in expressive language.
Cognitive / Adaptive: 0 month starting delay | The child shows good understanding and engagement, indicating typical cognitive development.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 12 months ---
Q: Can Aria drinks from a cup without a lid as you hold it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's 20 months and doesn't have any issues drinking when I hold the cup for her.
Q: Can Aria picks things up between thumb and pointer finger like small bits of food right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's good at picking up her cheerios and little bits of food herself.
Q: Can Aria pulls up to stand right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very active and has been pulling up for a long time now.

--- Asking Movement / Physical milestones around 15 months ---
Q: Can Aria takes a few steps on her own right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yeah, she's all over the place!
Q: Can Aria uses fingers to feed herself some food right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's good at picking up little pieces of food herself.

--- Asking Movement / Physical milestones around 18 months ---
Q: Can Aria climbs on and off a couch or chair without help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very active and always climbing up and down from the couch.
Q: Can Aria drinks from a cup without a lid and may spill sometimes right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She drinks from a regular cup and definitely spills sometimes, that's just how it goes!
Q: Can Aria feeds himself with his fingers right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, she totally feeds herself with her fingers.

Question / answer transcript:
- [12m] drinks from a cup without a lid as you hold it -> yes | status: ok | reason: She's 20 months and doesn't have any issues drinking when I hold the cup for her.
- [12m] picks things up between thumb and pointer finger like small bits of food -> yes | status: ok | reason: She's good at picking up her cheerios and little bits of food herself.
- [12m] pulls up to stand -> yes | status: ok | reason: She's very active and has been pulling up for a long time now.
- [15m] takes a few steps on her own -> yes | status: ok | reason: Oh yeah, she's all over the place!
- [15m] uses fingers to feed herself some food -> yes | status: ok | reason: She's good at picking up little pieces of food herself.
- [18m] climbs on and off a couch or chair without help -> yes | status: ok | reason: She's very active and always climbing up and down from the couch.
- [18m] drinks from a cup without a lid and may spill sometimes -> yes | status: ok | reason: She drinks from a regular cup and definitely spills sometimes, that's just how it goes!
- [18m] feeds himself with his fingers -> yes | status: ok | reason: Oh yes, she totally feeds herself with her fingers.

Band summary:
  12m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  15m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Movement / Physical: 18 months (chronological age 20 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 15 months ---
Q: Can Aria claps when excited right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She gets super excited and claps her hands.
Q: Can Aria copies other children while playing like taking toys out of a container when another child does right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She watches other kids closely and often tries to do what they do.
Q: Can Aria hugs stuffed doll or other toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often gives her teddy bear big squeezes.

--- Asking Social / Emotional milestones around 18 months ---
Q: Can Aria helps you dress him by pushing the arm through the sleeve or lifting up the foot right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very active and understands what we're asking her to do, so she helps.
Q: Can Aria looks at a few pages in a book with you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands well and makes good eye contact, so she'll look at books with us.
Q: Can Aria moves away from you but looks to make sure you are close by right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very active and loves to explore, but she always glances back to make sure we're still there.

--- Asking Social / Emotional milestones around 24 months ---
Q: Can Aria looks at your face to see how to react in a new situation right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often looks at my face to see if things are okay, especially if it's something new.
Q: Can Aria notices when others are hurt or upset like pausing or looking sad when someone is crying right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very observant and often looks at faces, so she notices when someone is sad or upset.

Question / answer transcript:
- [15m] claps when excited -> yes | status: ok | reason: She gets super excited and claps her hands.
- [15m] copies other children while playing like taking toys out of a container when another child does -> yes | status: ok | reason: She watches other kids closely and often tries to do what they do.
- [15m] hugs stuffed doll or other toy -> yes | status: ok | reason: She often gives her teddy bear big squeezes.
- [18m] helps you dress him by pushing the arm through the sleeve or lifting up the foot -> yes | status: ok | reason: She's very active and understands what we're asking her to do, so she helps.
- [18m] looks at a few pages in a book with you -> yes | status: ok | reason: She understands well and makes good eye contact, so she'll look at books with us.
- [18m] moves away from you but looks to make sure you are close by -> yes | status: ok | reason: She's very active and loves to explore, but she always glances back to make sure we're still there.
- [24m] looks at your face to see how to react in a new situation -> yes | status: ok | reason: She often looks at my face to see if things are okay, especially if it's something new.
- [24m] notices when others are hurt or upset like pausing or looking sad when someone is crying -> yes | status: ok | reason: She's very observant and often looks at faces, so she notices when someone is sad or upset.

Band summary:
  15m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  24m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Social / Emotional: 24 months (chronological age 20 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 12 months ---
Q: Can Aria calls parents mama or dada or another special name right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She does say mama and dada, those are some of her few words.
Q: Can Aria understands no so pauses briefly or stops when you say it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we mean when we say 'no' and usually stops.
Q: Can Aria waves byebye right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She definitely waves when we say bye-bye.

--- Asking Language / Communication milestones around 15 months ---
Q: Can Aria follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we want her to do when we show her.
Q: Can Aria looks at a ffamiliar object when you name it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands well what we say.
Q: Can Aria points to ask for something or to get help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She points to things she wants, like a snack or toy, or if she needs help getting something.

--- Asking Language / Communication milestones around 18 months ---
Q: Can Aria follows one step directions without any gestures like giving you the toy when you say give it to me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we say, especially for simple requests like that.
Q: Can Aria tries to say three or more words besides mama or dada right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Her profile says she has about 10 words, so that's definitely more than three besides mama and dada.

Question / answer transcript:
- [12m] calls parents mama or dada or another special name -> yes | status: ok | reason: She does say mama and dada, those are some of her few words.
- [12m] understands no so pauses briefly or stops when you say it -> yes | status: ok | reason: She understands what we mean when we say 'no' and usually stops.
- [12m] waves byebye -> yes | status: ok | reason: She definitely waves when we say bye-bye.
- [15m] follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy -> yes | status: ok | reason: She understands what we want her to do when we show her.
- [15m] looks at a ffamiliar object when you name it -> yes | status: ok | reason: She understands well what we say.
- [15m] points to ask for something or to get help -> yes | status: ok | reason: She points to things she wants, like a snack or toy, or if she needs help getting something.
- [18m] follows one step directions without any gestures like giving you the toy when you say give it to me -> yes | status: ok | reason: She understands what we say, especially for simple requests like that.
- [18m] tries to say three or more words besides mama or dada -> yes | status: ok | reason: Her profile says she has about 10 words, so that's definitely more than three besides mama and dada.

Band summary:
  12m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  15m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Language / Communication: 18 months (chronological age 20 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 15 months ---
Q: Can Aria stacks at least two small objects like blocks right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Yes, she can, but she's usually too busy being active to sit and stack for long.
Q: Can Aria tries to use things the right way like a phone or a cup or a book right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yeah, she'll grab a phone and put it to her ear, or pretend to drink from a cup. She knows what they're for.

--- Asking Cognitive / Adaptive milestones around 18 months ---
Q: Can Aria copies you doing chores like sweeping with a broom right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's always trying to 'help' and copies whatever we're doing.
Q: Can Aria plays with toys in a simple way like pushing a toy car right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very active and loves to push her toy cars around the floor.

--- Asking Cognitive / Adaptive milestones around 24 months ---
Q: Can Aria holds something in one hand while using the other hand for example holding a container and taking the lid off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, she's always trying to open her snack containers and sometimes she gets them.
Q: Can Aria plays with more than one toy at the same time like putting toy food on a toy plate right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves to play with her kitchen set and put things on plates.
Q: Can Aria tries to use switches or knobs or buttons on a toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very curious and loves to see what happens when she pushes them.

Question / answer transcript:
- [15m] stacks at least two small objects like blocks -> yes | status: ok | reason: Yes, she can, but she's usually too busy being active to sit and stack for long.
- [15m] tries to use things the right way like a phone or a cup or a book -> yes | status: ok | reason: Oh yeah, she'll grab a phone and put it to her ear, or pretend to drink from a cup. She knows what they're for.
- [18m] copies you doing chores like sweeping with a broom -> yes | status: ok | reason: She's always trying to 'help' and copies whatever we're doing.
- [18m] plays with toys in a simple way like pushing a toy car -> yes | status: ok | reason: She's very active and loves to push her toy cars around the floor.
- [24m] holds something in one hand while using the other hand for example holding a container and taking the lid off -> yes | status: ok | reason: Oh yes, she's always trying to open her snack containers and sometimes she gets them.
- [24m] plays with more than one toy at the same time like putting toy food on a toy plate -> yes | status: ok | reason: She loves to play with her kitchen set and put things on plates.
- [24m] tries to use switches or knobs or buttons on a toy -> yes | status: ok | reason: She's very curious and loves to see what happens when she pushes them.

Band summary:
  15m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  18m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  24m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Cognitive / Adaptive: 24 months (chronological age 20 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
No categories need a scheduled weekly activity plan right now.

==============================================================================================================
CASE C11 | Aria | 20 months | No diagnosis
==============================================================================================================

1. CHILD PROFILE
- Name: Aria
- Age: 20 months (20 months)
- Diagnosis: No diagnosis
- Daily time available: 10 min/day
- Key concerns:
  • Only ~10 words
  • very active
  • good eye contact
  • understands well

2. PARENT INPUT (full transcript)

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,18,2,no_special_support,minimal / mild
1,Social / Emotional,24,0,no_special_support,minimal / mild
2,Language / Communication,18,2,no_special_support,minimal / mild
3,Cognitive / Adaptive,24,0,no_special_support,minimal / mild

Focus areas:

Daily activities:

4. SUMMARY
This output did not identify a strong need for special support across the reviewed categories, but the family can continue monitoring development and bring remaining questions to the clinician.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C12 | Mateo | 2y 6m | No formal diagnosis
==============================================================================================================
Concerns: Good eye contact but no words, lines up toys, responds to name inconsistently
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 6 month starting delay | The child shows limited verbal communication and inconsistent responses, suggesting a moderate delay in movement/physical skills.
Social / Emotional: 6 month starting delay | Inconsistent response to name and limited verbal communication suggest social/emotional delays.
Language / Communication: 12 month starting delay | The child shows good eye contact but has no words and inconsistent response to name, indicating a significant delay in language development.
Cognitive / Adaptive: 6 month starting delay | The child shows limited verbal communication and inconsistent response to name, indicating a potential cognitive delay.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 18 months ---
Q: Can Mateo climbs on and off a couch or chair without help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's pretty active and can get on and off the couch by himself without any trouble.
Q: Can Mateo drinks from a cup without a lid and may spill sometimes right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He uses a regular cup and just sometimes makes a mess.
Q: Can Mateo feeds himself with his fingers right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He picks up all his snacks and finger foods and eats them himself.

--- Asking Movement / Physical milestones around 24 months ---
Q: Can Mateo eats with a spoon right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He uses a spoon for most meals and handles it pretty well to feed himself.
Q: Can Mateo kicks a ball right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves kicking his little ball around in the backyard.
Q: Can Mateo runs right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yeah, he's always zooming around the house.

--- Asking Movement / Physical milestones around 30 months ---
Q: Can Mateo jumps off the ground with both feet right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves to bounce around, especially when he's excited.
Q: Can Mateo takes some clothes off by himself like loose pants or an open jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He usually pulls off his pants for naps and can slip out of his jacket.
Q: Can Mateo turns book pages one at a time when you read to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's good with his hands and likes to help turn the pages when we read.

Question / answer transcript:
- [18m] climbs on and off a couch or chair without help -> yes | status: ok | reason: He's pretty active and can get on and off the couch by himself without any trouble.
- [18m] drinks from a cup without a lid and may spill sometimes -> yes | status: ok | reason: He uses a regular cup and just sometimes makes a mess.
- [18m] feeds himself with his fingers -> yes | status: ok | reason: He picks up all his snacks and finger foods and eats them himself.
- [24m] eats with a spoon -> yes | status: ok | reason: He uses a spoon for most meals and handles it pretty well to feed himself.
- [24m] kicks a ball -> yes | status: ok | reason: He loves kicking his little ball around in the backyard.
- [24m] runs -> yes | status: ok | reason: Oh yeah, he's always zooming around the house.
- [30m] jumps off the ground with both feet -> yes | status: ok | reason: He loves to bounce around, especially when he's excited.
- [30m] takes some clothes off by himself like loose pants or an open jacket -> yes | status: ok | reason: He usually pulls off his pants for naps and can slip out of his jacket.
- [30m] turns book pages one at a time when you read to her -> yes | status: ok | reason: He's good with his hands and likes to help turn the pages when we read.

Band summary:
  18m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  24m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  30m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Movement / Physical: 30 months (chronological age 30 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 18 months ---
Q: Can Mateo helps you dress him by pushing the arm through the sleeve or lifting up the foot right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll do it sometimes, but it's not every time or super consistent.
Q: Can Mateo looks at a few pages in a book with you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He has good eye contact, so he usually looks with me when we have a book.
Q: Can Mateo moves away from you but looks to make sure you are close by right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He has good eye contact and usually checks to see where I am when he's off playing.

--- Asking Social / Emotional milestones around 24 months ---
Q: Can Mateo looks at your face to see how to react in a new situation right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll look at my face when something new happens, but I'm not always sure if he's really using it to figure out how to react.
Q: Can Mateo notices when others are hurt or upset like pausing or looking sad when someone is crying right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll sometimes pause or look over when someone is crying, but it's not every time.

--- Asking Social / Emotional milestones around 30 months ---
Q: Can Mateo follos simple routines when told like helping to pick up toys when you say it is clean up time right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He has trouble with words, so following directions can be tricky, but sometimes he'll help if we start the cleanup together.
Q: Can Mateo plays next to other children and sometimes plays with them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: Mateo usually focuses on his own play, like lining up toys, and doesn't typically interact with other children when they are nearby.
Q: Can Mateo shows you what she can do by saying look at me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He doesn't have any words yet, so he can't say 'look at me'.

Question / answer transcript:
- [18m] helps you dress him by pushing the arm through the sleeve or lifting up the foot -> sometimes | status: ok | reason: He'll do it sometimes, but it's not every time or super consistent.
- [18m] looks at a few pages in a book with you -> yes | status: ok | reason: He has good eye contact, so he usually looks with me when we have a book.
- [18m] moves away from you but looks to make sure you are close by -> yes | status: ok | reason: He has good eye contact and usually checks to see where I am when he's off playing.
- [24m] looks at your face to see how to react in a new situation -> sometimes | status: ok | reason: He'll look at my face when something new happens, but I'm not always sure if he's really using it to figure out how to react.
- [24m] notices when others are hurt or upset like pausing or looking sad when someone is crying -> sometimes | status: ok | reason: He'll sometimes pause or look over when someone is crying, but it's not every time.
- [30m] follos simple routines when told like helping to pick up toys when you say it is clean up time -> sometimes | status: ok | reason: He has trouble with words, so following directions can be tricky, but sometimes he'll help if we start the cleanup together.
- [30m] plays next to other children and sometimes plays with them -> no | status: ok | reason: Mateo usually focuses on his own play, like lining up toys, and doesn't typically interact with other children when they are nearby.
- [30m] shows you what she can do by saying look at me -> no | status: ok | reason: He doesn't have any words yet, so he can't say 'look at me'.

Band summary:
  18m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67
  24m | total=2 | yes=0 | partial=2 | no=0 | yes_ratio=0.0
  30m | total=3 | yes=0 | partial=1 | no=2 | yes_ratio=0.0

Estimated developmental age for Social / Emotional: 18 months (chronological age 30 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 12 months ---
Q: Can Mateo calls parents mama or dada or another special name right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: Mateo doesn't have any words yet, so he can't say 'mama' or 'dada'.
Q: Can Mateo understands no so pauses briefly or stops when you say it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He's inconsistent with his name, and it's the same with 'no'. Sometimes he pauses, sometimes he just keeps going.
Q: Can Mateo waves byebye right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He'll wave back if he's really paying attention, but it's not consistent.

--- Asking Language / Communication milestones around 15 months ---
Q: Can Mateo follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He gets it sometimes, especially with the hand gesture.
Q: Can Mateo looks at a ffamiliar object when you name it right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He responds to his name inconsistently, so it's similar with objects. Sometimes he'll look, sometimes he won't.
Q: Can Mateo points to ask for something or to get help right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He does point to things he wants sometimes, especially food, but it's not consistent or always clear when he needs help.

--- Asking Language / Communication milestones around 18 months ---
Q: Can Mateo follows one step directions without any gestures like giving you the toy when you say give it to me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He really needs us to show him what we want him to do, just words don't seem to make sense to him.
Q: Can Mateo tries to say three or more words besides mama or dada right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He doesn't say any words at all yet, not even mama or dada.

Question / answer transcript:
- [12m] calls parents mama or dada or another special name -> no | status: ok | reason: Mateo doesn't have any words yet, so he can't say 'mama' or 'dada'.
- [12m] understands no so pauses briefly or stops when you say it -> sometimes | status: ok | reason: He's inconsistent with his name, and it's the same with 'no'. Sometimes he pauses, sometimes he just keeps going.
- [12m] waves byebye -> sometimes | status: ok | reason: He'll wave back if he's really paying attention, but it's not consistent.
- [15m] follows directions given with both a gesture and words for example she gives you a toy when you hold out your hand and say give me the toy -> sometimes | status: ok | reason: He gets it sometimes, especially with the hand gesture.
- [15m] looks at a ffamiliar object when you name it -> sometimes | status: ok | reason: He responds to his name inconsistently, so it's similar with objects. Sometimes he'll look, sometimes he won't.
- [15m] points to ask for something or to get help -> sometimes | status: ok | reason: He does point to things he wants sometimes, especially food, but it's not consistent or always clear when he needs help.
- [18m] follows one step directions without any gestures like giving you the toy when you say give it to me -> no | status: ok | reason: He really needs us to show him what we want him to do, just words don't seem to make sense to him.
- [18m] tries to say three or more words besides mama or dada -> no | status: ok | reason: He doesn't say any words at all yet, not even mama or dada.

Band summary:
  12m | total=3 | yes=0 | partial=2 | no=1 | yes_ratio=0.0
  15m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  18m | total=2 | yes=0 | partial=0 | no=2 | yes_ratio=0.0

Estimated developmental age for Language / Communication: 12 months (chronological age 30 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 18 months ---
Q: Can Mateo copies you doing chores like sweeping with a broom right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He has good eye contact and watches what I do, and sometimes he'll pick up his toy broom and try to copy me.
Q: Can Mateo plays with toys in a simple way like pushing a toy car right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He mostly lines his toys up, but he will sometimes push a car around briefly.

--- Asking Cognitive / Adaptive milestones around 24 months ---
Q: Can Mateo holds something in one hand while using the other hand for example holding a container and taking the lid off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it with some containers, especially if he's interested in what's inside.
Q: Can Mateo plays with more than one toy at the same time like putting toy food on a toy plate right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He mostly just lines up his toys, not really playing with them together.
Q: Can Mateo tries to use switches or knobs or buttons on a toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He will try pushing buttons or turning a knob if he's playing with a toy that has them, but it's not consistent.

--- Asking Cognitive / Adaptive milestones around 30 months ---
Q: Can Mateo follows two step instructions like put the toy down and close the door right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He's not really understanding words yet, especially not two things at once.
Q: Can Mateo shows she knows at least one color like pointing to a red crayon when you ask which one is red right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He doesn't really have words yet, so he doesn't know color names.
Q: Can Mateo shows simple problem solving skills like standing on a small stool to reach something right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: He doesn't usually think to get a stool or figure out how to reach things that way.

Question / answer transcript:
- [18m] copies you doing chores like sweeping with a broom -> sometimes | status: ok | reason: He has good eye contact and watches what I do, and sometimes he'll pick up his toy broom and try to copy me.
- [18m] plays with toys in a simple way like pushing a toy car -> sometimes | status: ok | reason: He mostly lines his toys up, but he will sometimes push a car around briefly.
- [24m] holds something in one hand while using the other hand for example holding a container and taking the lid off -> sometimes | status: ok | reason: He can do it with some containers, especially if he's interested in what's inside.
- [24m] plays with more than one toy at the same time like putting toy food on a toy plate -> no | status: ok | reason: He mostly just lines up his toys, not really playing with them together.
- [24m] tries to use switches or knobs or buttons on a toy -> sometimes | status: ok | reason: He will try pushing buttons or turning a knob if he's playing with a toy that has them, but it's not consistent.
- [30m] follows two step instructions like put the toy down and close the door -> no | status: ok | reason: He's not really understanding words yet, especially not two things at once.
- [30m] shows she knows at least one color like pointing to a red crayon when you ask which one is red -> no | status: ok | reason: He doesn't really have words yet, so he doesn't know color names.
- [30m] shows simple problem solving skills like standing on a small stool to reach something -> no | status: ok | reason: He doesn't usually think to get a stool or figure out how to reach things that way.

Band summary:
  18m | total=2 | yes=0 | partial=2 | no=0 | yes_ratio=0.0
  24m | total=3 | yes=0 | partial=2 | no=1 | yes_ratio=0.0
  30m | total=3 | yes=0 | partial=0 | no=3 | yes_ratio=0.0

Estimated developmental age for Cognitive / Adaptive: 18 months (chronological age 30 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
Summary: Weekly schedule built from category activity banks and true daily minute limits.
Daily time budget: 10
Target minutes by category: {'social_and_emotional': 15, 'language_and_communication': 20, 'cognitive': 15}
Assigned minutes by category: {'social_and_emotional': 10, 'language_and_communication': 22, 'cognitive': 15}


,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,30,0,no_special_support,minimal / mild
1,Social / Emotional,18,12,needs_special_support,moderate
2,Language / Communication,12,18,needs_special_support,moderate
3,Cognitive / Adaptive,18,12,needs_special_support,moderate

Focus areas:
  • Language / Communication
  • Social / Emotional
  • Cognitive / Adaptive

Daily activities:
1. Sound Imitation Game | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Make different animal sounds and encourage Mateo to imitate them. Start with simple sounds like 'moo' for a cow or 'meow' for a cat. Use gestures to encourage him to join in.
2. Chore Imitation | Cognitive / Adaptive | 5 min
   Goal: needs_special_support
   Description: Show Mateo how to sweep the floor with a broom. Encourage him to copy you while you sweep together.
3. Follow the Gesture | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Show Mateo a simple gesture like waving or pointing. Encourage him to copy you. Then, ask him to do the gesture when you say a word related to it, like 'bye-bye' for waving.
4. Toy Car Push | Cognitive / Adaptive | 5 min
   Goal: needs_special_support
   Description: Sit on the floor with Mateo and take turns pushing a toy car back and forth. Encourage him to push the car towards you.
5. Simple Direction Following | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Give Mateo simple directions using both words and gestures, like 'come here' or 'give me the ball'. Celebrate when he follows your direction.

4. SUMMARY
This plan prioritizes Social / Emotional, Language / Communication, Cognitive / Adaptive for Mateo. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C13 | Luna | 3y 6m | Speech delay
==============================================================================================================
Concerns: Limited speech, understands well, parents have very limited time for activities
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 3 month starting delay | Limited opportunities for physical activities may impact movement development.
Social / Emotional: 6 month starting delay | Limited speech may impact social interactions and emotional expression.
Language / Communication: 12 month starting delay | The child has a speech delay, indicating a significant delay in language/communication skills.
Cognitive / Adaptive: 6 month starting delay | Limited speech may impact cognitive/adaptive skills related to communication and problem-solving.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 30 months ---
Q: Can Luna jumps off the ground with both feet right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's very active and loves jumping around.
Q: Can Luna takes some clothes off by himself like loose pants or an open jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often pulls off her pajamas for bed or takes off her jacket when she comes inside.
Q: Can Luna turns book pages one at a time when you read to her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty good with her hands, especially when we read together.

--- Asking Movement / Physical milestones around 36 months ---
Q: Can Luna puts on some clothes by himself like loose pants or a jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can pull up her loose pants and put her arms into a jacket without us helping.
Q: Can Luna strings items together like large beads or macaroni right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can do that, she does it at preschool sometimes.
Q: Can Luna uses a fork right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty good with her fork for most meals, even if it's a bit messy sometimes.

--- Asking Movement / Physical milestones around 48 months ---
Q: Can Luna catches a large ball most of the times right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty good with her hands and overall movement, so she usually gets it.
Q: Can Luna holds crayon or pencil between fingers and thumb not fist right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She uses it like that when she tries to draw pictures.
Q: Can Luna serves herself food or pours water with adult supervision right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's good with her hands and we encourage her to help herself at meal times.

Question / answer transcript:
- [30m] jumps off the ground with both feet -> yes | status: ok | reason: She's very active and loves jumping around.
- [30m] takes some clothes off by himself like loose pants or an open jacket -> yes | status: ok | reason: She often pulls off her pajamas for bed or takes off her jacket when she comes inside.
- [30m] turns book pages one at a time when you read to her -> yes | status: ok | reason: She's pretty good with her hands, especially when we read together.
- [36m] puts on some clothes by himself like loose pants or a jacket -> yes | status: ok | reason: She can pull up her loose pants and put her arms into a jacket without us helping.
- [36m] strings items together like large beads or macaroni -> yes | status: ok | reason: She can do that, she does it at preschool sometimes.
- [36m] uses a fork -> yes | status: ok | reason: She's pretty good with her fork for most meals, even if it's a bit messy sometimes.
- [48m] catches a large ball most of the times -> yes | status: ok | reason: She's pretty good with her hands and overall movement, so she usually gets it.
- [48m] holds crayon or pencil between fingers and thumb not fist -> yes | status: ok | reason: She uses it like that when she tries to draw pictures.
- [48m] serves herself food or pours water with adult supervision -> yes | status: ok | reason: She's good with her hands and we encourage her to help herself at meal times.

Band summary:
  30m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  36m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  48m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Movement / Physical: 48 months (chronological age 42 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 24 months ---
Q: Can Luna looks at your face to see how to react in a new situation right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands everything really well, so she definitely looks at our faces to figure out new situations.
Q: Can Luna notices when others are hurt or upset like pausing or looking sad when someone is crying right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She definitely notices and often gets a sad look on her face when someone is upset.

--- Asking Social / Emotional milestones around 30 months ---
Q: Can Luna follos simple routines when told like helping to pick up toys when you say it is clean up time right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask her to do, even if she doesn't say much back.
Q: Can Luna plays next to other children and sometimes plays with them right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She enjoys being around other kids and will play next to them, and sometimes they'll even play together for a bit.
Q: Can Luna shows you what she can do by saying look at me right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She has limited speech, so she doesn't use phrases like 'look at me'.

--- Asking Social / Emotional milestones around 36 months ---
Q: Can Luna calms down within 10 minutes after you leave her like at childcare drop off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands the routine of drop-off and usually settles pretty quickly once we're gone.
Q: Can Luna notices other children and joins them to play right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: She sometimes plays with other children, so she does notice them and join in sometimes.

Question / answer transcript:
- [24m] looks at your face to see how to react in a new situation -> yes | status: ok | reason: She understands everything really well, so she definitely looks at our faces to figure out new situations.
- [24m] notices when others are hurt or upset like pausing or looking sad when someone is crying -> yes | status: ok | reason: She definitely notices and often gets a sad look on her face when someone is upset.
- [30m] follos simple routines when told like helping to pick up toys when you say it is clean up time -> yes | status: ok | reason: She understands what we ask her to do, even if she doesn't say much back.
- [30m] plays next to other children and sometimes plays with them -> yes | status: ok | reason: She enjoys being around other kids and will play next to them, and sometimes they'll even play together for a bit.
- [30m] shows you what she can do by saying look at me -> no | status: ok | reason: She has limited speech, so she doesn't use phrases like 'look at me'.
- [36m] calms down within 10 minutes after you leave her like at childcare drop off -> yes | status: ok | reason: She understands the routine of drop-off and usually settles pretty quickly once we're gone.
- [36m] notices other children and joins them to play -> sometimes | status: ok | reason: She sometimes plays with other children, so she does notice them and join in sometimes.

Band summary:
  24m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  30m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67
  36m | total=2 | yes=1 | partial=1 | no=0 | yes_ratio=0.5

Estimated developmental age for Social / Emotional: 30 months (chronological age 42 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 24 months ---
Q: Can Luna points at least two body parts when you ask her to show you right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask her to do, even if she can't always say the words herself.
Q: Can Luna points to things in a book when you ask like where is the bear right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask, even though her speech is limited.
Q: Can Luna says at least two words together like more milk right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She mostly uses single words, she's not combining them yet.

--- Asking Language / Communication milestones around 30 months ---
Q: Can Luna name things in a book when you point and ask what is this right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She understands what we point to, but she can't usually say the names of things yet.
Q: Can Luna say two or more words toghether with one action word like doggie run right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She doesn't really put words together yet, even simple ones.
Q: Can Luna says about 50 words right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She has very limited speech right now, definitely not 50 words.

--- Asking Language / Communication milestones around 36 months ---
Q: Can Luna ask who or what or where or why questions like where is mommy or where is daddy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She doesn't really put words together like that yet.
Q: Can Luna says first name when asked right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She knows her name, but she doesn't really say many words at all yet.
Q: Can Luna says what action is happening in a picture or book when asked like running or eating or playing right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: She has very limited speech and doesn't say single words for actions yet.

Question / answer transcript:
- [24m] points at least two body parts when you ask her to show you -> yes | status: ok | reason: She understands what we ask her to do, even if she can't always say the words herself.
- [24m] points to things in a book when you ask like where is the bear -> yes | status: ok | reason: She understands what we ask, even though her speech is limited.
- [24m] says at least two words together like more milk -> no | status: ok | reason: She mostly uses single words, she's not combining them yet.
- [30m] name things in a book when you point and ask what is this -> no | status: ok | reason: She understands what we point to, but she can't usually say the names of things yet.
- [30m] say two or more words toghether with one action word like doggie run -> no | status: ok | reason: She doesn't really put words together yet, even simple ones.
- [30m] says about 50 words -> no | status: ok | reason: She has very limited speech right now, definitely not 50 words.
- [36m] ask who or what or where or why questions like where is mommy or where is daddy -> no | status: ok | reason: She doesn't really put words together like that yet.
- [36m] says first name when asked -> no | status: ok | reason: She knows her name, but she doesn't really say many words at all yet.
- [36m] says what action is happening in a picture or book when asked like running or eating or playing -> no | status: ok | reason: She has very limited speech and doesn't say single words for actions yet.

Band summary:
  24m | total=3 | yes=2 | partial=0 | no=1 | yes_ratio=0.67
  30m | total=3 | yes=0 | partial=0 | no=3 | yes_ratio=0.0
  36m | total=3 | yes=0 | partial=0 | no=3 | yes_ratio=0.0

Estimated developmental age for Language / Communication: 24 months (chronological age 42 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 24 months ---
Q: Can Luna holds something in one hand while using the other hand for example holding a container and taking the lid off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She opens her snack containers and takes lids off her toys without any trouble.
Q: Can Luna plays with more than one toy at the same time like putting toy food on a toy plate right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She often sets up little scenarios, like feeding her stuffed animals.
Q: Can Luna tries to use switches or knobs or buttons on a toy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She loves her busy board and any toy with buttons that make sounds.

--- Asking Cognitive / Adaptive milestones around 30 months ---
Q: Can Luna follows two step instructions like put the toy down and close the door right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Her understanding is really good, even though she doesn't talk much.
Q: Can Luna shows she knows at least one color like pointing to a red crayon when you ask which one is red right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands what we ask, even if she doesn't say the color name, she can point to it.
Q: Can Luna shows simple problem solving skills like standing on a small stool to reach something right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She's pretty smart and figures out how to get things she wants, even if it means using a chair.

--- Asking Cognitive / Adaptive milestones around 36 months ---
Q: Can Luna avoids touching hot objects like the stove when you warn her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She understands warnings really well and knows to stay away from the stove when we tell her it's hot.
Q: Can Luna draws a circle when you show her how right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She can usually make a pretty good circle if we show her first.

Question / answer transcript:
- [24m] holds something in one hand while using the other hand for example holding a container and taking the lid off -> yes | status: ok | reason: She opens her snack containers and takes lids off her toys without any trouble.
- [24m] plays with more than one toy at the same time like putting toy food on a toy plate -> yes | status: ok | reason: She often sets up little scenarios, like feeding her stuffed animals.
- [24m] tries to use switches or knobs or buttons on a toy -> yes | status: ok | reason: She loves her busy board and any toy with buttons that make sounds.
- [30m] follows two step instructions like put the toy down and close the door -> yes | status: ok | reason: Her understanding is really good, even though she doesn't talk much.
- [30m] shows she knows at least one color like pointing to a red crayon when you ask which one is red -> yes | status: ok | reason: She understands what we ask, even if she doesn't say the color name, she can point to it.
- [30m] shows simple problem solving skills like standing on a small stool to reach something -> yes | status: ok | reason: She's pretty smart and figures out how to get things she wants, even if it means using a chair.
- [36m] avoids touching hot objects like the stove when you warn her -> yes | status: ok | reason: She understands warnings really well and knows to stay away from the stove when we tell her it's hot.
- [36m] draws a circle when you show her how -> yes | status: ok | reason: She can usually make a pretty good circle if we show her first.

Band summary:
  24m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  30m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,48,0,no_special_support,minimal / mild
1,Social / Emotional,30,12,needs_special_support,moderate
2,Language / Communication,24,18,needs_special_support,moderate
3,Cognitive / Adaptive,36,6,monitor_and_enrich,minimal / mild

Focus areas:
  • Language / Communication
  • Social / Emotional
  • Cognitive / Adaptive

Daily activities:
1. Body Part Pointing | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Ask Luna to point to different body parts on herself or on a doll. Start with common ones like 'nose' and 'eyes'.
2. Clean Up Time | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: At a designated time, say 'It's clean up time!' and encourage Luna to help pick up her toys. Use eye contact and praise her efforts.
3. Two-Word Phrases | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Encourage Luna to use two-word phrases by modeling them. For example, say 'more juice' and prompt her to repeat it.
4. Look at Me Game | Social / Emotional | 5 min
   Goal: needs_special_support
   Description: Take turns with Luna to show each other something fun you can do. Encourage her to say 'Look at me!' when it's her turn.
5. Gesture Game | Language / Communication | 5 min
   Goal: needs_special_support
   Description: Play a game where you model different gestures (like blowing a kiss or nodding) and encourage Luna to imitate you.

4. SUMMARY
This plan prioritizes Social / Emotional, Language / Communication, Cognitive / Adaptive for Luna. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
STARTING C14 | Ryan | 4y 2m | No diagnosis
==============================================================================================================
Concerns: Tantrums, difficulty with transitions, strong language skills, social but rigid
Daily time: 10 min/day

====================================================================================================
DELAY ESTIMATOR AGENT
====================================================================================================
Movement / Physical: 3 month starting delay | The child's strong language skills and social engagement suggest some physical development is on track, but tantrums and difficulty with transitions may indicate some challenges in movement/physical domain.
Social / Emotional: 4 month starting delay | The child's rigidity in social interactions suggests a slight delay in social/emotional development.
Language / Communication: 3 month starting delay | The child exhibits strong language skills but has rigidity in social interactions, suggesting a slight delay in functional communication.
Cognitive / Adaptive: 3 month starting delay | The child's rigidity in social interactions may indicate some cognitive adaptive challenges.

====================================================================================================
MILESTONE Q&A AGENT — Movement / Physical
====================================================================================================

--- Asking Movement / Physical milestones around 36 months ---
Q: Can Ryan puts on some clothes by himself like loose pants or a jacket right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can, but often doesn't want to because of his rigidity and difficulty with transitions.
Q: Can Ryan strings items together like large beads or macaroni right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it when he's focused, but he gets frustrated easily if it's tricky or not going his way.
Q: Can Ryan uses a fork right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can use it, but often defaults to his hands or a spoon for ease.

--- Asking Movement / Physical milestones around 48 months ---
Q: Can Ryan catches a large ball most of the times right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it, but sometimes he misses or isn't paying attention.
Q: Can Ryan holds crayon or pencil between fingers and thumb not fist right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it, but he doesn't always choose to hold it that way, sometimes he still uses a fisted grip.
Q: Can Ryan serves herself food or pours water with adult supervision right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): sometimes | status: ok | reason: He can do it, but it often depends on his mood and how careful he wants to be.

Question / answer transcript:
- [36m] puts on some clothes by himself like loose pants or a jacket -> sometimes | status: ok | reason: He can, but often doesn't want to because of his rigidity and difficulty with transitions.
- [36m] strings items together like large beads or macaroni -> sometimes | status: ok | reason: He can do it when he's focused, but he gets frustrated easily if it's tricky or not going his way.
- [36m] uses a fork -> sometimes | status: ok | reason: He can use it, but often defaults to his hands or a spoon for ease.
- [48m] catches a large ball most of the times -> sometimes | status: ok | reason: He can do it, but sometimes he misses or isn't paying attention.
- [48m] holds crayon or pencil between fingers and thumb not fist -> sometimes | status: ok | reason: He can do it, but he doesn't always choose to hold it that way, sometimes he still uses a fisted grip.
- [48m] serves herself food or pours water with adult supervision -> sometimes | status: ok | reason: He can do it, but it often depends on his mood and how careful he wants to be.

Band summary:
  36m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0
  48m | total=3 | yes=0 | partial=3 | no=0 | yes_ratio=0.0

Estimated developmental age for Movement / Physical: 36 months (chronological age 50 months)

====================================================================================================
MILESTONE Q&A AGENT — Social / Emotional
====================================================================================================

--- Asking Social / Emotional milestones around 36 months ---
Q: Can Ryan calms down within 10 minutes after you leave her like at childcare drop off right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): no | status: ok | reason: Ryan has a really hard time with goodbyes and transitions, so it usually takes him much longer than 10 minutes to calm down.
Q: Can Ryan notices other children and joins them to play right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and usually wants to play with other kids.

--- Asking Social / Emotional milestones around 48 months ---
Q: Can Ryan asks to go play with children if none are around like can I play with Alex right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's very social and has strong language skills, so he definitely asks to play with his friends.
Q: Can Ryan avoids danger like not jumping from tall heights at the playgroung right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He generally understands what's safe and what's not.
Q: Can Ryan changes behavior based on where she is like place of worship or library or playground right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): with_help | status: ok | reason: She's rigid and struggles with transitions, so she needs reminders and guidance to adjust.

Question / answer transcript:
- [36m] calms down within 10 minutes after you leave her like at childcare drop off -> no | status: ok | reason: Ryan has a really hard time with goodbyes and transitions, so it usually takes him much longer than 10 minutes to calm down.
- [36m] notices other children and joins them to play -> yes | status: ok | reason: He's very social and usually wants to play with other kids.
- [48m] asks to go play with children if none are around like can I play with Alex -> yes | status: ok | reason: He's very social and has strong language skills, so he definitely asks to play with his friends.
- [48m] avoids danger like not jumping from tall heights at the playgroung -> yes | status: ok | reason: He generally understands what's safe and what's not.
- [48m] changes behavior based on where she is like place of worship or library or playground -> with_help | status: ok | reason: She's rigid and struggles with transitions, so she needs reminders and guidance to adjust.

Band summary:
  36m | total=2 | yes=1 | partial=0 | no=1 | yes_ratio=0.5
  48m | total=3 | yes=2 | partial=1 | no=0 | yes_ratio=0.67

Estimated developmental age for Social / Emotional: 48 months (chronological age 50 months)

====================================================================================================
MILESTONE Q&A AGENT — Language / Communication
====================================================================================================

--- Asking Language / Communication milestones around 36 months ---
Q: Can Ryan ask who or what or where or why questions like where is mommy or where is daddy right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Ryan has very strong language skills and asks these kinds of questions all the time.
Q: Can Ryan says first name when asked right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He has strong language skills and knows his name perfectly well.
Q: Can Ryan says what action is happening in a picture or book when asked like running or eating or playing right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Ryan has strong language skills and can usually tell us what's going on in a picture or book.

--- Asking Language / Communication milestones around 48 months ---
Q: Can Ryan answers simple questions like what is a coat for or what is crayon for right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He's really good with his words and can explain what things are used for.
Q: Can Ryan says sentences with four or more words right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he talks in full sentences all the time, he has very strong language skills.
Q: Can Ryan says some words from a song or story or nursery rhyme right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves to sing along to his favorite songs and can recite parts of stories.

Question / answer transcript:
- [36m] ask who or what or where or why questions like where is mommy or where is daddy -> yes | status: ok | reason: Ryan has very strong language skills and asks these kinds of questions all the time.
- [36m] says first name when asked -> yes | status: ok | reason: He has strong language skills and knows his name perfectly well.
- [36m] says what action is happening in a picture or book when asked like running or eating or playing -> yes | status: ok | reason: Ryan has strong language skills and can usually tell us what's going on in a picture or book.
- [48m] answers simple questions like what is a coat for or what is crayon for -> yes | status: ok | reason: He's really good with his words and can explain what things are used for.
- [48m] says sentences with four or more words -> yes | status: ok | reason: Oh yes, he talks in full sentences all the time, he has very strong language skills.
- [48m] says some words from a song or story or nursery rhyme -> yes | status: ok | reason: He loves to sing along to his favorite songs and can recite parts of stories.

Band summary:
  36m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0
  48m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Language / Communication: 48 months (chronological age 50 months)

====================================================================================================
MILESTONE Q&A AGENT — Cognitive / Adaptive
====================================================================================================

--- Asking Cognitive / Adaptive milestones around 36 months ---
Q: Can Ryan avoids touching hot objects like the stove when you warn her right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He understands what 'hot' means and usually listens to us about safety.
Q: Can Ryan draws a circle when you show her how right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: Oh yes, he's been drawing shapes like that for a while now.

--- Asking Cognitive / Adaptive milestones around 48 months ---
Q: Can Ryan draws a person with three or more body parts right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: She draws people pretty often, usually with a head, body, and legs at least.
Q: Can Ryan names a few colors or items right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He has strong language skills and knows his colors and lots of different things.
Q: Can Ryan tell what comes next in a well known story right now? (yes / sometimes / with_help / no / not_sure)
A (Gemini-parent): yes | status: ok | reason: He loves story time and can definitely anticipate what's coming in his favorite books.

Question / answer transcript:
- [36m] avoids touching hot objects like the stove when you warn her -> yes | status: ok | reason: He understands what 'hot' means and usually listens to us about safety.
- [36m] draws a circle when you show her how -> yes | status: ok | reason: Oh yes, he's been drawing shapes like that for a while now.
- [48m] draws a person with three or more body parts -> yes | status: ok | reason: She draws people pretty often, usually with a head, body, and legs at least.
- [48m] names a few colors or items -> yes | status: ok | reason: He has strong language skills and knows his colors and lots of different things.
- [48m] tell what comes next in a well known story -> yes | status: ok | reason: He loves story time and can definitely anticipate what's coming in his favorite books.

Band summary:
  36m | total=2 | yes=2 | partial=0 | no=0 | yes_ratio=1.0
  48m | total=3 | yes=3 | partial=0 | no=0 | yes_ratio=1.0

Estimated developmental age for Cognitive / Adaptive: 48 months (chronological age 50 months)

====================================================================================================
WEEKLY SCHEDULE
====================================================================================================
Summary: Weekly schedule built from category activity banks and true daily minute limits.
Daily time budget: 10
Target minutes by category: {'movement_and_physical': 50}
Assigned minutes by category: {'movement_and_physical': 37}

----------------------------------------------------------------------------------------------------
DAY_1 — total 5 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Dress-Up Challenge (5 min)
  Goal: needs_special_support
  Instructions: Provide Ryan with loose clothing items like a jacket or pants. Encourage him to put them on by himself. Offer assistance as needed, but let him try independently first.
  Materials: Loose clothing items (jacket, pants)

----------------------------------------------------------------------------------------------------
DAY_2 — total 5 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Ball Toss (5 min)
  Goal: needs_special_support
  Instructions: Stand a few feet away from Ryan and toss a large ball to him. Encourage him to catch it. If he misses, encourage him to try again. This helps with hand-eye coordination.
  Materials: Large ball

----------------------------------------------------------------------------------------------------
DAY_3 — total 7 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Bead Stringing (7 min)
  Goal: needs_special_support
  Instructions: Give Ryan large beads or macaroni and a string. Encourage him to string them together, helping him if he struggles. Focus on his grip and coordination.
  Materials: Large beads or macaroni, string

----------------------------------------------------------------------------------------------------
DAY_4 — total 10 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Crayon Drawing (10 min)
  Goal: needs_special_support
  Instructions: Provide Ryan with crayons and paper. Encourage him to hold the crayon between his fingers and thumb, not in a fist, while drawing. Offer prompts for different shapes or lines.
  Materials: Crayons, paper

----------------------------------------------------------------------------------------------------
DAY_5 — total 10 min
----------------------------------------------------------------------------------------------------
- [Movement / Physical] Pouring Practice (10 min)
  Goal: needs_special_support
  Instructions: With adult supervision, provide Ryan with a small pitcher of water and a cup. Encourage him to pour the water into the cup, focusing on control and balance.
  Materials: Small pitcher, cup, water

====================================================================================================
OPTIONAL WEEKLY BONUS ACTIVITY
====================================================================================================
- [Movement / Physical] Pouring Practice (10 min)
  Goal: needs_special_support
  Instructions: With adult supervision, provide Ryan with a small pitcher of water and a cup. Encourage him to pour the water into the cup, focusing on control and balance.
  Materials: Small pitcher, cup, water
  Why extended: This activity benefits from longer time to practice pouring and refining motor skills.

==============================================================================================================
CASE C14 | Ryan | 4y 2m | No diagnosis
==============================================================================================================

1. CHILD PROFILE
- Name: Ryan
- Age: 4y 2m (50 months)
- Diagnosis: No diagnosis
- Daily time available: 10 min/day
- Key concerns:
  • Tantrums
  • difficulty with transitions
  • strong language skills
  • social but rigid

2. PARENT INPUT (full transcript)
- [36m] puts on some clothes by himself like loose pants or a jacket -> sometimes (ok)
- [36m] strings items together like large beads or macaroni -> sometimes (ok)
- [36m] uses a fork -> sometimes (ok)
- [48m] catches a large ball most of the times -> sometimes (ok)
- [48m] holds crayon or pencil between fingers and thumb not fist -> sometimes (ok)
- [48m] serves herself food or pours water with adult supervision -> sometimes (ok)
- [36m] calms down within 10 minutes after you leave her like at childcare drop off -> no (ok)
- [36m] notices other children and joins them to play -> yes (ok)
- [48m] asks to go play with children if none are around like can I play with Alex -> yes (ok)
- [48m] avoids danger like not jumping from tall heights at the playgroung -> yes (ok)

,category,estimated_dev_age_months,gap_months,support_tier,severity
0,Movement / Physical,36,14,needs_special_support,moderate
1,Social / Emotional,48,2,no_special_support,minimal / mild
2,Language / Communication,48,2,no_special_support,minimal / mild
3,Cognitive / Adaptive,48,2,no_special_support,minimal / mild

Focus areas:
  • Movement / Physical

Daily activities:
1. Dress-Up Challenge | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Provide Ryan with loose clothing items like a jacket or pants. Encourage him to put them on by himself. Offer assistance as needed, but let him try independently first.
2. Ball Toss | Movement / Physical | 5 min
   Goal: needs_special_support
   Description: Stand a few feet away from Ryan and toss a large ball to him. Encourage him to catch it. If he misses, encourage him to try again. This helps with hand-eye coordination.
3. Bead Stringing | Movement / Physical | 7 min
   Goal: needs_special_support
   Description: Give Ryan large beads or macaroni and a string. Encourage him to string them together, helping him if he struggles. Focus on his grip and coordination.
4. Crayon Drawing | Movement / Physical | 10 min
   Goal: needs_special_support
   Description: Provide Ryan with crayons and paper. Encourage him to hold the crayon between his fingers and thumb, not in a fist, while drawing. Offer prompts for different shapes or lines.
5. Pouring Practice | Movement / Physical | 10 min
   Goal: needs_special_support
   Description: With adult supervision, provide Ryan with a small pitcher of water and a cup. Encourage him to pour the water into the cup, focusing on control and balance.

4. SUMMARY
This plan prioritizes Movement / Physical for Ryan. The activities are intended to be short, parent-friendly, and aligned with the developmental areas that appeared most delayed or most worth enriching in the interview.

5. ADVISOR REVIEW SECTION
Rate 1–5:
- Clinical appropriateness
- Safety
- Practicality for parents
- Clarity
- Overall usefulness
Short feedback:
- What would you change?
- What is missing?
- Any concerns?

==============================================================================================================
DONE
==============================================================================================================
Mode: gemini
Combined PDF: outputs/advisor_case_pack_v5/genex_case_report_gemini_20260428_135800.pdf
Rating CSV : outputs/advisor_case_pack_v5/advisor_rating_sheet_gemini_20260428_135800.csv
Rating XLSX: outputs/advisor_case_pack_v5/advisor_rating_sheet_gemini_20260428_135800.xlsx
Payload JSON: outputs/advisor_case_pack_v5/case_payloads_gemini_20260428_135800.json

,case_id,child_name,age_months,diagnosis,clinical_appropriateness_1to5,safety_1to5,practicality_for_parents_1to5,clarity_1to5,overall_usefulness_1to5,what_would_you_change,what_is_missing,any_concerns
0,C01,Noah,10,Down syndrome,,,,,,,,
1,C02,Maya,18,No formal diagnosis,,,,,,,,
2,C03,Leo,26,Autism spectrum disorder,,,,,,,,
3,C04,Sofia,37,Prematurity history,,,,,,,,
4,C05,Ethan,54,Cerebral palsy,,,,,,,,

PosixPath('outputs/advisor_case_pack_v5/genex_case_report_gemini_20260428_135800.pdf')

# How We Designed This Notebook and How the Current Algorithm Works

We built this notebook as a structured prototype of the Genex developmental interview and home-support engine for children ages 0–5. Our goal was to create something that is transparent enough for expert review, flexible enough to improve over time, and practical enough to eventually translate into a real product workflow.

At a high level, the notebook has one shared core pipeline and two different interview modes. The shared core pipeline is:

1. collect or load the child profile  
2. estimate a starting delay by developmental domain  
3. ask milestone questions by domain  
4. convert the answers into an estimated developmental age per domain  
5. determine the level of support needed in each domain  
6. generate activity banks by category  
7. build a realistic weekly schedule based on the parent’s available time  
8. optionally export a one-page case summary and advisor rating sheet  

The two interview modes are:

- **Live parent mode**: we answer the milestone questions directly as the parent or evaluator.
- **Synthetic parent mode**: another language model simulates the parent one question at a time from the child’s profile, while the Genex logic still controls question selection, scoring, and planning.

The point of using both modes is that live mode is better for careful manual review, while synthetic mode is useful for rapid stress-testing, generating benchmark cases, and creating packets for advisor feedback.

## 1. Child profile and intake

The notebook begins by gathering a simple child profile. The core fields are:

- child name
- chronological age in months
- diagnosis or condition, if known
- parent concern in free text
- daily time available for home support activities

We use **months** rather than years because the milestone tables are month-based and developmental changes are more granular in infancy and toddlerhood. This is especially important in younger ages, where a few months can make a meaningful difference.

The `daily_time_min` field is important because we did not want the system to recommend unrealistic activity loads. The weekly schedule is constrained by the parent’s available time rather than assuming unlimited home practice time.

## 2. CDC milestone table loading

The notebook loads a CDC milestone table as the structured source for milestone questions. The table is normalized into a consistent internal format, including:

- `months`
- `category`
- `milestone`
- `category_key`
- `question_id`

We map milestone categories into four working developmental domains:

- Movement / Physical
- Social / Emotional
- Language / Communication
- Cognitive / Adaptive

We use aliases so slightly different category names in the source table can still map into one consistent internal category system.

The reason we use a structured milestone table rather than asking a model to invent milestone questions is to keep the interview grounded, reproducible, and easier to inspect.

## 3. Starting delay estimation by domain

Before asking milestone questions, we estimate a **starting delay** in months for each domain. This is not meant to be a diagnosis and not meant to be the final developmental age. It is only meant to be a **rough starting anchor** to help us decide which age bands to ask first.

The starting delay is estimated separately for each domain using:

- chronological age
- diagnosis / condition
- parent concern
- the domain being evaluated

The output is:

- `delay_months`
- a short reason

The design goal here is to avoid asking all milestones from all ages. Instead, we use the starting delay to center the interview around the most likely developmental range for that specific child and that specific domain.

## 4. How we choose milestone questions

For each domain, we build the milestone question set dynamically.

The main logic is:

- `approx_dev_months = chronological_months - delay_months`
- define a question window around that developmental estimate
- retrieve CDC milestone items in that range
- select the closest age bands
- ask a small number of questions from each band

### Current important parameters

The current synthetic-review setup uses these settings:

- `window_months = 24`
- `target_questions_per_band = 3`
- `max_bands = 3`
- `max_questions_total = 9`
- `ask_limit_per_band = 3`

### Why we chose these numbers

- **24-month window**: wide enough to capture uncertainty without forcing the system to search the full age range every time
- **3 questions per band**: enough to detect a pattern without making the interview too long
- **3 bands**: gives a lower, middle, and upper range around the estimated developmental level
- **9 total questions per category**: keeps synthetic runs and advisor packets feasible
- **3 asked per band**: balances signal with time and cost

## 5. How answers are handled

Every milestone question can be answered using one of these normalized answer types:

- `yes`
- `sometimes`
- `with_help`
- `no`
- `not_sure`

These are also mapped to simple numeric scores internally:

- yes = 1.0
- sometimes = 0.4
- with_help = 0.2
- no = 0.0
- not_sure = 0.1

We use these labels because they are more realistic than forcing a binary yes/no for developmental milestones. Parents often observe partial, inconsistent, or supported performance.

### Live parent mode

In live mode, the parent or evaluator answers directly.

### Synthetic parent mode

In synthetic mode, a different model simulates a parent based on:

- the child profile
- the current domain
- the current milestone question
- a short memory of previous answers for consistency

We added retry logic, pacing between calls, and error handling because synthetic-parent mode is useful for testing but should not contaminate the developmental estimate with API failures. If the model fails, we treat that as an API problem rather than as real developmental uncertainty.

## 6. How developmental age is estimated

After collecting answers within a domain, we summarize them by age band.

For each month band, we count:

- total questions
- number of `yes`
- number of partial responses (`sometimes`, `with_help`, `not_sure`)
- number of `no`
- yes ratio

Then we use a conservative band-confirmation rule.

### Current confirmation parameters

- `min_yes_confirm = 2`
- `yes_ratio_confirm = 0.60`

### Why we chose these numbers

We originally used a stricter threshold, but it was too hard to confirm a band even when the child clearly had several strengths in that range. The current rule means a band is confirmed when it has:

- at least 2 strong yes answers
- and at least 60% yes within that band

This is conservative enough to avoid overestimating developmental age, but not so strict that partial developmental progress is ignored.

### Current developmental age rule

- If one or more bands are confirmed, we use the **highest confirmed band** as the estimated developmental age.
- If no band is fully confirmed but there are partial responses, we anchor to the lowest partial band and may step one band lower.
- If everything is negative, we fall back to the minimum asked band.

## 7. How we decide support level: three tiers

Once we have developmental age and milestone gap for each domain, we assign a support tier.

The three tiers are:

- `needs_special_support`
- `monitor_and_enrich`
- `no_special_support`

We moved to this three-tier system because a strict binary decision was too blunt. In practice, some categories do not need intensive support but still deserve light enrichment or monitoring.

### Inputs to support-tier logic

The support-tier decision uses:

- `chronological_months`
- `dev_age`
- `milestone_gap_months = chrono - dev_age`
- `estimated_delay_months`

### Why we made it age-aware

A 4-month gap means something very different at 10 months than at 60 months. We wanted the system to be more sensitive in infancy and more tolerant of smaller month differences in older children.

So instead of hard-coding diagnoses or using exactly the same month threshold at every age, we use age-scaled thresholds based on the child’s chronological age.

### Why we did not ask GPT again for support tier

We considered making support tier another model decision, but we chose not to. We want support tier to be:

- deterministic
- inspectable
- easier to explain to advisors
- easier to tune after feedback

So GPT helps with the **starting delay estimate** and the **activity generation**, but the support tier itself is based on transparent rules from the developmental results.

## 8. How activities are generated

We intentionally split activity planning into two stages.

### Stage 1: category activity bank

For each domain that needs support or enrichment, the notebook generates a **category-specific activity bank**.

The activity bank is not a day-by-day plan. It is a pool of candidate activities for that category.

Each activity includes fields such as:

- title
- instructions
- duration
- materials
- level (current-level or near-next-step)
- optional extended activity flag

### Why we did it this way

We did **not** want one model call to directly produce a full weekly schedule. That makes it hard to control realism and time budgets.

Instead, we ask the model for a good activity bank for one category. Then we use deterministic scheduling logic to build the weekly plan from those banks.

## 9. How weekly scheduling works

The weekly scheduler uses:

- daily time available
- milestone gap by category
- support tier by category
- category activity banks

The goal is to create a practical plan for a 5-day week.

### Core scheduling logic

1. determine which categories are eligible for support or enrichment  
2. compute gap-based weights  
3. give stronger categories more weekly emphasis  
4. keep the plan within the parent’s daily time budget  
5. rotate categories across the week  
6. ensure the final plan is realistic, short, and home-friendly  

The weekly schedule therefore depends on:
- time available
- severity / gap
- support tier
- what activities exist in each category bank

## 10. Live parent mode vs synthetic parent mode

### Live parent mode is best for:
- manual testing
- debugging specific cases
- discussing logic with advisors
- checking whether the interview feels natural

### Synthetic parent mode is best for:
- batch testing
- creating initial advisor packets
- benchmarking consistency
- finding edge cases

Synthetic parent mode is not meant to replace real parent input in production. It is a testing and review tool.

## 11. How advisor packets are created

For advisor review, we package each case as a 1-page summary with:

1. child profile  
2. parent input (question / answer transcript)  
3. Genex output (developmental estimates and support priorities)  
4. daily activities  
5. summary paragraph  
6. advisor review prompts  

In addition to the PDF case packet, we also create a structured rating sheet with columns such as:

- clinical appropriateness
- safety
- practicality for parents
- clarity
- overall usefulness
- open-text feedback

## 12. What is model-based vs rule-based

### Model-based components
- starting delay estimation by domain
- synthetic parent answers in synthetic mode
- category activity-bank generation

### Rule-based / deterministic components
- CDC table loading and question retrieval
- category mapping
- answer normalization
- band summaries
- developmental-age estimation from band confirmation
- support-tier assignment
- weekly slot allocation
- weekly schedule construction
- export structure

We intentionally kept the state tracking and scheduling logic deterministic because those are the parts we most want to inspect, defend, and improve transparently.

## 13. Why we chose the current parameter values

- **window_months = 24**  
  Wide enough to capture uncertainty, but still focused around the estimated developmental range.

- **target_questions_per_band = 3**  
  Gives enough evidence per band without making the interview too long.

- **max_bands = 3**  
  Lets us sample a lower, middle, and upper zone around the estimated developmental age.

- **max_questions_total = 9**  
  Keeps synthetic runs manageable and reduces API cost / rate-limit risk.

- **ask_limit_per_band = 3**  
  Matches the compact advisor-review design.

- **min_yes_confirm = 2**  
  Prevents overreacting to a single isolated yes.

- **yes_ratio_confirm = 0.60**  
  Slightly conservative, but more flexible than our earlier stricter threshold.

- **delay_between_questions_sec** in synthetic mode  
  Added to reduce rate-limit issues and keep synthetic-parent runs feasible.

- **daily_time_min**  
  Makes the plan realistic for actual families rather than outputting an idealized schedule.

- **3-tier support system**  
  Better than binary support/no-support because it allows lighter enrichment when a domain is not the top concern but still deserves attention.

## 14. What we expect advisors to help us refine

We see this notebook as an inspectable prototype, not a final clinical system. The parts we especially want advisor feedback on are:

- whether the milestone questions chosen feel like the right ones for the child’s level
- whether the developmental-age estimate feels too optimistic or too conservative
- whether the support tiers are set at the right thresholds
- whether the weekly plan gives the right balance across domains
- whether the activities are clinically appropriate and practical for real families
- whether some diagnoses or age groups need different tuning

## 15. How we see this evolving later

Later, in the real app, we do not expect to use a synthetic parent. That is only for testing and advisor review.

Our production direction is:

- real parent answers directly
- local logic handles state tracking and developmental estimation
- retrieval / RAG helps with grounded educational content
- the model helps mainly with:
  - final plan wording
  - doctor visit prep
  - Ask Genex / evidence-grounded Q&A
  - maybe clarifying messy free-text parent concerns

So we see this notebook as the prototype for the developmental interview and home-support planning engine, while the future Genex app will combine this with the retrieval-grounded RAG system we are building separately.

## 16. Summary of the current philosophy

The philosophy of this notebook is:

- use structured milestone references as the backbone
- use models where language flexibility helps
- keep state tracking and planning logic transparent
- prioritize practical home use
- make the system inspectable enough that expert advisors can tell us exactly what to fix

That is why we built it this way: we wanted something we could explain, test, critique, and iteratively improve with expert feedback rather than a black-box output generator.

# Genex Advisor Review Handout  
## Developmental Interview + Home Support Prototype (Ages 0–5)

Thank you for reviewing this early Genex prototype.

This packet contains sample child cases generated through our current developmental interview and home-support planning workflow for ages 0–5. Our goal at this stage is to evaluate whether the logic, developmental estimates, prioritization across domains, and suggested home activities feel clinically reasonable, practical, and safe.

This is still a prototype and is not intended to diagnose or replace clinical judgment. We are using this review process to identify where the system is working well, where it is too aggressive or too conservative, and what should be revised before further development.

## What this prototype is trying to do

This prototype takes a child’s basic profile, asks structured developmental milestone questions, estimates the child’s developmental level across key domains, and produces a realistic home support plan based on the parent’s available time.

The goal is not to diagnose, label, or replace clinical judgment. The goal is to create a transparent, structured first-pass tool that can help families identify priority areas, receive practical home suggestions, and prepare for more informed follow-up with clinicians.

## What information goes into the system

Each case begins with:
- child name
- age in months
- diagnosis or condition, if known
- parent concerns
- daily time available for home support

We use age in **months** rather than years because developmental milestones are much more sensitive to smaller age differences, especially in infancy and toddlerhood.

## What reference framework we use

The milestone interview is grounded in a structured CDC milestone table. We normalize those milestones into four working domains:

- Movement / Physical  
- Social / Emotional  
- Language / Communication  
- Cognitive / Adaptive  

We use the CDC-based milestone table to keep the question set structured, inspectable, and reproducible.

## How the interview works

The system does not ask every milestone at every age. Instead, it first estimates a rough **starting delay** in each domain based on:
- chronological age
- diagnosis / condition
- parent concerns
- the specific developmental domain

This starting delay is only used to decide **where to begin asking questions**.

From there, the system selects milestone questions around the most likely developmental range for that child in that domain. It asks a small set of milestone questions across a few nearby age bands, then summarizes the responses by band.

## How answers are collected

We currently support two modes:

### 1. Live parent mode  
A real person answers the milestone questions directly.

### 2. Synthetic parent mode  
A language model simulates the parent’s answers from the child profile, while the Genex logic still controls:
- which milestones are asked
- how answers are scored
- how developmental age is estimated
- how support is assigned

Synthetic mode is only for internal testing and advisor review. It is not intended to replace real parent input in a production product.

## How developmental age is estimated

For each domain, the notebook groups responses by milestone age band and looks for enough evidence to “confirm” a band. A band is currently treated as confirmed when it has:
- at least 2 strong “yes” responses
- and at least 60% yes answers within that band

If more than one band is confirmed, we use the highest confirmed band as the domain’s estimated developmental age.

## How support is assigned

Once developmental age is estimated in each domain, we compare it with chronological age and assign one of three support tiers:

- **Needs special support**  
- **Monitor and enrich**  
- **No special support**

We moved to this three-tier system because a binary yes/no support decision was too blunt. In practice, some domains do not need intensive support but still deserve light enrichment or monitoring.

We also made the support logic **age-aware**, because the meaning of a 4-month gap is different in a 10-month-old than in a 5-year-old.

## How activities are generated

The activity system works in two steps.

### Step 1: Category activity bank  
For each category that needs support or enrichment, the system builds a category-specific activity bank.

### Step 2: Weekly scheduling  
The system then builds a weekly plan from those category activity banks, using:
- parent daily time available
- support level by domain
- milestone gap by domain
- the activity durations

This helps us create a plan that is more realistic for home use.

## What is model-based vs rule-based

### Model-based components
- rough starting delay estimate by domain
- synthetic parent answers in synthetic mode
- activity-bank wording and activity suggestions

### Rule-based components
- milestone table loading and normalization
- milestone question selection
- answer normalization
- developmental age estimation
- support-tier assignment
- weekly slot allocation
- weekly schedule construction
- case export format

## What we want feedback on

We would especially value feedback on:
- clinical appropriateness
- developmental-age calibration
- support allocation across domains
- practicality for families
- clarity for parents
- safety / caution
- anything important that feels missing

## Current limitations

This is still a prototype and has important limitations:
- it is not diagnostic
- it does not replace developmental or therapeutic assessment
- synthetic-parent mode is only for internal testing
- milestone thresholds and support logic are still being tuned
- some diagnoses and age bands may need different calibration

## Why your feedback matters

Your feedback will directly shape:
- milestone selection logic
- developmental-age calibration
- support-tier thresholds
- activity quality
- report structure
- future doctor-visit preparation and parent-facing product flows

# Short Cover Note

**Dear Advisor,**

Thank you for reviewing this early Genex prototype.

This packet contains sample child cases generated through our current developmental interview and home-support planning workflow for ages 0–5. Our goal at this stage is to evaluate whether the logic, developmental estimates, prioritization across domains, and suggested home activities feel clinically reasonable, practical, and safe.

This is still a prototype and is not intended to diagnose or replace clinical judgment. We are using this review process to identify where the system is working well, where it is too aggressive or too conservative, and what should be revised before further development.

Your feedback on appropriateness, clarity, practicality, safety, and missing elements would be incredibly valuable.

**Best,**  
**Sara / Genex**